<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Encore.Domain\Encore.Domain.csproj" />
    <ProjectReference Include="..\Encore.Infra.CrossCutting\Encore.Infra.CrossCutting.csproj" />
    <ProjectReference Include="..\Encore.Infra.Data\Encore.Infra.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Home\" />
  </ItemGroup>

</Project>
