/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class ParticipanteRowItemThrift : TBase
{
  private string _cnsParticipante;
  private long _dataNascimento;
  private bool _avaliacaoAlterada;
  private double _peso;
  private double _altura;
  private bool _cessouHabitoFumar;
  private bool _abandonouGrupo;
  private long _sexo;
  private string _cpfParticipante;

  public string CnsParticipante
  {
    get
    {
      return _cnsParticipante;
    }
    set
    {
      __isset.cnsParticipante = true;
      this._cnsParticipante = value;
    }
  }

  public long DataNascimento
  {
    get
    {
      return _dataNascimento;
    }
    set
    {
      __isset.dataNascimento = true;
      this._dataNascimento = value;
    }
  }

  public bool AvaliacaoAlterada
  {
    get
    {
      return _avaliacaoAlterada;
    }
    set
    {
      __isset.avaliacaoAlterada = true;
      this._avaliacaoAlterada = value;
    }
  }

  public double Peso
  {
    get
    {
      return _peso;
    }
    set
    {
      __isset.@peso = true;
      this._peso = value;
    }
  }

  public double Altura
  {
    get
    {
      return _altura;
    }
    set
    {
      __isset.@altura = true;
      this._altura = value;
    }
  }

  public bool CessouHabitoFumar
  {
    get
    {
      return _cessouHabitoFumar;
    }
    set
    {
      __isset.cessouHabitoFumar = true;
      this._cessouHabitoFumar = value;
    }
  }

  public bool AbandonouGrupo
  {
    get
    {
      return _abandonouGrupo;
    }
    set
    {
      __isset.abandonouGrupo = true;
      this._abandonouGrupo = value;
    }
  }

  public long Sexo
  {
    get
    {
      return _sexo;
    }
    set
    {
      __isset.@sexo = true;
      this._sexo = value;
    }
  }

  public string CpfParticipante
  {
    get
    {
      return _cpfParticipante;
    }
    set
    {
      __isset.cpfParticipante = true;
      this._cpfParticipante = value;
    }
  }


  public ParticipanteRowItem __isset;
  public struct ParticipanteRowItem
    {
    public bool cnsParticipante;
    public bool dataNascimento;
    public bool avaliacaoAlterada;
    public bool @peso;
    public bool @altura;
    public bool cessouHabitoFumar;
    public bool abandonouGrupo;
    public bool @sexo;
    public bool cpfParticipante;
  }

  public ParticipanteRowItemThrift()
  {
  }

  public ParticipanteRowItemThrift DeepCopy()
  {
    var tmp0 = new ParticipanteRowItemThrift();
    if((CnsParticipante != null) && __isset.cnsParticipante)
    {
      tmp0.CnsParticipante = this.CnsParticipante;
    }
    tmp0.__isset.cnsParticipante = this.__isset.cnsParticipante;
    if(__isset.dataNascimento)
    {
      tmp0.DataNascimento = this.DataNascimento;
    }
    tmp0.__isset.dataNascimento = this.__isset.dataNascimento;
    if(__isset.avaliacaoAlterada)
    {
      tmp0.AvaliacaoAlterada = this.AvaliacaoAlterada;
    }
    tmp0.__isset.avaliacaoAlterada = this.__isset.avaliacaoAlterada;
    if(__isset.@peso)
    {
      tmp0.Peso = this.Peso;
    }
    tmp0.__isset.@peso = this.__isset.@peso;
    if(__isset.@altura)
    {
      tmp0.Altura = this.Altura;
    }
    tmp0.__isset.@altura = this.__isset.@altura;
    if(__isset.cessouHabitoFumar)
    {
      tmp0.CessouHabitoFumar = this.CessouHabitoFumar;
    }
    tmp0.__isset.cessouHabitoFumar = this.__isset.cessouHabitoFumar;
    if(__isset.abandonouGrupo)
    {
      tmp0.AbandonouGrupo = this.AbandonouGrupo;
    }
    tmp0.__isset.abandonouGrupo = this.__isset.abandonouGrupo;
    if(__isset.@sexo)
    {
      tmp0.Sexo = this.Sexo;
    }
    tmp0.__isset.@sexo = this.__isset.@sexo;
    if((CpfParticipante != null) && __isset.cpfParticipante)
    {
      tmp0.CpfParticipante = this.CpfParticipante;
    }
    tmp0.__isset.cpfParticipante = this.__isset.cpfParticipante;
    return tmp0;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              CnsParticipante = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              DataNascimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Bool)
            {
              AvaliacaoAlterada = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.Double)
            {
              Peso = await iprot.ReadDoubleAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.Double)
            {
              Altura = await iprot.ReadDoubleAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.Bool)
            {
              CessouHabitoFumar = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.Bool)
            {
              AbandonouGrupo = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.I64)
            {
              Sexo = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.String)
            {
              CpfParticipante = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp1 = new TStruct("ParticipanteRowItemThrift");
      await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
      var tmp2 = new TField();
      if((CnsParticipante != null) && __isset.cnsParticipante)
      {
        tmp2.Name = "cnsParticipante";
        tmp2.Type = TType.String;
        tmp2.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(CnsParticipante, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataNascimento)
      {
        tmp2.Name = "dataNascimento";
        tmp2.Type = TType.I64;
        tmp2.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(DataNascimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.avaliacaoAlterada)
      {
        tmp2.Name = "avaliacaoAlterada";
        tmp2.Type = TType.Bool;
        tmp2.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteBoolAsync(AvaliacaoAlterada, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@peso)
      {
        tmp2.Name = "peso";
        tmp2.Type = TType.Double;
        tmp2.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteDoubleAsync(Peso, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@altura)
      {
        tmp2.Name = "altura";
        tmp2.Type = TType.Double;
        tmp2.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteDoubleAsync(Altura, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.cessouHabitoFumar)
      {
        tmp2.Name = "cessouHabitoFumar";
        tmp2.Type = TType.Bool;
        tmp2.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteBoolAsync(CessouHabitoFumar, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.abandonouGrupo)
      {
        tmp2.Name = "abandonouGrupo";
        tmp2.Type = TType.Bool;
        tmp2.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteBoolAsync(AbandonouGrupo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@sexo)
      {
        tmp2.Name = "sexo";
        tmp2.Type = TType.I64;
        tmp2.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(Sexo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CpfParticipante != null) && __isset.cpfParticipante)
      {
        tmp2.Name = "cpfParticipante";
        tmp2.Type = TType.String;
        tmp2.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(CpfParticipante, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is ParticipanteRowItemThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.cnsParticipante == other.__isset.cnsParticipante) && ((!__isset.cnsParticipante) || (global::System.Object.Equals(CnsParticipante, other.CnsParticipante))))
      && ((__isset.dataNascimento == other.__isset.dataNascimento) && ((!__isset.dataNascimento) || (global::System.Object.Equals(DataNascimento, other.DataNascimento))))
      && ((__isset.avaliacaoAlterada == other.__isset.avaliacaoAlterada) && ((!__isset.avaliacaoAlterada) || (global::System.Object.Equals(AvaliacaoAlterada, other.AvaliacaoAlterada))))
      && ((__isset.@peso == other.__isset.@peso) && ((!__isset.@peso) || (global::System.Object.Equals(Peso, other.Peso))))
      && ((__isset.@altura == other.__isset.@altura) && ((!__isset.@altura) || (global::System.Object.Equals(Altura, other.Altura))))
      && ((__isset.cessouHabitoFumar == other.__isset.cessouHabitoFumar) && ((!__isset.cessouHabitoFumar) || (global::System.Object.Equals(CessouHabitoFumar, other.CessouHabitoFumar))))
      && ((__isset.abandonouGrupo == other.__isset.abandonouGrupo) && ((!__isset.abandonouGrupo) || (global::System.Object.Equals(AbandonouGrupo, other.AbandonouGrupo))))
      && ((__isset.@sexo == other.__isset.@sexo) && ((!__isset.@sexo) || (global::System.Object.Equals(Sexo, other.Sexo))))
      && ((__isset.cpfParticipante == other.__isset.cpfParticipante) && ((!__isset.cpfParticipante) || (global::System.Object.Equals(CpfParticipante, other.CpfParticipante))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((CnsParticipante != null) && __isset.cnsParticipante)
      {
        hashcode = (hashcode * 397) + CnsParticipante.GetHashCode();
      }
      if(__isset.dataNascimento)
      {
        hashcode = (hashcode * 397) + DataNascimento.GetHashCode();
      }
      if(__isset.avaliacaoAlterada)
      {
        hashcode = (hashcode * 397) + AvaliacaoAlterada.GetHashCode();
      }
      if(__isset.@peso)
      {
        hashcode = (hashcode * 397) + Peso.GetHashCode();
      }
      if(__isset.@altura)
      {
        hashcode = (hashcode * 397) + Altura.GetHashCode();
      }
      if(__isset.cessouHabitoFumar)
      {
        hashcode = (hashcode * 397) + CessouHabitoFumar.GetHashCode();
      }
      if(__isset.abandonouGrupo)
      {
        hashcode = (hashcode * 397) + AbandonouGrupo.GetHashCode();
      }
      if(__isset.@sexo)
      {
        hashcode = (hashcode * 397) + Sexo.GetHashCode();
      }
      if((CpfParticipante != null) && __isset.cpfParticipante)
      {
        hashcode = (hashcode * 397) + CpfParticipante.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp3 = new StringBuilder("ParticipanteRowItemThrift(");
    int tmp4 = 0;
    if((CnsParticipante != null) && __isset.cnsParticipante)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CnsParticipante: ");
      CnsParticipante.ToString(tmp3);
    }
    if(__isset.dataNascimento)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("DataNascimento: ");
      DataNascimento.ToString(tmp3);
    }
    if(__isset.avaliacaoAlterada)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("AvaliacaoAlterada: ");
      AvaliacaoAlterada.ToString(tmp3);
    }
    if(__isset.@peso)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Peso: ");
      Peso.ToString(tmp3);
    }
    if(__isset.@altura)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Altura: ");
      Altura.ToString(tmp3);
    }
    if(__isset.cessouHabitoFumar)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CessouHabitoFumar: ");
      CessouHabitoFumar.ToString(tmp3);
    }
    if(__isset.abandonouGrupo)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("AbandonouGrupo: ");
      AbandonouGrupo.ToString(tmp3);
    }
    if(__isset.@sexo)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Sexo: ");
      Sexo.ToString(tmp3);
    }
    if((CpfParticipante != null) && __isset.cpfParticipante)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CpfParticipante: ");
      CpfParticipante.ToString(tmp3);
    }
    tmp3.Append(')');
    return tmp3.ToString();
  }
}

