/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class CidadaoTransportThrift : TBase
{
  private string _cpf;
  private string _nomeMae;
  private string _email;
  private EnderecoTransportThrift _endereco;
  private long _escolaridadeId;
  private long _estadoCivilId;
  private long _etniaId;
  private bool _faleceu;
  private string _municipioNascimentoIbge;
  private string _nisPisPasep;
  private string _nomeSocial;
  private string _numeroProntuario;
  private string _numeroProntuarioCnes;
  private string _telefoneCelular;
  private string _telefoneContato;
  private string _telefoneResidencial;
  private TipoSanguineoThrift _tipoSanguineo;
  private string _cboNumero;

  public bool NaoPossuiCns { get; set; }

  public string Cns { get; set; }

  public string Cpf
  {
    get
    {
      return _cpf;
    }
    set
    {
      __isset.@cpf = true;
      this._cpf = value;
    }
  }

  public long DataNascimento { get; set; }

  public bool DesconheceNomeMae { get; set; }

  public string NomeMae
  {
    get
    {
      return _nomeMae;
    }
    set
    {
      __isset.nomeMae = true;
      this._nomeMae = value;
    }
  }

  public string Email
  {
    get
    {
      return _email;
    }
    set
    {
      __isset.@email = true;
      this._email = value;
    }
  }

  public EnderecoTransportThrift Endereco
  {
    get
    {
      return _endereco;
    }
    set
    {
      __isset.@endereco = true;
      this._endereco = value;
    }
  }

  public long EscolaridadeId
  {
    get
    {
      return _escolaridadeId;
    }
    set
    {
      __isset.escolaridadeId = true;
      this._escolaridadeId = value;
    }
  }

  public long EstadoCivilId
  {
    get
    {
      return _estadoCivilId;
    }
    set
    {
      __isset.estadoCivilId = true;
      this._estadoCivilId = value;
    }
  }

  public bool Estrangeiro { get; set; }

  public long EtniaId
  {
    get
    {
      return _etniaId;
    }
    set
    {
      __isset.etniaId = true;
      this._etniaId = value;
    }
  }

  public bool Faleceu
  {
    get
    {
      return _faleceu;
    }
    set
    {
      __isset.@faleceu = true;
      this._faleceu = value;
    }
  }

  public string MunicipioNascimentoCep { get; set; }

  public string MunicipioNascimentoDne { get; set; }

  public string MunicipioNascimentoIbge
  {
    get
    {
      return _municipioNascimentoIbge;
    }
    set
    {
      __isset.municipioNascimentoIbge = true;
      this._municipioNascimentoIbge = value;
    }
  }

  public string NisPisPasep
  {
    get
    {
      return _nisPisPasep;
    }
    set
    {
      __isset.nisPisPasep = true;
      this._nisPisPasep = value;
    }
  }

  public string NomeCompleto { get; set; }

  public string NomeSocial
  {
    get
    {
      return _nomeSocial;
    }
    set
    {
      __isset.nomeSocial = true;
      this._nomeSocial = value;
    }
  }

  public string NumeroProntuario
  {
    get
    {
      return _numeroProntuario;
    }
    set
    {
      __isset.numeroProntuario = true;
      this._numeroProntuario = value;
    }
  }

  public string NumeroProntuarioCnes
  {
    get
    {
      return _numeroProntuarioCnes;
    }
    set
    {
      __isset.numeroProntuarioCnes = true;
      this._numeroProntuarioCnes = value;
    }
  }

  public long RacaCorId { get; set; }

  /// <summary>
  /// 
  /// <seealso cref="global::.SexoThrift"/>
  /// </summary>
  public SexoThrift Sexo { get; set; }

  public string TelefoneCelular
  {
    get
    {
      return _telefoneCelular;
    }
    set
    {
      __isset.telefoneCelular = true;
      this._telefoneCelular = value;
    }
  }

  public string TelefoneContato
  {
    get
    {
      return _telefoneContato;
    }
    set
    {
      __isset.telefoneContato = true;
      this._telefoneContato = value;
    }
  }

  public string TelefoneResidencial
  {
    get
    {
      return _telefoneResidencial;
    }
    set
    {
      __isset.telefoneResidencial = true;
      this._telefoneResidencial = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref="global::.TipoSanguineoThrift"/>
  /// </summary>
  public TipoSanguineoThrift TipoSanguineo
  {
    get
    {
      return _tipoSanguineo;
    }
    set
    {
      __isset.tipoSanguineo = true;
      this._tipoSanguineo = value;
    }
  }

  public string CboNumero
  {
    get
    {
      return _cboNumero;
    }
    set
    {
      __isset.cboNumero = true;
      this._cboNumero = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool @cpf;
    public bool nomeMae;
    public bool @email;
    public bool @endereco;
    public bool escolaridadeId;
    public bool estadoCivilId;
    public bool etniaId;
    public bool @faleceu;
    public bool municipioNascimentoIbge;
    public bool nisPisPasep;
    public bool nomeSocial;
    public bool numeroProntuario;
    public bool numeroProntuarioCnes;
    public bool telefoneCelular;
    public bool telefoneContato;
    public bool telefoneResidencial;
    public bool tipoSanguineo;
    public bool cboNumero;
  }

  public CidadaoTransportThrift()
  {
  }

  public CidadaoTransportThrift(bool naoPossuiCns, string @cns, long dataNascimento, bool desconheceNomeMae, bool @estrangeiro, string municipioNascimentoCep, string municipioNascimentoDne, string nomeCompleto, long racaCorId, SexoThrift @sexo) : this()
  {
    this.NaoPossuiCns = naoPossuiCns;
    this.Cns = @cns;
    this.DataNascimento = dataNascimento;
    this.DesconheceNomeMae = desconheceNomeMae;
    this.Estrangeiro = @estrangeiro;
    this.MunicipioNascimentoCep = municipioNascimentoCep;
    this.MunicipioNascimentoDne = municipioNascimentoDne;
    this.NomeCompleto = nomeCompleto;
    this.RacaCorId = racaCorId;
    this.Sexo = @sexo;
  }

  public CidadaoTransportThrift DeepCopy()
  {
    var tmp5 = new CidadaoTransportThrift();
    tmp5.NaoPossuiCns = this.NaoPossuiCns;
    if((Cns != null))
    {
      tmp5.Cns = this.Cns;
    }
    if((Cpf != null) && __isset.@cpf)
    {
      tmp5.Cpf = this.Cpf;
    }
    tmp5.__isset.@cpf = this.__isset.@cpf;
    tmp5.DataNascimento = this.DataNascimento;
    tmp5.DesconheceNomeMae = this.DesconheceNomeMae;
    if((NomeMae != null) && __isset.nomeMae)
    {
      tmp5.NomeMae = this.NomeMae;
    }
    tmp5.__isset.nomeMae = this.__isset.nomeMae;
    if((Email != null) && __isset.@email)
    {
      tmp5.Email = this.Email;
    }
    tmp5.__isset.@email = this.__isset.@email;
    if((Endereco != null) && __isset.@endereco)
    {
      tmp5.Endereco = (EnderecoTransportThrift)this.Endereco.DeepCopy();
    }
    tmp5.__isset.@endereco = this.__isset.@endereco;
    if(__isset.escolaridadeId)
    {
      tmp5.EscolaridadeId = this.EscolaridadeId;
    }
    tmp5.__isset.escolaridadeId = this.__isset.escolaridadeId;
    if(__isset.estadoCivilId)
    {
      tmp5.EstadoCivilId = this.EstadoCivilId;
    }
    tmp5.__isset.estadoCivilId = this.__isset.estadoCivilId;
    tmp5.Estrangeiro = this.Estrangeiro;
    if(__isset.etniaId)
    {
      tmp5.EtniaId = this.EtniaId;
    }
    tmp5.__isset.etniaId = this.__isset.etniaId;
    if(__isset.@faleceu)
    {
      tmp5.Faleceu = this.Faleceu;
    }
    tmp5.__isset.@faleceu = this.__isset.@faleceu;
    if((MunicipioNascimentoCep != null))
    {
      tmp5.MunicipioNascimentoCep = this.MunicipioNascimentoCep;
    }
    if((MunicipioNascimentoDne != null))
    {
      tmp5.MunicipioNascimentoDne = this.MunicipioNascimentoDne;
    }
    if((MunicipioNascimentoIbge != null) && __isset.municipioNascimentoIbge)
    {
      tmp5.MunicipioNascimentoIbge = this.MunicipioNascimentoIbge;
    }
    tmp5.__isset.municipioNascimentoIbge = this.__isset.municipioNascimentoIbge;
    if((NisPisPasep != null) && __isset.nisPisPasep)
    {
      tmp5.NisPisPasep = this.NisPisPasep;
    }
    tmp5.__isset.nisPisPasep = this.__isset.nisPisPasep;
    if((NomeCompleto != null))
    {
      tmp5.NomeCompleto = this.NomeCompleto;
    }
    if((NomeSocial != null) && __isset.nomeSocial)
    {
      tmp5.NomeSocial = this.NomeSocial;
    }
    tmp5.__isset.nomeSocial = this.__isset.nomeSocial;
    if((NumeroProntuario != null) && __isset.numeroProntuario)
    {
      tmp5.NumeroProntuario = this.NumeroProntuario;
    }
    tmp5.__isset.numeroProntuario = this.__isset.numeroProntuario;
    if((NumeroProntuarioCnes != null) && __isset.numeroProntuarioCnes)
    {
      tmp5.NumeroProntuarioCnes = this.NumeroProntuarioCnes;
    }
    tmp5.__isset.numeroProntuarioCnes = this.__isset.numeroProntuarioCnes;
    tmp5.RacaCorId = this.RacaCorId;
    tmp5.Sexo = this.Sexo;
    if((TelefoneCelular != null) && __isset.telefoneCelular)
    {
      tmp5.TelefoneCelular = this.TelefoneCelular;
    }
    tmp5.__isset.telefoneCelular = this.__isset.telefoneCelular;
    if((TelefoneContato != null) && __isset.telefoneContato)
    {
      tmp5.TelefoneContato = this.TelefoneContato;
    }
    tmp5.__isset.telefoneContato = this.__isset.telefoneContato;
    if((TelefoneResidencial != null) && __isset.telefoneResidencial)
    {
      tmp5.TelefoneResidencial = this.TelefoneResidencial;
    }
    tmp5.__isset.telefoneResidencial = this.__isset.telefoneResidencial;
    if(__isset.tipoSanguineo)
    {
      tmp5.TipoSanguineo = this.TipoSanguineo;
    }
    tmp5.__isset.tipoSanguineo = this.__isset.tipoSanguineo;
    if((CboNumero != null) && __isset.cboNumero)
    {
      tmp5.CboNumero = this.CboNumero;
    }
    tmp5.__isset.cboNumero = this.__isset.cboNumero;
    return tmp5;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_naoPossuiCns = false;
      bool isset_cns = false;
      bool isset_dataNascimento = false;
      bool isset_desconheceNomeMae = false;
      bool isset_estrangeiro = false;
      bool isset_municipioNascimentoCep = false;
      bool isset_municipioNascimentoDne = false;
      bool isset_nomeCompleto = false;
      bool isset_racaCorId = false;
      bool isset_sexo = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool)
            {
              NaoPossuiCns = await iprot.ReadBoolAsync(cancellationToken);
              isset_naoPossuiCns = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Cns = await iprot.ReadStringAsync(cancellationToken);
              isset_cns = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              Cpf = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I64)
            {
              DataNascimento = await iprot.ReadI64Async(cancellationToken);
              isset_dataNascimento = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.Bool)
            {
              DesconheceNomeMae = await iprot.ReadBoolAsync(cancellationToken);
              isset_desconheceNomeMae = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.String)
            {
              NomeMae = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.String)
            {
              Email = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.Struct)
            {
              Endereco = new EnderecoTransportThrift();
              await Endereco.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.I64)
            {
              EscolaridadeId = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.I64)
            {
              EstadoCivilId = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.Bool)
            {
              Estrangeiro = await iprot.ReadBoolAsync(cancellationToken);
              isset_estrangeiro = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.I64)
            {
              EtniaId = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.Bool)
            {
              Faleceu = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 14:
            if (field.Type == TType.String)
            {
              MunicipioNascimentoCep = await iprot.ReadStringAsync(cancellationToken);
              isset_municipioNascimentoCep = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 15:
            if (field.Type == TType.String)
            {
              MunicipioNascimentoDne = await iprot.ReadStringAsync(cancellationToken);
              isset_municipioNascimentoDne = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 16:
            if (field.Type == TType.String)
            {
              MunicipioNascimentoIbge = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 17:
            if (field.Type == TType.String)
            {
              NisPisPasep = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 18:
            if (field.Type == TType.String)
            {
              NomeCompleto = await iprot.ReadStringAsync(cancellationToken);
              isset_nomeCompleto = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 19:
            if (field.Type == TType.String)
            {
              NomeSocial = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 20:
            if (field.Type == TType.String)
            {
              NumeroProntuario = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 22:
            if (field.Type == TType.String)
            {
              NumeroProntuarioCnes = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 23:
            if (field.Type == TType.I64)
            {
              RacaCorId = await iprot.ReadI64Async(cancellationToken);
              isset_racaCorId = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 24:
            if (field.Type == TType.I32)
            {
              Sexo = (SexoThrift)await iprot.ReadI32Async(cancellationToken);
              isset_sexo = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 25:
            if (field.Type == TType.String)
            {
              TelefoneCelular = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 26:
            if (field.Type == TType.String)
            {
              TelefoneContato = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 27:
            if (field.Type == TType.String)
            {
              TelefoneResidencial = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 28:
            if (field.Type == TType.I32)
            {
              TipoSanguineo = (TipoSanguineoThrift)await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 29:
            if (field.Type == TType.String)
            {
              CboNumero = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_naoPossuiCns)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_cns)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_dataNascimento)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_desconheceNomeMae)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_estrangeiro)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_municipioNascimentoCep)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_municipioNascimentoDne)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_nomeCompleto)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_racaCorId)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_sexo)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp6 = new TStruct("CidadaoTransportThrift");
      await oprot.WriteStructBeginAsync(tmp6, cancellationToken);
      var tmp7 = new TField();
      tmp7.Name = "naoPossuiCns";
      tmp7.Type = TType.Bool;
      tmp7.ID = 1;
      await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
      await oprot.WriteBoolAsync(NaoPossuiCns, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if((Cns != null))
      {
        tmp7.Name = "cns";
        tmp7.Type = TType.String;
        tmp7.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Cns, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Cpf != null) && __isset.@cpf)
      {
        tmp7.Name = "cpf";
        tmp7.Type = TType.String;
        tmp7.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Cpf, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      tmp7.Name = "dataNascimento";
      tmp7.Type = TType.I64;
      tmp7.ID = 4;
      await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
      await oprot.WriteI64Async(DataNascimento, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      tmp7.Name = "desconheceNomeMae";
      tmp7.Type = TType.Bool;
      tmp7.ID = 5;
      await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
      await oprot.WriteBoolAsync(DesconheceNomeMae, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if((NomeMae != null) && __isset.nomeMae)
      {
        tmp7.Name = "nomeMae";
        tmp7.Type = TType.String;
        tmp7.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NomeMae, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Email != null) && __isset.@email)
      {
        tmp7.Name = "email";
        tmp7.Type = TType.String;
        tmp7.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Email, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Endereco != null) && __isset.@endereco)
      {
        tmp7.Name = "endereco";
        tmp7.Type = TType.Struct;
        tmp7.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await Endereco.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.escolaridadeId)
      {
        tmp7.Name = "escolaridadeId";
        tmp7.Type = TType.I64;
        tmp7.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteI64Async(EscolaridadeId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.estadoCivilId)
      {
        tmp7.Name = "estadoCivilId";
        tmp7.Type = TType.I64;
        tmp7.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteI64Async(EstadoCivilId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      tmp7.Name = "estrangeiro";
      tmp7.Type = TType.Bool;
      tmp7.ID = 11;
      await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
      await oprot.WriteBoolAsync(Estrangeiro, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if(__isset.etniaId)
      {
        tmp7.Name = "etniaId";
        tmp7.Type = TType.I64;
        tmp7.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteI64Async(EtniaId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@faleceu)
      {
        tmp7.Name = "faleceu";
        tmp7.Type = TType.Bool;
        tmp7.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteBoolAsync(Faleceu, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MunicipioNascimentoCep != null))
      {
        tmp7.Name = "municipioNascimentoCep";
        tmp7.Type = TType.String;
        tmp7.ID = 14;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(MunicipioNascimentoCep, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MunicipioNascimentoDne != null))
      {
        tmp7.Name = "municipioNascimentoDne";
        tmp7.Type = TType.String;
        tmp7.ID = 15;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(MunicipioNascimentoDne, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MunicipioNascimentoIbge != null) && __isset.municipioNascimentoIbge)
      {
        tmp7.Name = "municipioNascimentoIbge";
        tmp7.Type = TType.String;
        tmp7.ID = 16;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(MunicipioNascimentoIbge, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NisPisPasep != null) && __isset.nisPisPasep)
      {
        tmp7.Name = "nisPisPasep";
        tmp7.Type = TType.String;
        tmp7.ID = 17;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NisPisPasep, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeCompleto != null))
      {
        tmp7.Name = "nomeCompleto";
        tmp7.Type = TType.String;
        tmp7.ID = 18;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NomeCompleto, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeSocial != null) && __isset.nomeSocial)
      {
        tmp7.Name = "nomeSocial";
        tmp7.Type = TType.String;
        tmp7.ID = 19;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NomeSocial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NumeroProntuario != null) && __isset.numeroProntuario)
      {
        tmp7.Name = "numeroProntuario";
        tmp7.Type = TType.String;
        tmp7.ID = 20;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NumeroProntuario, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NumeroProntuarioCnes != null) && __isset.numeroProntuarioCnes)
      {
        tmp7.Name = "numeroProntuarioCnes";
        tmp7.Type = TType.String;
        tmp7.ID = 22;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NumeroProntuarioCnes, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      tmp7.Name = "racaCorId";
      tmp7.Type = TType.I64;
      tmp7.ID = 23;
      await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
      await oprot.WriteI64Async(RacaCorId, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      tmp7.Name = "sexo";
      tmp7.Type = TType.I32;
      tmp7.ID = 24;
      await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
      await oprot.WriteI32Async((int)Sexo, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if((TelefoneCelular != null) && __isset.telefoneCelular)
      {
        tmp7.Name = "telefoneCelular";
        tmp7.Type = TType.String;
        tmp7.ID = 25;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(TelefoneCelular, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TelefoneContato != null) && __isset.telefoneContato)
      {
        tmp7.Name = "telefoneContato";
        tmp7.Type = TType.String;
        tmp7.ID = 26;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(TelefoneContato, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TelefoneResidencial != null) && __isset.telefoneResidencial)
      {
        tmp7.Name = "telefoneResidencial";
        tmp7.Type = TType.String;
        tmp7.ID = 27;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(TelefoneResidencial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.tipoSanguineo)
      {
        tmp7.Name = "tipoSanguineo";
        tmp7.Type = TType.I32;
        tmp7.ID = 28;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteI32Async((int)TipoSanguineo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CboNumero != null) && __isset.cboNumero)
      {
        tmp7.Name = "cboNumero";
        tmp7.Type = TType.String;
        tmp7.ID = 29;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(CboNumero, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is CidadaoTransportThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(NaoPossuiCns, other.NaoPossuiCns)
      && global::System.Object.Equals(Cns, other.Cns)
      && ((__isset.@cpf == other.__isset.@cpf) && ((!__isset.@cpf) || (global::System.Object.Equals(Cpf, other.Cpf))))
      && global::System.Object.Equals(DataNascimento, other.DataNascimento)
      && global::System.Object.Equals(DesconheceNomeMae, other.DesconheceNomeMae)
      && ((__isset.nomeMae == other.__isset.nomeMae) && ((!__isset.nomeMae) || (global::System.Object.Equals(NomeMae, other.NomeMae))))
      && ((__isset.@email == other.__isset.@email) && ((!__isset.@email) || (global::System.Object.Equals(Email, other.Email))))
      && ((__isset.@endereco == other.__isset.@endereco) && ((!__isset.@endereco) || (global::System.Object.Equals(Endereco, other.Endereco))))
      && ((__isset.escolaridadeId == other.__isset.escolaridadeId) && ((!__isset.escolaridadeId) || (global::System.Object.Equals(EscolaridadeId, other.EscolaridadeId))))
      && ((__isset.estadoCivilId == other.__isset.estadoCivilId) && ((!__isset.estadoCivilId) || (global::System.Object.Equals(EstadoCivilId, other.EstadoCivilId))))
      && global::System.Object.Equals(Estrangeiro, other.Estrangeiro)
      && ((__isset.etniaId == other.__isset.etniaId) && ((!__isset.etniaId) || (global::System.Object.Equals(EtniaId, other.EtniaId))))
      && ((__isset.@faleceu == other.__isset.@faleceu) && ((!__isset.@faleceu) || (global::System.Object.Equals(Faleceu, other.Faleceu))))
      && global::System.Object.Equals(MunicipioNascimentoCep, other.MunicipioNascimentoCep)
      && global::System.Object.Equals(MunicipioNascimentoDne, other.MunicipioNascimentoDne)
      && ((__isset.municipioNascimentoIbge == other.__isset.municipioNascimentoIbge) && ((!__isset.municipioNascimentoIbge) || (global::System.Object.Equals(MunicipioNascimentoIbge, other.MunicipioNascimentoIbge))))
      && ((__isset.nisPisPasep == other.__isset.nisPisPasep) && ((!__isset.nisPisPasep) || (global::System.Object.Equals(NisPisPasep, other.NisPisPasep))))
      && global::System.Object.Equals(NomeCompleto, other.NomeCompleto)
      && ((__isset.nomeSocial == other.__isset.nomeSocial) && ((!__isset.nomeSocial) || (global::System.Object.Equals(NomeSocial, other.NomeSocial))))
      && ((__isset.numeroProntuario == other.__isset.numeroProntuario) && ((!__isset.numeroProntuario) || (global::System.Object.Equals(NumeroProntuario, other.NumeroProntuario))))
      && ((__isset.numeroProntuarioCnes == other.__isset.numeroProntuarioCnes) && ((!__isset.numeroProntuarioCnes) || (global::System.Object.Equals(NumeroProntuarioCnes, other.NumeroProntuarioCnes))))
      && global::System.Object.Equals(RacaCorId, other.RacaCorId)
      && global::System.Object.Equals(Sexo, other.Sexo)
      && ((__isset.telefoneCelular == other.__isset.telefoneCelular) && ((!__isset.telefoneCelular) || (global::System.Object.Equals(TelefoneCelular, other.TelefoneCelular))))
      && ((__isset.telefoneContato == other.__isset.telefoneContato) && ((!__isset.telefoneContato) || (global::System.Object.Equals(TelefoneContato, other.TelefoneContato))))
      && ((__isset.telefoneResidencial == other.__isset.telefoneResidencial) && ((!__isset.telefoneResidencial) || (global::System.Object.Equals(TelefoneResidencial, other.TelefoneResidencial))))
      && ((__isset.tipoSanguineo == other.__isset.tipoSanguineo) && ((!__isset.tipoSanguineo) || (global::System.Object.Equals(TipoSanguineo, other.TipoSanguineo))))
      && ((__isset.cboNumero == other.__isset.cboNumero) && ((!__isset.cboNumero) || (global::System.Object.Equals(CboNumero, other.CboNumero))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      hashcode = (hashcode * 397) + NaoPossuiCns.GetHashCode();
      if((Cns != null))
      {
        hashcode = (hashcode * 397) + Cns.GetHashCode();
      }
      if((Cpf != null) && __isset.@cpf)
      {
        hashcode = (hashcode * 397) + Cpf.GetHashCode();
      }
      hashcode = (hashcode * 397) + DataNascimento.GetHashCode();
      hashcode = (hashcode * 397) + DesconheceNomeMae.GetHashCode();
      if((NomeMae != null) && __isset.nomeMae)
      {
        hashcode = (hashcode * 397) + NomeMae.GetHashCode();
      }
      if((Email != null) && __isset.@email)
      {
        hashcode = (hashcode * 397) + Email.GetHashCode();
      }
      if((Endereco != null) && __isset.@endereco)
      {
        hashcode = (hashcode * 397) + Endereco.GetHashCode();
      }
      if(__isset.escolaridadeId)
      {
        hashcode = (hashcode * 397) + EscolaridadeId.GetHashCode();
      }
      if(__isset.estadoCivilId)
      {
        hashcode = (hashcode * 397) + EstadoCivilId.GetHashCode();
      }
      hashcode = (hashcode * 397) + Estrangeiro.GetHashCode();
      if(__isset.etniaId)
      {
        hashcode = (hashcode * 397) + EtniaId.GetHashCode();
      }
      if(__isset.@faleceu)
      {
        hashcode = (hashcode * 397) + Faleceu.GetHashCode();
      }
      if((MunicipioNascimentoCep != null))
      {
        hashcode = (hashcode * 397) + MunicipioNascimentoCep.GetHashCode();
      }
      if((MunicipioNascimentoDne != null))
      {
        hashcode = (hashcode * 397) + MunicipioNascimentoDne.GetHashCode();
      }
      if((MunicipioNascimentoIbge != null) && __isset.municipioNascimentoIbge)
      {
        hashcode = (hashcode * 397) + MunicipioNascimentoIbge.GetHashCode();
      }
      if((NisPisPasep != null) && __isset.nisPisPasep)
      {
        hashcode = (hashcode * 397) + NisPisPasep.GetHashCode();
      }
      if((NomeCompleto != null))
      {
        hashcode = (hashcode * 397) + NomeCompleto.GetHashCode();
      }
      if((NomeSocial != null) && __isset.nomeSocial)
      {
        hashcode = (hashcode * 397) + NomeSocial.GetHashCode();
      }
      if((NumeroProntuario != null) && __isset.numeroProntuario)
      {
        hashcode = (hashcode * 397) + NumeroProntuario.GetHashCode();
      }
      if((NumeroProntuarioCnes != null) && __isset.numeroProntuarioCnes)
      {
        hashcode = (hashcode * 397) + NumeroProntuarioCnes.GetHashCode();
      }
      hashcode = (hashcode * 397) + RacaCorId.GetHashCode();
      hashcode = (hashcode * 397) + Sexo.GetHashCode();
      if((TelefoneCelular != null) && __isset.telefoneCelular)
      {
        hashcode = (hashcode * 397) + TelefoneCelular.GetHashCode();
      }
      if((TelefoneContato != null) && __isset.telefoneContato)
      {
        hashcode = (hashcode * 397) + TelefoneContato.GetHashCode();
      }
      if((TelefoneResidencial != null) && __isset.telefoneResidencial)
      {
        hashcode = (hashcode * 397) + TelefoneResidencial.GetHashCode();
      }
      if(__isset.tipoSanguineo)
      {
        hashcode = (hashcode * 397) + TipoSanguineo.GetHashCode();
      }
      if((CboNumero != null) && __isset.cboNumero)
      {
        hashcode = (hashcode * 397) + CboNumero.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp8 = new StringBuilder("CidadaoTransportThrift(");
    tmp8.Append($", NaoPossuiCns: ");
    NaoPossuiCns.ToString();
    if((Cns != null))
    {
      tmp8.Append($", Cns: {Cns.ToString()}");      
    }
    if((Cpf != null) && __isset.@cpf)
    {
      tmp8.Append($", Cpf: {Cpf.ToString()}");      
    }
    tmp8.Append($", DataNascimento: {DataNascimento.ToString()}");    
    tmp8.Append($", DesconheceNomeMae: {DesconheceNomeMae.ToString()}");    
    if((NomeMae != null) && __isset.nomeMae)
    {
      tmp8.Append($", NomeMae: {NomeMae.ToString()}");      
    }
    if((Email != null) && __isset.@email)
    {
      tmp8.Append($", Email: {Email.ToString()}");      
    }
    if((Endereco != null) && __isset.@endereco)
    {
      tmp8.Append($", Endereco: {Endereco.ToString()}");      
    }
    if(__isset.escolaridadeId)
    {
      tmp8.Append($", EscolaridadeId: {EscolaridadeId.ToString()}");      
    }
    if(__isset.estadoCivilId)
    {
      tmp8.Append($", EstadoCivilId: {EstadoCivilId.ToString()}");      
    }
    tmp8.Append($", Estrangeiro: {    Estrangeiro.ToString()}");
    if(__isset.etniaId)
    {
      tmp8.Append($", EtniaId: {      EtniaId.ToString()}");
    }
    if(__isset.@faleceu)
    {
      tmp8.Append($", Faleceu: {      Faleceu.ToString()}");
    }
    if((MunicipioNascimentoCep != null))
    {
      tmp8.Append($", MunicipioNascimentoCep: {      MunicipioNascimentoCep.ToString()}");
    }
    if((MunicipioNascimentoDne != null))
    {
      tmp8.Append($", MunicipioNascimentoDne: {      MunicipioNascimentoDne.ToString()}");
    }
    if((MunicipioNascimentoIbge != null) && __isset.municipioNascimentoIbge)
    {
      tmp8.Append($", MunicipioNascimentoIbge: {      MunicipioNascimentoIbge.ToString()}");
    }
    if((NisPisPasep != null) && __isset.nisPisPasep)
    {
      tmp8.Append($", NisPisPasep: {      NisPisPasep.ToString()}");
    }
    if((NomeCompleto != null))
    {
      tmp8.Append($", NomeCompleto: {      NomeCompleto.ToString()}");
    }
    if((NomeSocial != null) && __isset.nomeSocial)
    {
      tmp8.Append($", NomeSocial: {      NomeSocial.ToString()}");
    }
    if((NumeroProntuario != null) && __isset.numeroProntuario)
    {
      tmp8.Append($", NumeroProntuario: {      NumeroProntuario.ToString()}");
    }
    if((NumeroProntuarioCnes != null) && __isset.numeroProntuarioCnes)
    {
      tmp8.Append($", NumeroProntuarioCnes: {      NumeroProntuarioCnes.ToString()}");
    }
    tmp8.Append($", RacaCorId: {    RacaCorId.ToString()}");
    tmp8.Append($", Sexo: {    Sexo.ToString()}");
    if((TelefoneCelular != null) && __isset.telefoneCelular)
    {
      tmp8.Append($", TelefoneCelular: {      TelefoneCelular.ToString()}");
    }
    if((TelefoneContato != null) && __isset.telefoneContato)
    {
      tmp8.Append($", TelefoneContato: {      TelefoneContato.ToString()}");
    }
    if((TelefoneResidencial != null) && __isset.telefoneResidencial)
    {
      tmp8.Append($", TelefoneResidencial: {      TelefoneResidencial.ToString()}");
    }
    if(__isset.tipoSanguineo)
    {
      tmp8.Append($", TipoSanguineo: {      TipoSanguineo.ToString()}");
    }
    if((CboNumero != null) && __isset.cboNumero)
    {
      tmp8.Append($", CboNumero: {      CboNumero.ToString()}");
    }
    tmp8.Append(')');
    return tmp8.ToString();
  }
}

