/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class CadastroIndividualThrift : TBase
{
  private CondicoesDeSaudeThrift _condicoesDeSaude;
  private EmSituacaoDeRuaThrift _emSituacaoDeRua;
  private bool _fichaAtualizada;
  private IdentificacaoUsuarioCidadaoThrift _identificacaoUsuarioCidadao;
  private InformacoesSocioDemograficasThrift _informacoesSocioDemograficas;
  private bool _statusTermoRecusaCadastroIndividualAtencaoBasica;
  private int _tpCdsOrigem;
  private string _uuidFichaOriginadora;
  private string _uuidCidadao;
  private SaidaCidadaoCadastroThrift _saidaCidadaoCadastro;
  private UnicaLotacaoHeaderThrift _headerTransport;
  private bool _statusCadastroIndividualInativo;
  private bool _statusGeradoAutomaticamente;
  private InformacoesSocioEconomicasThrift _informacoesSocioEconomicas;

  public CondicoesDeSaudeThrift CondicoesDeSaude
  {
    get
    {
      return _condicoesDeSaude;
    }
    set
    {
      __isset.condicoesDeSaude = true;
      this._condicoesDeSaude = value;
    }
  }

  public EmSituacaoDeRuaThrift EmSituacaoDeRua
  {
    get
    {
      return _emSituacaoDeRua;
    }
    set
    {
      __isset.emSituacaoDeRua = true;
      this._emSituacaoDeRua = value;
    }
  }

  public bool FichaAtualizada
  {
    get
    {
      return _fichaAtualizada;
    }
    set
    {
      __isset.fichaAtualizada = true;
      this._fichaAtualizada = value;
    }
  }

  public IdentificacaoUsuarioCidadaoThrift IdentificacaoUsuarioCidadao
  {
    get
    {
      return _identificacaoUsuarioCidadao;
    }
    set
    {
      __isset.identificacaoUsuarioCidadao = true;
      this._identificacaoUsuarioCidadao = value;
    }
  }

  public InformacoesSocioDemograficasThrift InformacoesSocioDemograficas
  {
    get
    {
      return _informacoesSocioDemograficas;
    }
    set
    {
      __isset.informacoesSocioDemograficas = true;
      this._informacoesSocioDemograficas = value;
    }
  }

  public bool StatusTermoRecusaCadastroIndividualAtencaoBasica
  {
    get
    {
      return _statusTermoRecusaCadastroIndividualAtencaoBasica;
    }
    set
    {
      __isset.statusTermoRecusaCadastroIndividualAtencaoBasica = true;
      this._statusTermoRecusaCadastroIndividualAtencaoBasica = value;
    }
  }

  public int TpCdsOrigem
  {
    get
    {
      return _tpCdsOrigem;
    }
    set
    {
      __isset.tpCdsOrigem = true;
      this._tpCdsOrigem = value;
    }
  }

  public string Uuid { get; set; }

  public string UuidFichaOriginadora
  {
    get
    {
      return _uuidFichaOriginadora;
    }
    set
    {
      __isset.uuidFichaOriginadora = true;
      this._uuidFichaOriginadora = value;
    }
  }

  public string UuidCidadao
  {
    get
    {
      return _uuidCidadao;
    }
    set
    {
      __isset.uuidCidadao = true;
      this._uuidCidadao = value;
    }
  }

  public SaidaCidadaoCadastroThrift SaidaCidadaoCadastro
  {
    get
    {
      return _saidaCidadaoCadastro;
    }
    set
    {
      __isset.saidaCidadaoCadastro = true;
      this._saidaCidadaoCadastro = value;
    }
  }

  public UnicaLotacaoHeaderThrift HeaderTransport
  {
    get
    {
      return _headerTransport;
    }
    set
    {
      __isset.headerTransport = true;
      this._headerTransport = value;
    }
  }

  public bool StatusCadastroIndividualInativo
  {
    get
    {
      return _statusCadastroIndividualInativo;
    }
    set
    {
      __isset.statusCadastroIndividualInativo = true;
      this._statusCadastroIndividualInativo = value;
    }
  }

  public bool StatusGeradoAutomaticamente
  {
    get
    {
      return _statusGeradoAutomaticamente;
    }
    set
    {
      __isset.statusGeradoAutomaticamente = true;
      this._statusGeradoAutomaticamente = value;
    }
  }

  public InformacoesSocioEconomicasThrift InformacoesSocioEconomicas
  {
    get
    {
      return _informacoesSocioEconomicas;
    }
    set
    {
      __isset.informacoesSocioEconomicas = true;
      this._informacoesSocioEconomicas = value;
    }
  }


  public CadastroIndividual __isset;
  public struct CadastroIndividual
    {
    public bool condicoesDeSaude;
    public bool emSituacaoDeRua;
    public bool fichaAtualizada;
    public bool identificacaoUsuarioCidadao;
    public bool informacoesSocioDemograficas;
    public bool statusTermoRecusaCadastroIndividualAtencaoBasica;
    public bool tpCdsOrigem;
    public bool uuidFichaOriginadora;
    public bool uuidCidadao;
    public bool saidaCidadaoCadastro;
    public bool headerTransport;
    public bool statusCadastroIndividualInativo;
    public bool statusGeradoAutomaticamente;
    public bool informacoesSocioEconomicas;
  }

  public CadastroIndividualThrift()
  {
  }

  public CadastroIndividualThrift(string @uuid) : this()
  {
    this.Uuid = @uuid;
  }

  public CadastroIndividualThrift DeepCopy()
  {
    var tmp58 = new CadastroIndividualThrift();
    if((CondicoesDeSaude != null) && __isset.condicoesDeSaude)
    {
      tmp58.CondicoesDeSaude = (CondicoesDeSaudeThrift)this.CondicoesDeSaude.DeepCopy();
    }
    tmp58.__isset.condicoesDeSaude = this.__isset.condicoesDeSaude;
    if((EmSituacaoDeRua != null) && __isset.emSituacaoDeRua)
    {
      tmp58.EmSituacaoDeRua = (EmSituacaoDeRuaThrift)this.EmSituacaoDeRua.DeepCopy();
    }
    tmp58.__isset.emSituacaoDeRua = this.__isset.emSituacaoDeRua;
    if(__isset.fichaAtualizada)
    {
      tmp58.FichaAtualizada = this.FichaAtualizada;
    }
    tmp58.__isset.fichaAtualizada = this.__isset.fichaAtualizada;
    if((IdentificacaoUsuarioCidadao != null) && __isset.identificacaoUsuarioCidadao)
    {
      tmp58.IdentificacaoUsuarioCidadao = (IdentificacaoUsuarioCidadaoThrift)this.IdentificacaoUsuarioCidadao.DeepCopy();
    }
    tmp58.__isset.identificacaoUsuarioCidadao = this.__isset.identificacaoUsuarioCidadao;
    if((InformacoesSocioDemograficas != null) && __isset.informacoesSocioDemograficas)
    {
      tmp58.InformacoesSocioDemograficas = (InformacoesSocioDemograficasThrift)this.InformacoesSocioDemograficas.DeepCopy();
    }
    tmp58.__isset.informacoesSocioDemograficas = this.__isset.informacoesSocioDemograficas;
    if(__isset.statusTermoRecusaCadastroIndividualAtencaoBasica)
    {
      tmp58.StatusTermoRecusaCadastroIndividualAtencaoBasica = this.StatusTermoRecusaCadastroIndividualAtencaoBasica;
    }
    tmp58.__isset.statusTermoRecusaCadastroIndividualAtencaoBasica = this.__isset.statusTermoRecusaCadastroIndividualAtencaoBasica;
    if(__isset.tpCdsOrigem)
    {
      tmp58.TpCdsOrigem = this.TpCdsOrigem;
    }
    tmp58.__isset.tpCdsOrigem = this.__isset.tpCdsOrigem;
    if((Uuid != null))
    {
      tmp58.Uuid = this.Uuid;
    }
    if((UuidFichaOriginadora != null) && __isset.uuidFichaOriginadora)
    {
      tmp58.UuidFichaOriginadora = this.UuidFichaOriginadora;
    }
    tmp58.__isset.uuidFichaOriginadora = this.__isset.uuidFichaOriginadora;
    if((UuidCidadao != null) && __isset.uuidCidadao)
    {
      tmp58.UuidCidadao = this.UuidCidadao;
    }
    tmp58.__isset.uuidCidadao = this.__isset.uuidCidadao;
    if((SaidaCidadaoCadastro != null) && __isset.saidaCidadaoCadastro)
    {
      tmp58.SaidaCidadaoCadastro = (SaidaCidadaoCadastroThrift)this.SaidaCidadaoCadastro.DeepCopy();
    }
    tmp58.__isset.saidaCidadaoCadastro = this.__isset.saidaCidadaoCadastro;
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp58.HeaderTransport = (UnicaLotacaoHeaderThrift)this.HeaderTransport.DeepCopy();
    }
    tmp58.__isset.headerTransport = this.__isset.headerTransport;
    if(__isset.statusCadastroIndividualInativo)
    {
      tmp58.StatusCadastroIndividualInativo = this.StatusCadastroIndividualInativo;
    }
    tmp58.__isset.statusCadastroIndividualInativo = this.__isset.statusCadastroIndividualInativo;
    if(__isset.statusGeradoAutomaticamente)
    {
      tmp58.StatusGeradoAutomaticamente = this.StatusGeradoAutomaticamente;
    }
    tmp58.__isset.statusGeradoAutomaticamente = this.__isset.statusGeradoAutomaticamente;
    if((InformacoesSocioEconomicas != null) && __isset.informacoesSocioEconomicas)
    {
      tmp58.InformacoesSocioEconomicas = (InformacoesSocioEconomicasThrift)this.InformacoesSocioEconomicas.DeepCopy();
    }
    tmp58.__isset.informacoesSocioEconomicas = this.__isset.informacoesSocioEconomicas;
    return tmp58;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_uuid = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              CondicoesDeSaude = new CondicoesDeSaudeThrift();
              await CondicoesDeSaude.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Struct)
            {
              EmSituacaoDeRua = new EmSituacaoDeRuaThrift();
              await EmSituacaoDeRua.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.Bool)
            {
              FichaAtualizada = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.Struct)
            {
              IdentificacaoUsuarioCidadao = new IdentificacaoUsuarioCidadaoThrift();
              await IdentificacaoUsuarioCidadao.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.Struct)
            {
              InformacoesSocioDemograficas = new InformacoesSocioDemograficasThrift();
              await InformacoesSocioDemograficas.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.Bool)
            {
              StatusTermoRecusaCadastroIndividualAtencaoBasica = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.I32)
            {
              TpCdsOrigem = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.String)
            {
              Uuid = await iprot.ReadStringAsync(cancellationToken);
              isset_uuid = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.String)
            {
              UuidFichaOriginadora = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.String)
            {
              UuidCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.Struct)
            {
              SaidaCidadaoCadastro = new SaidaCidadaoCadastroThrift();
              await SaidaCidadaoCadastro.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.Struct)
            {
              HeaderTransport = new UnicaLotacaoHeaderThrift();
              await HeaderTransport.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 14:
            if (field.Type == TType.Bool)
            {
              StatusCadastroIndividualInativo = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 15:
            if (field.Type == TType.Bool)
            {
              StatusGeradoAutomaticamente = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 16:
            if (field.Type == TType.Struct)
            {
              InformacoesSocioEconomicas = new InformacoesSocioEconomicasThrift();
              await InformacoesSocioEconomicas.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_uuid)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp59 = new TStruct("CadastroIndividualThrift");
      await oprot.WriteStructBeginAsync(tmp59, cancellationToken);
      var tmp60 = new TField();
      if((CondicoesDeSaude != null) && __isset.condicoesDeSaude)
      {
        tmp60.Name = "condicoesDeSaude";
        tmp60.Type = TType.Struct;
        tmp60.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await CondicoesDeSaude.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((EmSituacaoDeRua != null) && __isset.emSituacaoDeRua)
      {
        tmp60.Name = "emSituacaoDeRua";
        tmp60.Type = TType.Struct;
        tmp60.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await EmSituacaoDeRua.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.fichaAtualizada)
      {
        tmp60.Name = "fichaAtualizada";
        tmp60.Type = TType.Bool;
        tmp60.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteBoolAsync(FichaAtualizada, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((IdentificacaoUsuarioCidadao != null) && __isset.identificacaoUsuarioCidadao)
      {
        tmp60.Name = "identificacaoUsuarioCidadao";
        tmp60.Type = TType.Struct;
        tmp60.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await IdentificacaoUsuarioCidadao.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((InformacoesSocioDemograficas != null) && __isset.informacoesSocioDemograficas)
      {
        tmp60.Name = "informacoesSocioDemograficas";
        tmp60.Type = TType.Struct;
        tmp60.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await InformacoesSocioDemograficas.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusTermoRecusaCadastroIndividualAtencaoBasica)
      {
        tmp60.Name = "statusTermoRecusaCadastroIndividualAtencaoBasica";
        tmp60.Type = TType.Bool;
        tmp60.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteBoolAsync(StatusTermoRecusaCadastroIndividualAtencaoBasica, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.tpCdsOrigem)
      {
        tmp60.Name = "tpCdsOrigem";
        tmp60.Type = TType.I32;
        tmp60.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteI32Async(TpCdsOrigem, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Uuid != null))
      {
        tmp60.Name = "uuid";
        tmp60.Type = TType.String;
        tmp60.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteStringAsync(Uuid, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((UuidFichaOriginadora != null) && __isset.uuidFichaOriginadora)
      {
        tmp60.Name = "uuidFichaOriginadora";
        tmp60.Type = TType.String;
        tmp60.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteStringAsync(UuidFichaOriginadora, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((UuidCidadao != null) && __isset.uuidCidadao)
      {
        tmp60.Name = "uuidCidadao";
        tmp60.Type = TType.String;
        tmp60.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteStringAsync(UuidCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((SaidaCidadaoCadastro != null) && __isset.saidaCidadaoCadastro)
      {
        tmp60.Name = "saidaCidadaoCadastro";
        tmp60.Type = TType.Struct;
        tmp60.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await SaidaCidadaoCadastro.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        tmp60.Name = "headerTransport";
        tmp60.Type = TType.Struct;
        tmp60.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await HeaderTransport.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusCadastroIndividualInativo)
      {
        tmp60.Name = "statusCadastroIndividualInativo";
        tmp60.Type = TType.Bool;
        tmp60.ID = 14;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteBoolAsync(StatusCadastroIndividualInativo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusGeradoAutomaticamente)
      {
        tmp60.Name = "statusGeradoAutomaticamente";
        tmp60.Type = TType.Bool;
        tmp60.ID = 15;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await oprot.WriteBoolAsync(StatusGeradoAutomaticamente, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((InformacoesSocioEconomicas != null) && __isset.informacoesSocioEconomicas)
      {
        tmp60.Name = "informacoesSocioEconomicas";
        tmp60.Type = TType.Struct;
        tmp60.ID = 16;
        await oprot.WriteFieldBeginAsync(tmp60, cancellationToken);
        await InformacoesSocioEconomicas.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is CadastroIndividualThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.condicoesDeSaude == other.__isset.condicoesDeSaude) && ((!__isset.condicoesDeSaude) || (global::System.Object.Equals(CondicoesDeSaude, other.CondicoesDeSaude))))
      && ((__isset.emSituacaoDeRua == other.__isset.emSituacaoDeRua) && ((!__isset.emSituacaoDeRua) || (global::System.Object.Equals(EmSituacaoDeRua, other.EmSituacaoDeRua))))
      && ((__isset.fichaAtualizada == other.__isset.fichaAtualizada) && ((!__isset.fichaAtualizada) || (global::System.Object.Equals(FichaAtualizada, other.FichaAtualizada))))
      && ((__isset.identificacaoUsuarioCidadao == other.__isset.identificacaoUsuarioCidadao) && ((!__isset.identificacaoUsuarioCidadao) || (global::System.Object.Equals(IdentificacaoUsuarioCidadao, other.IdentificacaoUsuarioCidadao))))
      && ((__isset.informacoesSocioDemograficas == other.__isset.informacoesSocioDemograficas) && ((!__isset.informacoesSocioDemograficas) || (global::System.Object.Equals(InformacoesSocioDemograficas, other.InformacoesSocioDemograficas))))
      && ((__isset.statusTermoRecusaCadastroIndividualAtencaoBasica == other.__isset.statusTermoRecusaCadastroIndividualAtencaoBasica) && ((!__isset.statusTermoRecusaCadastroIndividualAtencaoBasica) || (global::System.Object.Equals(StatusTermoRecusaCadastroIndividualAtencaoBasica, other.StatusTermoRecusaCadastroIndividualAtencaoBasica))))
      && ((__isset.tpCdsOrigem == other.__isset.tpCdsOrigem) && ((!__isset.tpCdsOrigem) || (global::System.Object.Equals(TpCdsOrigem, other.TpCdsOrigem))))
      && global::System.Object.Equals(Uuid, other.Uuid)
      && ((__isset.uuidFichaOriginadora == other.__isset.uuidFichaOriginadora) && ((!__isset.uuidFichaOriginadora) || (global::System.Object.Equals(UuidFichaOriginadora, other.UuidFichaOriginadora))))
      && ((__isset.uuidCidadao == other.__isset.uuidCidadao) && ((!__isset.uuidCidadao) || (global::System.Object.Equals(UuidCidadao, other.UuidCidadao))))
      && ((__isset.saidaCidadaoCadastro == other.__isset.saidaCidadaoCadastro) && ((!__isset.saidaCidadaoCadastro) || (global::System.Object.Equals(SaidaCidadaoCadastro, other.SaidaCidadaoCadastro))))
      && ((__isset.headerTransport == other.__isset.headerTransport) && ((!__isset.headerTransport) || (global::System.Object.Equals(HeaderTransport, other.HeaderTransport))))
      && ((__isset.statusCadastroIndividualInativo == other.__isset.statusCadastroIndividualInativo) && ((!__isset.statusCadastroIndividualInativo) || (global::System.Object.Equals(StatusCadastroIndividualInativo, other.StatusCadastroIndividualInativo))))
      && ((__isset.statusGeradoAutomaticamente == other.__isset.statusGeradoAutomaticamente) && ((!__isset.statusGeradoAutomaticamente) || (global::System.Object.Equals(StatusGeradoAutomaticamente, other.StatusGeradoAutomaticamente))))
      && ((__isset.informacoesSocioEconomicas == other.__isset.informacoesSocioEconomicas) && ((!__isset.informacoesSocioEconomicas) || (global::System.Object.Equals(InformacoesSocioEconomicas, other.InformacoesSocioEconomicas))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((CondicoesDeSaude != null) && __isset.condicoesDeSaude)
      {
        hashcode = (hashcode * 397) + CondicoesDeSaude.GetHashCode();
      }
      if((EmSituacaoDeRua != null) && __isset.emSituacaoDeRua)
      {
        hashcode = (hashcode * 397) + EmSituacaoDeRua.GetHashCode();
      }
      if(__isset.fichaAtualizada)
      {
        hashcode = (hashcode * 397) + FichaAtualizada.GetHashCode();
      }
      if((IdentificacaoUsuarioCidadao != null) && __isset.identificacaoUsuarioCidadao)
      {
        hashcode = (hashcode * 397) + IdentificacaoUsuarioCidadao.GetHashCode();
      }
      if((InformacoesSocioDemograficas != null) && __isset.informacoesSocioDemograficas)
      {
        hashcode = (hashcode * 397) + InformacoesSocioDemograficas.GetHashCode();
      }
      if(__isset.statusTermoRecusaCadastroIndividualAtencaoBasica)
      {
        hashcode = (hashcode * 397) + StatusTermoRecusaCadastroIndividualAtencaoBasica.GetHashCode();
      }
      if(__isset.tpCdsOrigem)
      {
        hashcode = (hashcode * 397) + TpCdsOrigem.GetHashCode();
      }
      if((Uuid != null))
      {
        hashcode = (hashcode * 397) + Uuid.GetHashCode();
      }
      if((UuidFichaOriginadora != null) && __isset.uuidFichaOriginadora)
      {
        hashcode = (hashcode * 397) + UuidFichaOriginadora.GetHashCode();
      }
      if((UuidCidadao != null) && __isset.uuidCidadao)
      {
        hashcode = (hashcode * 397) + UuidCidadao.GetHashCode();
      }
      if((SaidaCidadaoCadastro != null) && __isset.saidaCidadaoCadastro)
      {
        hashcode = (hashcode * 397) + SaidaCidadaoCadastro.GetHashCode();
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        hashcode = (hashcode * 397) + HeaderTransport.GetHashCode();
      }
      if(__isset.statusCadastroIndividualInativo)
      {
        hashcode = (hashcode * 397) + StatusCadastroIndividualInativo.GetHashCode();
      }
      if(__isset.statusGeradoAutomaticamente)
      {
        hashcode = (hashcode * 397) + StatusGeradoAutomaticamente.GetHashCode();
      }
      if((InformacoesSocioEconomicas != null) && __isset.informacoesSocioEconomicas)
      {
        hashcode = (hashcode * 397) + InformacoesSocioEconomicas.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp61 = new StringBuilder("CadastroIndividualThrift(");
    int tmp62 = 0;
    if((CondicoesDeSaude != null) && __isset.condicoesDeSaude)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("CondicoesDeSaude: ");
      CondicoesDeSaude.ToString(tmp61);
    }
    if((EmSituacaoDeRua != null) && __isset.emSituacaoDeRua)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("EmSituacaoDeRua: ");
      EmSituacaoDeRua.ToString(tmp61);
    }
    if(__isset.fichaAtualizada)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("FichaAtualizada: ");
      FichaAtualizada.ToString(tmp61);
    }
    if((IdentificacaoUsuarioCidadao != null) && __isset.identificacaoUsuarioCidadao)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("IdentificacaoUsuarioCidadao: ");
      IdentificacaoUsuarioCidadao.ToString(tmp61);
    }
    if((InformacoesSocioDemograficas != null) && __isset.informacoesSocioDemograficas)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("InformacoesSocioDemograficas: ");
      InformacoesSocioDemograficas.ToString(tmp61);
    }
    if(__isset.statusTermoRecusaCadastroIndividualAtencaoBasica)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("StatusTermoRecusaCadastroIndividualAtencaoBasica: ");
      StatusTermoRecusaCadastroIndividualAtencaoBasica.ToString(tmp61);
    }
    if(__isset.tpCdsOrigem)
    {
      if(0 < tmp62++) { tmp61.Append(", "); }
      tmp61.Append("TpCdsOrigem: ");
      TpCdsOrigem.ToString(tmp61);
    }
    if((Uuid != null))
    {
      if(0 < tmp62) { tmp61.Append(", "); }
      tmp61.Append("Uuid: ");
      Uuid.ToString(tmp61);
    }
    if((UuidFichaOriginadora != null) && __isset.uuidFichaOriginadora)
    {
      tmp61.Append(", UuidFichaOriginadora: ");
      UuidFichaOriginadora.ToString(tmp61);
    }
    if((UuidCidadao != null) && __isset.uuidCidadao)
    {
      tmp61.Append(", UuidCidadao: ");
      UuidCidadao.ToString(tmp61);
    }
    if((SaidaCidadaoCadastro != null) && __isset.saidaCidadaoCadastro)
    {
      tmp61.Append(", SaidaCidadaoCadastro: ");
      SaidaCidadaoCadastro.ToString(tmp61);
    }
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp61.Append(", HeaderTransport: ");
      HeaderTransport.ToString(tmp61);
    }
    if(__isset.statusCadastroIndividualInativo)
    {
      tmp61.Append(", StatusCadastroIndividualInativo: ");
      StatusCadastroIndividualInativo.ToString(tmp61);
    }
    if(__isset.statusGeradoAutomaticamente)
    {
      tmp61.Append(", StatusGeradoAutomaticamente: ");
      StatusGeradoAutomaticamente.ToString(tmp61);
    }
    if((InformacoesSocioEconomicas != null) && __isset.informacoesSocioEconomicas)
    {
      tmp61.Append(", InformacoesSocioEconomicas: ");
      InformacoesSocioEconomicas.ToString(tmp61);
    }
    tmp61.Append(')');
    return tmp61.ToString();
  }
}

