/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class IdentificacaoUsuarioCidadaoThrift : TBase
{
  private string _nomeSocial;
  private string _codigoIbgeMunicipioNascimento;
  private long _dataNascimentoCidadao;
  private bool _desconheceNomeMae;
  private string _emailCidadao;
  private long _nacionalidadeCidadao;
  private string _nomeCidadao;
  private string _nomeMaeCidadao;
  private string _cnsCidadao;
  private string _cnsResponsavelFamiliar;
  private string _telefoneCelular;
  private string _numeroNisPisPasep;
  private long _paisNascimento;
  private long _racaCorCidadao;
  private long _sexoCidadao;
  private bool _statusEhResponsavel;
  private long _etnia;
  private string _nomePaiCidadao;
  private bool _desconheceNomePai;
  private long _dtNaturalizacao;
  private string _portariaNaturalizacao;
  private long _dtEntradaBrasil;
  private string _microArea;
  private bool _stForaArea;
  private string _cpfCidadao;
  private string _cpfResponsavelFamiliar;

  public string NomeSocial
  {
    get
    {
      return _nomeSocial;
    }
    set
    {
      __isset.nomeSocial = true;
      this._nomeSocial = value;
    }
  }

  public string CodigoIbgeMunicipioNascimento
  {
    get
    {
      return _codigoIbgeMunicipioNascimento;
    }
    set
    {
      __isset.codigoIbgeMunicipioNascimento = true;
      this._codigoIbgeMunicipioNascimento = value;
    }
  }

  public long DataNascimentoCidadao
  {
    get
    {
      return _dataNascimentoCidadao;
    }
    set
    {
      __isset.dataNascimentoCidadao = true;
      this._dataNascimentoCidadao = value;
    }
  }

  public bool DesconheceNomeMae
  {
    get
    {
      return _desconheceNomeMae;
    }
    set
    {
      __isset.desconheceNomeMae = true;
      this._desconheceNomeMae = value;
    }
  }

  public string EmailCidadao
  {
    get
    {
      return _emailCidadao;
    }
    set
    {
      __isset.emailCidadao = true;
      this._emailCidadao = value;
    }
  }

  public long NacionalidadeCidadao
  {
    get
    {
      return _nacionalidadeCidadao;
    }
    set
    {
      __isset.nacionalidadeCidadao = true;
      this._nacionalidadeCidadao = value;
    }
  }

  public string NomeCidadao
  {
    get
    {
      return _nomeCidadao;
    }
    set
    {
      __isset.nomeCidadao = true;
      this._nomeCidadao = value;
    }
  }

  public string NomeMaeCidadao
  {
    get
    {
      return _nomeMaeCidadao;
    }
    set
    {
      __isset.nomeMaeCidadao = true;
      this._nomeMaeCidadao = value;
    }
  }

  public string CnsCidadao
  {
    get
    {
      return _cnsCidadao;
    }
    set
    {
      __isset.cnsCidadao = true;
      this._cnsCidadao = value;
    }
  }

  public string CnsResponsavelFamiliar
  {
    get
    {
      return _cnsResponsavelFamiliar;
    }
    set
    {
      __isset.cnsResponsavelFamiliar = true;
      this._cnsResponsavelFamiliar = value;
    }
  }

  public string TelefoneCelular
  {
    get
    {
      return _telefoneCelular;
    }
    set
    {
      __isset.telefoneCelular = true;
      this._telefoneCelular = value;
    }
  }

  public string NumeroNisPisPasep
  {
    get
    {
      return _numeroNisPisPasep;
    }
    set
    {
      __isset.numeroNisPisPasep = true;
      this._numeroNisPisPasep = value;
    }
  }

  public long PaisNascimento
  {
    get
    {
      return _paisNascimento;
    }
    set
    {
      __isset.paisNascimento = true;
      this._paisNascimento = value;
    }
  }

  public long RacaCorCidadao
  {
    get
    {
      return _racaCorCidadao;
    }
    set
    {
      __isset.racaCorCidadao = true;
      this._racaCorCidadao = value;
    }
  }

  public long SexoCidadao
  {
    get
    {
      return _sexoCidadao;
    }
    set
    {
      __isset.sexoCidadao = true;
      this._sexoCidadao = value;
    }
  }

  public bool StatusEhResponsavel
  {
    get
    {
      return _statusEhResponsavel;
    }
    set
    {
      __isset.statusEhResponsavel = true;
      this._statusEhResponsavel = value;
    }
  }

  public long Etnia
  {
    get
    {
      return _etnia;
    }
    set
    {
      __isset.@etnia = true;
      this._etnia = value;
    }
  }

  public string NomePaiCidadao
  {
    get
    {
      return _nomePaiCidadao;
    }
    set
    {
      __isset.nomePaiCidadao = true;
      this._nomePaiCidadao = value;
    }
  }

  public bool DesconheceNomePai
  {
    get
    {
      return _desconheceNomePai;
    }
    set
    {
      __isset.desconheceNomePai = true;
      this._desconheceNomePai = value;
    }
  }

  public long DtNaturalizacao
  {
    get
    {
      return _dtNaturalizacao;
    }
    set
    {
      __isset.dtNaturalizacao = true;
      this._dtNaturalizacao = value;
    }
  }

  public string PortariaNaturalizacao
  {
    get
    {
      return _portariaNaturalizacao;
    }
    set
    {
      __isset.portariaNaturalizacao = true;
      this._portariaNaturalizacao = value;
    }
  }

  public long DtEntradaBrasil
  {
    get
    {
      return _dtEntradaBrasil;
    }
    set
    {
      __isset.dtEntradaBrasil = true;
      this._dtEntradaBrasil = value;
    }
  }

  public string MicroArea
  {
    get
    {
      return _microArea;
    }
    set
    {
      __isset.microArea = true;
      this._microArea = value;
    }
  }

  public bool StForaArea
  {
    get
    {
      return _stForaArea;
    }
    set
    {
      __isset.stForaArea = true;
      this._stForaArea = value;
    }
  }

  public string CpfCidadao
  {
    get
    {
      return _cpfCidadao;
    }
    set
    {
      __isset.cpfCidadao = true;
      this._cpfCidadao = value;
    }
  }

  public string CpfResponsavelFamiliar
  {
    get
    {
      return _cpfResponsavelFamiliar;
    }
    set
    {
      __isset.cpfResponsavelFamiliar = true;
      this._cpfResponsavelFamiliar = value;
    }
  }


  public IdentificacaoUsuarioCidadao __isset;
  public struct IdentificacaoUsuarioCidadao
    {
    public bool nomeSocial;
    public bool codigoIbgeMunicipioNascimento;
    public bool dataNascimentoCidadao;
    public bool desconheceNomeMae;
    public bool emailCidadao;
    public bool nacionalidadeCidadao;
    public bool nomeCidadao;
    public bool nomeMaeCidadao;
    public bool cnsCidadao;
    public bool cnsResponsavelFamiliar;
    public bool telefoneCelular;
    public bool numeroNisPisPasep;
    public bool paisNascimento;
    public bool racaCorCidadao;
    public bool sexoCidadao;
    public bool statusEhResponsavel;
    public bool @etnia;
    public bool nomePaiCidadao;
    public bool desconheceNomePai;
    public bool dtNaturalizacao;
    public bool portariaNaturalizacao;
    public bool dtEntradaBrasil;
    public bool microArea;
    public bool stForaArea;
    public bool cpfCidadao;
    public bool cpfResponsavelFamiliar;
  }

  public IdentificacaoUsuarioCidadaoThrift()
  {
  }

  public IdentificacaoUsuarioCidadaoThrift DeepCopy()
  {
    var tmp30 = new IdentificacaoUsuarioCidadaoThrift();
    if((NomeSocial != null) && __isset.nomeSocial)
    {
      tmp30.NomeSocial = this.NomeSocial;
    }
    tmp30.__isset.nomeSocial = this.__isset.nomeSocial;
    if((CodigoIbgeMunicipioNascimento != null) && __isset.codigoIbgeMunicipioNascimento)
    {
      tmp30.CodigoIbgeMunicipioNascimento = this.CodigoIbgeMunicipioNascimento;
    }
    tmp30.__isset.codigoIbgeMunicipioNascimento = this.__isset.codigoIbgeMunicipioNascimento;
    if(__isset.dataNascimentoCidadao)
    {
      tmp30.DataNascimentoCidadao = this.DataNascimentoCidadao;
    }
    tmp30.__isset.dataNascimentoCidadao = this.__isset.dataNascimentoCidadao;
    if(__isset.desconheceNomeMae)
    {
      tmp30.DesconheceNomeMae = this.DesconheceNomeMae;
    }
    tmp30.__isset.desconheceNomeMae = this.__isset.desconheceNomeMae;
    if((EmailCidadao != null) && __isset.emailCidadao)
    {
      tmp30.EmailCidadao = this.EmailCidadao;
    }
    tmp30.__isset.emailCidadao = this.__isset.emailCidadao;
    if(__isset.nacionalidadeCidadao)
    {
      tmp30.NacionalidadeCidadao = this.NacionalidadeCidadao;
    }
    tmp30.__isset.nacionalidadeCidadao = this.__isset.nacionalidadeCidadao;
    if((NomeCidadao != null) && __isset.nomeCidadao)
    {
      tmp30.NomeCidadao = this.NomeCidadao;
    }
    tmp30.__isset.nomeCidadao = this.__isset.nomeCidadao;
    if((NomeMaeCidadao != null) && __isset.nomeMaeCidadao)
    {
      tmp30.NomeMaeCidadao = this.NomeMaeCidadao;
    }
    tmp30.__isset.nomeMaeCidadao = this.__isset.nomeMaeCidadao;
    if((CnsCidadao != null) && __isset.cnsCidadao)
    {
      tmp30.CnsCidadao = this.CnsCidadao;
    }
    tmp30.__isset.cnsCidadao = this.__isset.cnsCidadao;
    if((CnsResponsavelFamiliar != null) && __isset.cnsResponsavelFamiliar)
    {
      tmp30.CnsResponsavelFamiliar = this.CnsResponsavelFamiliar;
    }
    tmp30.__isset.cnsResponsavelFamiliar = this.__isset.cnsResponsavelFamiliar;
    if((TelefoneCelular != null) && __isset.telefoneCelular)
    {
      tmp30.TelefoneCelular = this.TelefoneCelular;
    }
    tmp30.__isset.telefoneCelular = this.__isset.telefoneCelular;
    if((NumeroNisPisPasep != null) && __isset.numeroNisPisPasep)
    {
      tmp30.NumeroNisPisPasep = this.NumeroNisPisPasep;
    }
    tmp30.__isset.numeroNisPisPasep = this.__isset.numeroNisPisPasep;
    if(__isset.paisNascimento)
    {
      tmp30.PaisNascimento = this.PaisNascimento;
    }
    tmp30.__isset.paisNascimento = this.__isset.paisNascimento;
    if(__isset.racaCorCidadao)
    {
      tmp30.RacaCorCidadao = this.RacaCorCidadao;
    }
    tmp30.__isset.racaCorCidadao = this.__isset.racaCorCidadao;
    if(__isset.sexoCidadao)
    {
      tmp30.SexoCidadao = this.SexoCidadao;
    }
    tmp30.__isset.sexoCidadao = this.__isset.sexoCidadao;
    if(__isset.statusEhResponsavel)
    {
      tmp30.StatusEhResponsavel = this.StatusEhResponsavel;
    }
    tmp30.__isset.statusEhResponsavel = this.__isset.statusEhResponsavel;
    if(__isset.@etnia)
    {
      tmp30.Etnia = this.Etnia;
    }
    tmp30.__isset.@etnia = this.__isset.@etnia;
    if((NomePaiCidadao != null) && __isset.nomePaiCidadao)
    {
      tmp30.NomePaiCidadao = this.NomePaiCidadao;
    }
    tmp30.__isset.nomePaiCidadao = this.__isset.nomePaiCidadao;
    if(__isset.desconheceNomePai)
    {
      tmp30.DesconheceNomePai = this.DesconheceNomePai;
    }
    tmp30.__isset.desconheceNomePai = this.__isset.desconheceNomePai;
    if(__isset.dtNaturalizacao)
    {
      tmp30.DtNaturalizacao = this.DtNaturalizacao;
    }
    tmp30.__isset.dtNaturalizacao = this.__isset.dtNaturalizacao;
    if((PortariaNaturalizacao != null) && __isset.portariaNaturalizacao)
    {
      tmp30.PortariaNaturalizacao = this.PortariaNaturalizacao;
    }
    tmp30.__isset.portariaNaturalizacao = this.__isset.portariaNaturalizacao;
    if(__isset.dtEntradaBrasil)
    {
      tmp30.DtEntradaBrasil = this.DtEntradaBrasil;
    }
    tmp30.__isset.dtEntradaBrasil = this.__isset.dtEntradaBrasil;
    if((MicroArea != null) && __isset.microArea)
    {
      tmp30.MicroArea = this.MicroArea;
    }
    tmp30.__isset.microArea = this.__isset.microArea;
    if(__isset.stForaArea)
    {
      tmp30.StForaArea = this.StForaArea;
    }
    tmp30.__isset.stForaArea = this.__isset.stForaArea;
    if((CpfCidadao != null) && __isset.cpfCidadao)
    {
      tmp30.CpfCidadao = this.CpfCidadao;
    }
    tmp30.__isset.cpfCidadao = this.__isset.cpfCidadao;
    if((CpfResponsavelFamiliar != null) && __isset.cpfResponsavelFamiliar)
    {
      tmp30.CpfResponsavelFamiliar = this.CpfResponsavelFamiliar;
    }
    tmp30.__isset.cpfResponsavelFamiliar = this.__isset.cpfResponsavelFamiliar;
    return tmp30;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              NomeSocial = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              CodigoIbgeMunicipioNascimento = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.I64)
            {
              DataNascimentoCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.Bool)
            {
              DesconheceNomeMae = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.String)
            {
              EmailCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.I64)
            {
              NacionalidadeCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.String)
            {
              NomeCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.String)
            {
              NomeMaeCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.String)
            {
              CnsCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.String)
            {
              CnsResponsavelFamiliar = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.String)
            {
              TelefoneCelular = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.String)
            {
              NumeroNisPisPasep = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 14:
            if (field.Type == TType.I64)
            {
              PaisNascimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 15:
            if (field.Type == TType.I64)
            {
              RacaCorCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 16:
            if (field.Type == TType.I64)
            {
              SexoCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 17:
            if (field.Type == TType.Bool)
            {
              StatusEhResponsavel = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 18:
            if (field.Type == TType.I64)
            {
              Etnia = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 19:
            if (field.Type == TType.String)
            {
              NomePaiCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 20:
            if (field.Type == TType.Bool)
            {
              DesconheceNomePai = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 21:
            if (field.Type == TType.I64)
            {
              DtNaturalizacao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 22:
            if (field.Type == TType.String)
            {
              PortariaNaturalizacao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 23:
            if (field.Type == TType.I64)
            {
              DtEntradaBrasil = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 24:
            if (field.Type == TType.String)
            {
              MicroArea = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 25:
            if (field.Type == TType.Bool)
            {
              StForaArea = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 26:
            if (field.Type == TType.String)
            {
              CpfCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 27:
            if (field.Type == TType.String)
            {
              CpfResponsavelFamiliar = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp31 = new TStruct("IdentificacaoUsuarioCidadaoThrift");
      await oprot.WriteStructBeginAsync(tmp31, cancellationToken);
      var tmp32 = new TField();
      if((NomeSocial != null) && __isset.nomeSocial)
      {
        tmp32.Name = "nomeSocial";
        tmp32.Type = TType.String;
        tmp32.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(NomeSocial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CodigoIbgeMunicipioNascimento != null) && __isset.codigoIbgeMunicipioNascimento)
      {
        tmp32.Name = "codigoIbgeMunicipioNascimento";
        tmp32.Type = TType.String;
        tmp32.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(CodigoIbgeMunicipioNascimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataNascimentoCidadao)
      {
        tmp32.Name = "dataNascimentoCidadao";
        tmp32.Type = TType.I64;
        tmp32.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DataNascimentoCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.desconheceNomeMae)
      {
        tmp32.Name = "desconheceNomeMae";
        tmp32.Type = TType.Bool;
        tmp32.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteBoolAsync(DesconheceNomeMae, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((EmailCidadao != null) && __isset.emailCidadao)
      {
        tmp32.Name = "emailCidadao";
        tmp32.Type = TType.String;
        tmp32.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(EmailCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.nacionalidadeCidadao)
      {
        tmp32.Name = "nacionalidadeCidadao";
        tmp32.Type = TType.I64;
        tmp32.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(NacionalidadeCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeCidadao != null) && __isset.nomeCidadao)
      {
        tmp32.Name = "nomeCidadao";
        tmp32.Type = TType.String;
        tmp32.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(NomeCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeMaeCidadao != null) && __isset.nomeMaeCidadao)
      {
        tmp32.Name = "nomeMaeCidadao";
        tmp32.Type = TType.String;
        tmp32.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(NomeMaeCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CnsCidadao != null) && __isset.cnsCidadao)
      {
        tmp32.Name = "cnsCidadao";
        tmp32.Type = TType.String;
        tmp32.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(CnsCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CnsResponsavelFamiliar != null) && __isset.cnsResponsavelFamiliar)
      {
        tmp32.Name = "cnsResponsavelFamiliar";
        tmp32.Type = TType.String;
        tmp32.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(CnsResponsavelFamiliar, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TelefoneCelular != null) && __isset.telefoneCelular)
      {
        tmp32.Name = "telefoneCelular";
        tmp32.Type = TType.String;
        tmp32.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(TelefoneCelular, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NumeroNisPisPasep != null) && __isset.numeroNisPisPasep)
      {
        tmp32.Name = "numeroNisPisPasep";
        tmp32.Type = TType.String;
        tmp32.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(NumeroNisPisPasep, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.paisNascimento)
      {
        tmp32.Name = "paisNascimento";
        tmp32.Type = TType.I64;
        tmp32.ID = 14;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(PaisNascimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.racaCorCidadao)
      {
        tmp32.Name = "racaCorCidadao";
        tmp32.Type = TType.I64;
        tmp32.ID = 15;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(RacaCorCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.sexoCidadao)
      {
        tmp32.Name = "sexoCidadao";
        tmp32.Type = TType.I64;
        tmp32.ID = 16;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(SexoCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusEhResponsavel)
      {
        tmp32.Name = "statusEhResponsavel";
        tmp32.Type = TType.Bool;
        tmp32.ID = 17;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteBoolAsync(StatusEhResponsavel, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@etnia)
      {
        tmp32.Name = "etnia";
        tmp32.Type = TType.I64;
        tmp32.ID = 18;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(Etnia, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomePaiCidadao != null) && __isset.nomePaiCidadao)
      {
        tmp32.Name = "nomePaiCidadao";
        tmp32.Type = TType.String;
        tmp32.ID = 19;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(NomePaiCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.desconheceNomePai)
      {
        tmp32.Name = "desconheceNomePai";
        tmp32.Type = TType.Bool;
        tmp32.ID = 20;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteBoolAsync(DesconheceNomePai, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dtNaturalizacao)
      {
        tmp32.Name = "dtNaturalizacao";
        tmp32.Type = TType.I64;
        tmp32.ID = 21;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DtNaturalizacao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((PortariaNaturalizacao != null) && __isset.portariaNaturalizacao)
      {
        tmp32.Name = "portariaNaturalizacao";
        tmp32.Type = TType.String;
        tmp32.ID = 22;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(PortariaNaturalizacao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dtEntradaBrasil)
      {
        tmp32.Name = "dtEntradaBrasil";
        tmp32.Type = TType.I64;
        tmp32.ID = 23;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DtEntradaBrasil, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MicroArea != null) && __isset.microArea)
      {
        tmp32.Name = "microArea";
        tmp32.Type = TType.String;
        tmp32.ID = 24;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(MicroArea, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.stForaArea)
      {
        tmp32.Name = "stForaArea";
        tmp32.Type = TType.Bool;
        tmp32.ID = 25;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteBoolAsync(StForaArea, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CpfCidadao != null) && __isset.cpfCidadao)
      {
        tmp32.Name = "cpfCidadao";
        tmp32.Type = TType.String;
        tmp32.ID = 26;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(CpfCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CpfResponsavelFamiliar != null) && __isset.cpfResponsavelFamiliar)
      {
        tmp32.Name = "cpfResponsavelFamiliar";
        tmp32.Type = TType.String;
        tmp32.ID = 27;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(CpfResponsavelFamiliar, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is IdentificacaoUsuarioCidadaoThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.nomeSocial == other.__isset.nomeSocial) && ((!__isset.nomeSocial) || (global::System.Object.Equals(NomeSocial, other.NomeSocial))))
      && ((__isset.codigoIbgeMunicipioNascimento == other.__isset.codigoIbgeMunicipioNascimento) && ((!__isset.codigoIbgeMunicipioNascimento) || (global::System.Object.Equals(CodigoIbgeMunicipioNascimento, other.CodigoIbgeMunicipioNascimento))))
      && ((__isset.dataNascimentoCidadao == other.__isset.dataNascimentoCidadao) && ((!__isset.dataNascimentoCidadao) || (global::System.Object.Equals(DataNascimentoCidadao, other.DataNascimentoCidadao))))
      && ((__isset.desconheceNomeMae == other.__isset.desconheceNomeMae) && ((!__isset.desconheceNomeMae) || (global::System.Object.Equals(DesconheceNomeMae, other.DesconheceNomeMae))))
      && ((__isset.emailCidadao == other.__isset.emailCidadao) && ((!__isset.emailCidadao) || (global::System.Object.Equals(EmailCidadao, other.EmailCidadao))))
      && ((__isset.nacionalidadeCidadao == other.__isset.nacionalidadeCidadao) && ((!__isset.nacionalidadeCidadao) || (global::System.Object.Equals(NacionalidadeCidadao, other.NacionalidadeCidadao))))
      && ((__isset.nomeCidadao == other.__isset.nomeCidadao) && ((!__isset.nomeCidadao) || (global::System.Object.Equals(NomeCidadao, other.NomeCidadao))))
      && ((__isset.nomeMaeCidadao == other.__isset.nomeMaeCidadao) && ((!__isset.nomeMaeCidadao) || (global::System.Object.Equals(NomeMaeCidadao, other.NomeMaeCidadao))))
      && ((__isset.cnsCidadao == other.__isset.cnsCidadao) && ((!__isset.cnsCidadao) || (global::System.Object.Equals(CnsCidadao, other.CnsCidadao))))
      && ((__isset.cnsResponsavelFamiliar == other.__isset.cnsResponsavelFamiliar) && ((!__isset.cnsResponsavelFamiliar) || (global::System.Object.Equals(CnsResponsavelFamiliar, other.CnsResponsavelFamiliar))))
      && ((__isset.telefoneCelular == other.__isset.telefoneCelular) && ((!__isset.telefoneCelular) || (global::System.Object.Equals(TelefoneCelular, other.TelefoneCelular))))
      && ((__isset.numeroNisPisPasep == other.__isset.numeroNisPisPasep) && ((!__isset.numeroNisPisPasep) || (global::System.Object.Equals(NumeroNisPisPasep, other.NumeroNisPisPasep))))
      && ((__isset.paisNascimento == other.__isset.paisNascimento) && ((!__isset.paisNascimento) || (global::System.Object.Equals(PaisNascimento, other.PaisNascimento))))
      && ((__isset.racaCorCidadao == other.__isset.racaCorCidadao) && ((!__isset.racaCorCidadao) || (global::System.Object.Equals(RacaCorCidadao, other.RacaCorCidadao))))
      && ((__isset.sexoCidadao == other.__isset.sexoCidadao) && ((!__isset.sexoCidadao) || (global::System.Object.Equals(SexoCidadao, other.SexoCidadao))))
      && ((__isset.statusEhResponsavel == other.__isset.statusEhResponsavel) && ((!__isset.statusEhResponsavel) || (global::System.Object.Equals(StatusEhResponsavel, other.StatusEhResponsavel))))
      && ((__isset.@etnia == other.__isset.@etnia) && ((!__isset.@etnia) || (global::System.Object.Equals(Etnia, other.Etnia))))
      && ((__isset.nomePaiCidadao == other.__isset.nomePaiCidadao) && ((!__isset.nomePaiCidadao) || (global::System.Object.Equals(NomePaiCidadao, other.NomePaiCidadao))))
      && ((__isset.desconheceNomePai == other.__isset.desconheceNomePai) && ((!__isset.desconheceNomePai) || (global::System.Object.Equals(DesconheceNomePai, other.DesconheceNomePai))))
      && ((__isset.dtNaturalizacao == other.__isset.dtNaturalizacao) && ((!__isset.dtNaturalizacao) || (global::System.Object.Equals(DtNaturalizacao, other.DtNaturalizacao))))
      && ((__isset.portariaNaturalizacao == other.__isset.portariaNaturalizacao) && ((!__isset.portariaNaturalizacao) || (global::System.Object.Equals(PortariaNaturalizacao, other.PortariaNaturalizacao))))
      && ((__isset.dtEntradaBrasil == other.__isset.dtEntradaBrasil) && ((!__isset.dtEntradaBrasil) || (global::System.Object.Equals(DtEntradaBrasil, other.DtEntradaBrasil))))
      && ((__isset.microArea == other.__isset.microArea) && ((!__isset.microArea) || (global::System.Object.Equals(MicroArea, other.MicroArea))))
      && ((__isset.stForaArea == other.__isset.stForaArea) && ((!__isset.stForaArea) || (global::System.Object.Equals(StForaArea, other.StForaArea))))
      && ((__isset.cpfCidadao == other.__isset.cpfCidadao) && ((!__isset.cpfCidadao) || (global::System.Object.Equals(CpfCidadao, other.CpfCidadao))))
      && ((__isset.cpfResponsavelFamiliar == other.__isset.cpfResponsavelFamiliar) && ((!__isset.cpfResponsavelFamiliar) || (global::System.Object.Equals(CpfResponsavelFamiliar, other.CpfResponsavelFamiliar))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((NomeSocial != null) && __isset.nomeSocial)
      {
        hashcode = (hashcode * 397) + NomeSocial.GetHashCode();
      }
      if((CodigoIbgeMunicipioNascimento != null) && __isset.codigoIbgeMunicipioNascimento)
      {
        hashcode = (hashcode * 397) + CodigoIbgeMunicipioNascimento.GetHashCode();
      }
      if(__isset.dataNascimentoCidadao)
      {
        hashcode = (hashcode * 397) + DataNascimentoCidadao.GetHashCode();
      }
      if(__isset.desconheceNomeMae)
      {
        hashcode = (hashcode * 397) + DesconheceNomeMae.GetHashCode();
      }
      if((EmailCidadao != null) && __isset.emailCidadao)
      {
        hashcode = (hashcode * 397) + EmailCidadao.GetHashCode();
      }
      if(__isset.nacionalidadeCidadao)
      {
        hashcode = (hashcode * 397) + NacionalidadeCidadao.GetHashCode();
      }
      if((NomeCidadao != null) && __isset.nomeCidadao)
      {
        hashcode = (hashcode * 397) + NomeCidadao.GetHashCode();
      }
      if((NomeMaeCidadao != null) && __isset.nomeMaeCidadao)
      {
        hashcode = (hashcode * 397) + NomeMaeCidadao.GetHashCode();
      }
      if((CnsCidadao != null) && __isset.cnsCidadao)
      {
        hashcode = (hashcode * 397) + CnsCidadao.GetHashCode();
      }
      if((CnsResponsavelFamiliar != null) && __isset.cnsResponsavelFamiliar)
      {
        hashcode = (hashcode * 397) + CnsResponsavelFamiliar.GetHashCode();
      }
      if((TelefoneCelular != null) && __isset.telefoneCelular)
      {
        hashcode = (hashcode * 397) + TelefoneCelular.GetHashCode();
      }
      if((NumeroNisPisPasep != null) && __isset.numeroNisPisPasep)
      {
        hashcode = (hashcode * 397) + NumeroNisPisPasep.GetHashCode();
      }
      if(__isset.paisNascimento)
      {
        hashcode = (hashcode * 397) + PaisNascimento.GetHashCode();
      }
      if(__isset.racaCorCidadao)
      {
        hashcode = (hashcode * 397) + RacaCorCidadao.GetHashCode();
      }
      if(__isset.sexoCidadao)
      {
        hashcode = (hashcode * 397) + SexoCidadao.GetHashCode();
      }
      if(__isset.statusEhResponsavel)
      {
        hashcode = (hashcode * 397) + StatusEhResponsavel.GetHashCode();
      }
      if(__isset.@etnia)
      {
        hashcode = (hashcode * 397) + Etnia.GetHashCode();
      }
      if((NomePaiCidadao != null) && __isset.nomePaiCidadao)
      {
        hashcode = (hashcode * 397) + NomePaiCidadao.GetHashCode();
      }
      if(__isset.desconheceNomePai)
      {
        hashcode = (hashcode * 397) + DesconheceNomePai.GetHashCode();
      }
      if(__isset.dtNaturalizacao)
      {
        hashcode = (hashcode * 397) + DtNaturalizacao.GetHashCode();
      }
      if((PortariaNaturalizacao != null) && __isset.portariaNaturalizacao)
      {
        hashcode = (hashcode * 397) + PortariaNaturalizacao.GetHashCode();
      }
      if(__isset.dtEntradaBrasil)
      {
        hashcode = (hashcode * 397) + DtEntradaBrasil.GetHashCode();
      }
      if((MicroArea != null) && __isset.microArea)
      {
        hashcode = (hashcode * 397) + MicroArea.GetHashCode();
      }
      if(__isset.stForaArea)
      {
        hashcode = (hashcode * 397) + StForaArea.GetHashCode();
      }
      if((CpfCidadao != null) && __isset.cpfCidadao)
      {
        hashcode = (hashcode * 397) + CpfCidadao.GetHashCode();
      }
      if((CpfResponsavelFamiliar != null) && __isset.cpfResponsavelFamiliar)
      {
        hashcode = (hashcode * 397) + CpfResponsavelFamiliar.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp33 = new StringBuilder("IdentificacaoUsuarioCidadaoThrift(");
    int tmp34 = 0;
    if((NomeSocial != null) && __isset.nomeSocial)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("NomeSocial: ");
      NomeSocial.ToString(tmp33);
    }
    if((CodigoIbgeMunicipioNascimento != null) && __isset.codigoIbgeMunicipioNascimento)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("CodigoIbgeMunicipioNascimento: ");
      CodigoIbgeMunicipioNascimento.ToString(tmp33);
    }
    if(__isset.dataNascimentoCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DataNascimentoCidadao: ");
      DataNascimentoCidadao.ToString(tmp33);
    }
    if(__isset.desconheceNomeMae)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DesconheceNomeMae: ");
      DesconheceNomeMae.ToString(tmp33);
    }
    if((EmailCidadao != null) && __isset.emailCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("EmailCidadao: ");
      EmailCidadao.ToString(tmp33);
    }
    if(__isset.nacionalidadeCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("NacionalidadeCidadao: ");
      NacionalidadeCidadao.ToString(tmp33);
    }
    if((NomeCidadao != null) && __isset.nomeCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("NomeCidadao: ");
      NomeCidadao.ToString(tmp33);
    }
    if((NomeMaeCidadao != null) && __isset.nomeMaeCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("NomeMaeCidadao: ");
      NomeMaeCidadao.ToString(tmp33);
    }
    if((CnsCidadao != null) && __isset.cnsCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("CnsCidadao: ");
      CnsCidadao.ToString(tmp33);
    }
    if((CnsResponsavelFamiliar != null) && __isset.cnsResponsavelFamiliar)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("CnsResponsavelFamiliar: ");
      CnsResponsavelFamiliar.ToString(tmp33);
    }
    if((TelefoneCelular != null) && __isset.telefoneCelular)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("TelefoneCelular: ");
      TelefoneCelular.ToString(tmp33);
    }
    if((NumeroNisPisPasep != null) && __isset.numeroNisPisPasep)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("NumeroNisPisPasep: ");
      NumeroNisPisPasep.ToString(tmp33);
    }
    if(__isset.paisNascimento)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("PaisNascimento: ");
      PaisNascimento.ToString(tmp33);
    }
    if(__isset.racaCorCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("RacaCorCidadao: ");
      RacaCorCidadao.ToString(tmp33);
    }
    if(__isset.sexoCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("SexoCidadao: ");
      SexoCidadao.ToString(tmp33);
    }
    if(__isset.statusEhResponsavel)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("StatusEhResponsavel: ");
      StatusEhResponsavel.ToString(tmp33);
    }
    if(__isset.@etnia)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("Etnia: ");
      Etnia.ToString(tmp33);
    }
    if((NomePaiCidadao != null) && __isset.nomePaiCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("NomePaiCidadao: ");
      NomePaiCidadao.ToString(tmp33);
    }
    if(__isset.desconheceNomePai)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DesconheceNomePai: ");
      DesconheceNomePai.ToString(tmp33);
    }
    if(__isset.dtNaturalizacao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DtNaturalizacao: ");
      DtNaturalizacao.ToString(tmp33);
    }
    if((PortariaNaturalizacao != null) && __isset.portariaNaturalizacao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("PortariaNaturalizacao: ");
      PortariaNaturalizacao.ToString(tmp33);
    }
    if(__isset.dtEntradaBrasil)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DtEntradaBrasil: ");
      DtEntradaBrasil.ToString(tmp33);
    }
    if((MicroArea != null) && __isset.microArea)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("MicroArea: ");
      MicroArea.ToString(tmp33);
    }
    if(__isset.stForaArea)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("StForaArea: ");
      StForaArea.ToString(tmp33);
    }
    if((CpfCidadao != null) && __isset.cpfCidadao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("CpfCidadao: ");
      CpfCidadao.ToString(tmp33);
    }
    if((CpfResponsavelFamiliar != null) && __isset.cpfResponsavelFamiliar)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("CpfResponsavelFamiliar: ");
      CpfResponsavelFamiliar.ToString(tmp33);
    }
    tmp33.Append(')');
    return tmp33.ToString();
  }
}

