/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Collections;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class FichaProcedimentoMasterThrift : TBase
{
  private int _tpCdsOrigem;
  private UnicaLotacaoHeaderThrift _headerTransport;
  private List<FichaProcedimentoChildThrift> _atendProcedimentos;
  private long _numTotalAfericaoPa;
  private long _numTotalGlicemiaCapilar;
  private long _numTotalAfericaoTemperatura;
  private long _numTotalMedicaoAltura;
  private long _numTotalCurativoSimples;
  private long _numTotalMedicaoPeso;
  private long _numTotalColetaMaterialParaExameLaboratorial;

  public string UuidFicha { get; set; }

  public int TpCdsOrigem
  {
    get
    {
      return _tpCdsOrigem;
    }
    set
    {
      __isset.tpCdsOrigem = true;
      this._tpCdsOrigem = value;
    }
  }

  public UnicaLotacaoHeaderThrift HeaderTransport
  {
    get
    {
      return _headerTransport;
    }
    set
    {
      __isset.headerTransport = true;
      this._headerTransport = value;
    }
  }

  public List<FichaProcedimentoChildThrift> AtendProcedimentos
  {
    get
    {
      return _atendProcedimentos;
    }
    set
    {
      __isset.atendProcedimentos = true;
      this._atendProcedimentos = value;
    }
  }

  public long NumTotalAfericaoPa
  {
    get
    {
      return _numTotalAfericaoPa;
    }
    set
    {
      __isset.numTotalAfericaoPa = true;
      this._numTotalAfericaoPa = value;
    }
  }

  public long NumTotalGlicemiaCapilar
  {
    get
    {
      return _numTotalGlicemiaCapilar;
    }
    set
    {
      __isset.numTotalGlicemiaCapilar = true;
      this._numTotalGlicemiaCapilar = value;
    }
  }

  public long NumTotalAfericaoTemperatura
  {
    get
    {
      return _numTotalAfericaoTemperatura;
    }
    set
    {
      __isset.numTotalAfericaoTemperatura = true;
      this._numTotalAfericaoTemperatura = value;
    }
  }

  public long NumTotalMedicaoAltura
  {
    get
    {
      return _numTotalMedicaoAltura;
    }
    set
    {
      __isset.numTotalMedicaoAltura = true;
      this._numTotalMedicaoAltura = value;
    }
  }

  public long NumTotalCurativoSimples
  {
    get
    {
      return _numTotalCurativoSimples;
    }
    set
    {
      __isset.numTotalCurativoSimples = true;
      this._numTotalCurativoSimples = value;
    }
  }

  public long NumTotalMedicaoPeso
  {
    get
    {
      return _numTotalMedicaoPeso;
    }
    set
    {
      __isset.numTotalMedicaoPeso = true;
      this._numTotalMedicaoPeso = value;
    }
  }

  public long NumTotalColetaMaterialParaExameLaboratorial
  {
    get
    {
      return _numTotalColetaMaterialParaExameLaboratorial;
    }
    set
    {
      __isset.numTotalColetaMaterialParaExameLaboratorial = true;
      this._numTotalColetaMaterialParaExameLaboratorial = value;
    }
  }


  public FichaProcedimentoMaster __isset;
  public struct FichaProcedimentoMaster
    {
    public bool tpCdsOrigem;
    public bool headerTransport;
    public bool atendProcedimentos;
    public bool numTotalAfericaoPa;
    public bool numTotalGlicemiaCapilar;
    public bool numTotalAfericaoTemperatura;
    public bool numTotalMedicaoAltura;
    public bool numTotalCurativoSimples;
    public bool numTotalMedicaoPeso;
    public bool numTotalColetaMaterialParaExameLaboratorial;
  }

  public FichaProcedimentoMasterThrift()
  {
  }

  public FichaProcedimentoMasterThrift(string uuidFicha) : this()
  {
    this.UuidFicha = uuidFicha;
  }

  public FichaProcedimentoMasterThrift DeepCopy()
  {
    var tmp9 = new FichaProcedimentoMasterThrift();
    if((UuidFicha != null))
    {
      tmp9.UuidFicha = this.UuidFicha;
    }
    if(__isset.tpCdsOrigem)
    {
      tmp9.TpCdsOrigem = this.TpCdsOrigem;
    }
    tmp9.__isset.tpCdsOrigem = this.__isset.tpCdsOrigem;
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp9.HeaderTransport = (UnicaLotacaoHeaderThrift)this.HeaderTransport.DeepCopy();
    }
    tmp9.__isset.headerTransport = this.__isset.headerTransport;
    if((AtendProcedimentos != null) && __isset.atendProcedimentos)
    {
      tmp9.AtendProcedimentos = this.AtendProcedimentos.DeepCopy();
    }
    tmp9.__isset.atendProcedimentos = this.__isset.atendProcedimentos;
    if(__isset.numTotalAfericaoPa)
    {
      tmp9.NumTotalAfericaoPa = this.NumTotalAfericaoPa;
    }
    tmp9.__isset.numTotalAfericaoPa = this.__isset.numTotalAfericaoPa;
    if(__isset.numTotalGlicemiaCapilar)
    {
      tmp9.NumTotalGlicemiaCapilar = this.NumTotalGlicemiaCapilar;
    }
    tmp9.__isset.numTotalGlicemiaCapilar = this.__isset.numTotalGlicemiaCapilar;
    if(__isset.numTotalAfericaoTemperatura)
    {
      tmp9.NumTotalAfericaoTemperatura = this.NumTotalAfericaoTemperatura;
    }
    tmp9.__isset.numTotalAfericaoTemperatura = this.__isset.numTotalAfericaoTemperatura;
    if(__isset.numTotalMedicaoAltura)
    {
      tmp9.NumTotalMedicaoAltura = this.NumTotalMedicaoAltura;
    }
    tmp9.__isset.numTotalMedicaoAltura = this.__isset.numTotalMedicaoAltura;
    if(__isset.numTotalCurativoSimples)
    {
      tmp9.NumTotalCurativoSimples = this.NumTotalCurativoSimples;
    }
    tmp9.__isset.numTotalCurativoSimples = this.__isset.numTotalCurativoSimples;
    if(__isset.numTotalMedicaoPeso)
    {
      tmp9.NumTotalMedicaoPeso = this.NumTotalMedicaoPeso;
    }
    tmp9.__isset.numTotalMedicaoPeso = this.__isset.numTotalMedicaoPeso;
    if(__isset.numTotalColetaMaterialParaExameLaboratorial)
    {
      tmp9.NumTotalColetaMaterialParaExameLaboratorial = this.NumTotalColetaMaterialParaExameLaboratorial;
    }
    tmp9.__isset.numTotalColetaMaterialParaExameLaboratorial = this.__isset.numTotalColetaMaterialParaExameLaboratorial;
    return tmp9;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_uuidFicha = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              UuidFicha = await iprot.ReadStringAsync(cancellationToken);
              isset_uuidFicha = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I32)
            {
              TpCdsOrigem = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Struct)
            {
              HeaderTransport = new UnicaLotacaoHeaderThrift();
              await HeaderTransport.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.List)
            {
              {
                var _list10 = await iprot.ReadListBeginAsync(cancellationToken);
                AtendProcedimentos = new List<FichaProcedimentoChildThrift>(_list10.Count);
                for(int _i11 = 0; _i11 < _list10.Count; ++_i11)
                {
                  FichaProcedimentoChildThrift _elem12;
                  _elem12 = new FichaProcedimentoChildThrift();
                  await _elem12.ReadAsync(iprot, cancellationToken);
                  AtendProcedimentos.Add(_elem12);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.I64)
            {
              NumTotalAfericaoPa = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.I64)
            {
              NumTotalGlicemiaCapilar = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.I64)
            {
              NumTotalAfericaoTemperatura = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.I64)
            {
              NumTotalMedicaoAltura = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.I64)
            {
              NumTotalCurativoSimples = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.I64)
            {
              NumTotalMedicaoPeso = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.I64)
            {
              NumTotalColetaMaterialParaExameLaboratorial = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_uuidFicha)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp13 = new TStruct("FichaProcedimentoMasterThrift");
      await oprot.WriteStructBeginAsync(tmp13, cancellationToken);
      var tmp14 = new TField();
      if((UuidFicha != null))
      {
        tmp14.Name = "uuidFicha";
        tmp14.Type = TType.String;
        tmp14.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteStringAsync(UuidFicha, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.tpCdsOrigem)
      {
        tmp14.Name = "tpCdsOrigem";
        tmp14.Type = TType.I32;
        tmp14.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI32Async(TpCdsOrigem, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        tmp14.Name = "headerTransport";
        tmp14.Type = TType.Struct;
        tmp14.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await HeaderTransport.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((AtendProcedimentos != null) && __isset.atendProcedimentos)
      {
        tmp14.Name = "atendProcedimentos";
        tmp14.Type = TType.List;
        tmp14.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, AtendProcedimentos.Count), cancellationToken);
        foreach (FichaProcedimentoChildThrift _iter15 in AtendProcedimentos)
        {
          await _iter15.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalAfericaoPa)
      {
        tmp14.Name = "numTotalAfericaoPa";
        tmp14.Type = TType.I64;
        tmp14.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalAfericaoPa, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalGlicemiaCapilar)
      {
        tmp14.Name = "numTotalGlicemiaCapilar";
        tmp14.Type = TType.I64;
        tmp14.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalGlicemiaCapilar, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalAfericaoTemperatura)
      {
        tmp14.Name = "numTotalAfericaoTemperatura";
        tmp14.Type = TType.I64;
        tmp14.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalAfericaoTemperatura, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalMedicaoAltura)
      {
        tmp14.Name = "numTotalMedicaoAltura";
        tmp14.Type = TType.I64;
        tmp14.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalMedicaoAltura, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalCurativoSimples)
      {
        tmp14.Name = "numTotalCurativoSimples";
        tmp14.Type = TType.I64;
        tmp14.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalCurativoSimples, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalMedicaoPeso)
      {
        tmp14.Name = "numTotalMedicaoPeso";
        tmp14.Type = TType.I64;
        tmp14.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalMedicaoPeso, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.numTotalColetaMaterialParaExameLaboratorial)
      {
        tmp14.Name = "numTotalColetaMaterialParaExameLaboratorial";
        tmp14.Type = TType.I64;
        tmp14.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp14, cancellationToken);
        await oprot.WriteI64Async(NumTotalColetaMaterialParaExameLaboratorial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FichaProcedimentoMasterThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(UuidFicha, other.UuidFicha)
      && ((__isset.tpCdsOrigem == other.__isset.tpCdsOrigem) && ((!__isset.tpCdsOrigem) || (global::System.Object.Equals(TpCdsOrigem, other.TpCdsOrigem))))
      && ((__isset.headerTransport == other.__isset.headerTransport) && ((!__isset.headerTransport) || (global::System.Object.Equals(HeaderTransport, other.HeaderTransport))))
      && ((__isset.atendProcedimentos == other.__isset.atendProcedimentos) && ((!__isset.atendProcedimentos) || (TCollections.Equals(AtendProcedimentos, other.AtendProcedimentos))))
      && ((__isset.numTotalAfericaoPa == other.__isset.numTotalAfericaoPa) && ((!__isset.numTotalAfericaoPa) || (global::System.Object.Equals(NumTotalAfericaoPa, other.NumTotalAfericaoPa))))
      && ((__isset.numTotalGlicemiaCapilar == other.__isset.numTotalGlicemiaCapilar) && ((!__isset.numTotalGlicemiaCapilar) || (global::System.Object.Equals(NumTotalGlicemiaCapilar, other.NumTotalGlicemiaCapilar))))
      && ((__isset.numTotalAfericaoTemperatura == other.__isset.numTotalAfericaoTemperatura) && ((!__isset.numTotalAfericaoTemperatura) || (global::System.Object.Equals(NumTotalAfericaoTemperatura, other.NumTotalAfericaoTemperatura))))
      && ((__isset.numTotalMedicaoAltura == other.__isset.numTotalMedicaoAltura) && ((!__isset.numTotalMedicaoAltura) || (global::System.Object.Equals(NumTotalMedicaoAltura, other.NumTotalMedicaoAltura))))
      && ((__isset.numTotalCurativoSimples == other.__isset.numTotalCurativoSimples) && ((!__isset.numTotalCurativoSimples) || (global::System.Object.Equals(NumTotalCurativoSimples, other.NumTotalCurativoSimples))))
      && ((__isset.numTotalMedicaoPeso == other.__isset.numTotalMedicaoPeso) && ((!__isset.numTotalMedicaoPeso) || (global::System.Object.Equals(NumTotalMedicaoPeso, other.NumTotalMedicaoPeso))))
      && ((__isset.numTotalColetaMaterialParaExameLaboratorial == other.__isset.numTotalColetaMaterialParaExameLaboratorial) && ((!__isset.numTotalColetaMaterialParaExameLaboratorial) || (global::System.Object.Equals(NumTotalColetaMaterialParaExameLaboratorial, other.NumTotalColetaMaterialParaExameLaboratorial))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((UuidFicha != null))
      {
        hashcode = (hashcode * 397) + UuidFicha.GetHashCode();
      }
      if(__isset.tpCdsOrigem)
      {
        hashcode = (hashcode * 397) + TpCdsOrigem.GetHashCode();
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        hashcode = (hashcode * 397) + HeaderTransport.GetHashCode();
      }
      if((AtendProcedimentos != null) && __isset.atendProcedimentos)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(AtendProcedimentos);
      }
      if(__isset.numTotalAfericaoPa)
      {
        hashcode = (hashcode * 397) + NumTotalAfericaoPa.GetHashCode();
      }
      if(__isset.numTotalGlicemiaCapilar)
      {
        hashcode = (hashcode * 397) + NumTotalGlicemiaCapilar.GetHashCode();
      }
      if(__isset.numTotalAfericaoTemperatura)
      {
        hashcode = (hashcode * 397) + NumTotalAfericaoTemperatura.GetHashCode();
      }
      if(__isset.numTotalMedicaoAltura)
      {
        hashcode = (hashcode * 397) + NumTotalMedicaoAltura.GetHashCode();
      }
      if(__isset.numTotalCurativoSimples)
      {
        hashcode = (hashcode * 397) + NumTotalCurativoSimples.GetHashCode();
      }
      if(__isset.numTotalMedicaoPeso)
      {
        hashcode = (hashcode * 397) + NumTotalMedicaoPeso.GetHashCode();
      }
      if(__isset.numTotalColetaMaterialParaExameLaboratorial)
      {
        hashcode = (hashcode * 397) + NumTotalColetaMaterialParaExameLaboratorial.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp16 = new StringBuilder("FichaProcedimentoMasterThrift(");
    if((UuidFicha != null))
    {
      tmp16.Append(", UuidFicha: ");
      UuidFicha.ToString(tmp16);
    }
    if(__isset.tpCdsOrigem)
    {
      tmp16.Append(", TpCdsOrigem: ");
      TpCdsOrigem.ToString(tmp16);
    }
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp16.Append(", HeaderTransport: ");
      HeaderTransport.ToString(tmp16);
    }
    if((AtendProcedimentos != null) && __isset.atendProcedimentos)
    {
      tmp16.Append(", AtendProcedimentos: ");
      AtendProcedimentos.ToString(tmp16);
    }
    if(__isset.numTotalAfericaoPa)
    {
      tmp16.Append(", NumTotalAfericaoPa: ");
      NumTotalAfericaoPa.ToString(tmp16);
    }
    if(__isset.numTotalGlicemiaCapilar)
    {
      tmp16.Append(", NumTotalGlicemiaCapilar: ");
      NumTotalGlicemiaCapilar.ToString(tmp16);
    }
    if(__isset.numTotalAfericaoTemperatura)
    {
      tmp16.Append(", NumTotalAfericaoTemperatura: ");
      NumTotalAfericaoTemperatura.ToString(tmp16);
    }
    if(__isset.numTotalMedicaoAltura)
    {
      tmp16.Append(", NumTotalMedicaoAltura: ");
      NumTotalMedicaoAltura.ToString(tmp16);
    }
    if(__isset.numTotalCurativoSimples)
    {
      tmp16.Append(", NumTotalCurativoSimples: ");
      NumTotalCurativoSimples.ToString(tmp16);
    }
    if(__isset.numTotalMedicaoPeso)
    {
      tmp16.Append(", NumTotalMedicaoPeso: ");
      NumTotalMedicaoPeso.ToString(tmp16);
    }
    if(__isset.numTotalColetaMaterialParaExameLaboratorial)
    {
      tmp16.Append(", NumTotalColetaMaterialParaExameLaboratorial: ");
      NumTotalColetaMaterialParaExameLaboratorial.ToString(tmp16);
    }
    tmp16.Append(')');
    return tmp16.ToString();
  }
}

