/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class LotacaoHeaderThrift : TBase
{
  private string _profissionalCNS;
  private string _cboCodigo_2002;
  private string _cnes;
  private string _ine;

  public string ProfissionalCNS
  {
    get
    {
      return _profissionalCNS;
    }
    set
    {
      __isset.profissionalCNS = true;
      this._profissionalCNS = value;
    }
  }

  public string CboCodigo_2002
  {
    get
    {
      return _cboCodigo_2002;
    }
    set
    {
      __isset.cboCodigo_2002 = true;
      this._cboCodigo_2002 = value;
    }
  }

  public string Cnes
  {
    get
    {
      return _cnes;
    }
    set
    {
      __isset.@cnes = true;
      this._cnes = value;
    }
  }

  public string Ine
  {
    get
    {
      return _ine;
    }
    set
    {
      __isset.@ine = true;
      this._ine = value;
    }
  }


  public LotacaoHeader __isset;
  public struct LotacaoHeader
    {
    public bool profissionalCNS;
    public bool cboCodigo_2002;
    public bool @cnes;
    public bool @ine;
  }

  public LotacaoHeaderThrift()
  {
  }

  public LotacaoHeaderThrift DeepCopy()
  {
    var tmp5 = new LotacaoHeaderThrift();
    if((ProfissionalCNS != null) && __isset.profissionalCNS)
    {
      tmp5.ProfissionalCNS = this.ProfissionalCNS;
    }
    tmp5.__isset.profissionalCNS = this.__isset.profissionalCNS;
    if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
    {
      tmp5.CboCodigo_2002 = this.CboCodigo_2002;
    }
    tmp5.__isset.cboCodigo_2002 = this.__isset.cboCodigo_2002;
    if((Cnes != null) && __isset.@cnes)
    {
      tmp5.Cnes = this.Cnes;
    }
    tmp5.__isset.@cnes = this.__isset.@cnes;
    if((Ine != null) && __isset.@ine)
    {
      tmp5.Ine = this.Ine;
    }
    tmp5.__isset.@ine = this.__isset.@ine;
    return tmp5;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              ProfissionalCNS = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              CboCodigo_2002 = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              Cnes = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              Ine = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp6 = new TStruct("LotacaoHeaderThrift");
      await oprot.WriteStructBeginAsync(tmp6, cancellationToken);
      var tmp7 = new TField();
      if((ProfissionalCNS != null) && __isset.profissionalCNS)
      {
        tmp7.Name = "profissionalCNS";
        tmp7.Type = TType.String;
        tmp7.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(ProfissionalCNS, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
      {
        tmp7.Name = "cboCodigo_2002";
        tmp7.Type = TType.String;
        tmp7.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(CboCodigo_2002, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Cnes != null) && __isset.@cnes)
      {
        tmp7.Name = "cnes";
        tmp7.Type = TType.String;
        tmp7.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Cnes, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Ine != null) && __isset.@ine)
      {
        tmp7.Name = "ine";
        tmp7.Type = TType.String;
        tmp7.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Ine, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is LotacaoHeaderThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.profissionalCNS == other.__isset.profissionalCNS) && ((!__isset.profissionalCNS) || (global::System.Object.Equals(ProfissionalCNS, other.ProfissionalCNS))))
      && ((__isset.cboCodigo_2002 == other.__isset.cboCodigo_2002) && ((!__isset.cboCodigo_2002) || (global::System.Object.Equals(CboCodigo_2002, other.CboCodigo_2002))))
      && ((__isset.@cnes == other.__isset.@cnes) && ((!__isset.@cnes) || (global::System.Object.Equals(Cnes, other.Cnes))))
      && ((__isset.@ine == other.__isset.@ine) && ((!__isset.@ine) || (global::System.Object.Equals(Ine, other.Ine))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((ProfissionalCNS != null) && __isset.profissionalCNS)
      {
        hashcode = (hashcode * 397) + ProfissionalCNS.GetHashCode();
      }
      if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
      {
        hashcode = (hashcode * 397) + CboCodigo_2002.GetHashCode();
      }
      if((Cnes != null) && __isset.@cnes)
      {
        hashcode = (hashcode * 397) + Cnes.GetHashCode();
      }
      if((Ine != null) && __isset.@ine)
      {
        hashcode = (hashcode * 397) + Ine.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp8 = new StringBuilder("LotacaoHeaderThrift(");
    int tmp9 = 0;
    if((ProfissionalCNS != null) && __isset.profissionalCNS)
    {
      if(0 < tmp9++) { tmp8.Append(", "); }
      tmp8.Append("ProfissionalCNS: ");
      ProfissionalCNS.ToString(tmp8);
    }
    if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
    {
      if(0 < tmp9++) { tmp8.Append(", "); }
      tmp8.Append("CboCodigo_2002: ");
      CboCodigo_2002.ToString(tmp8);
    }
    if((Cnes != null) && __isset.@cnes)
    {
      if(0 < tmp9++) { tmp8.Append(", "); }
      tmp8.Append("Cnes: ");
      Cnes.ToString(tmp8);
    }
    if((Ine != null) && __isset.@ine)
    {
      if(0 < tmp9++) { tmp8.Append(", "); }
      tmp8.Append("Ine: ");
      Ine.ToString(tmp8);
    }
    tmp8.Append(')');
    return tmp8.ToString();
  }
}

