/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class MedicamentoThrift : TBase
{
  private string _codigoCatmat;
  private long _viaAdministracao;
  private string _dose;
  private bool _doseUnica;
  private bool _usoContinuo;
  private long _doseFrequenciaTipo;
  private string _doseFrequencia;
  private int _doseFrequenciaQuantidade;
  private long _doseFrequenciaUnidadeMedida;
  private long _dtInicioTratamento;
  private int _duracaoTratamento;
  private long _duracaoTratamentoMedida;
  private int _quantidadeReceitada;

  public string CodigoCatmat
  {
    get
    {
      return _codigoCatmat;
    }
    set
    {
      __isset.codigoCatmat = true;
      this._codigoCatmat = value;
    }
  }

  public long ViaAdministracao
  {
    get
    {
      return _viaAdministracao;
    }
    set
    {
      __isset.viaAdministracao = true;
      this._viaAdministracao = value;
    }
  }

  public string Dose
  {
    get
    {
      return _dose;
    }
    set
    {
      __isset.@dose = true;
      this._dose = value;
    }
  }

  public bool DoseUnica
  {
    get
    {
      return _doseUnica;
    }
    set
    {
      __isset.doseUnica = true;
      this._doseUnica = value;
    }
  }

  public bool UsoContinuo
  {
    get
    {
      return _usoContinuo;
    }
    set
    {
      __isset.usoContinuo = true;
      this._usoContinuo = value;
    }
  }

  public long DoseFrequenciaTipo
  {
    get
    {
      return _doseFrequenciaTipo;
    }
    set
    {
      __isset.doseFrequenciaTipo = true;
      this._doseFrequenciaTipo = value;
    }
  }

  public string DoseFrequencia
  {
    get
    {
      return _doseFrequencia;
    }
    set
    {
      __isset.doseFrequencia = true;
      this._doseFrequencia = value;
    }
  }

  public int DoseFrequenciaQuantidade
  {
    get
    {
      return _doseFrequenciaQuantidade;
    }
    set
    {
      __isset.doseFrequenciaQuantidade = true;
      this._doseFrequenciaQuantidade = value;
    }
  }

  public long DoseFrequenciaUnidadeMedida
  {
    get
    {
      return _doseFrequenciaUnidadeMedida;
    }
    set
    {
      __isset.doseFrequenciaUnidadeMedida = true;
      this._doseFrequenciaUnidadeMedida = value;
    }
  }

  public long DtInicioTratamento
  {
    get
    {
      return _dtInicioTratamento;
    }
    set
    {
      __isset.dtInicioTratamento = true;
      this._dtInicioTratamento = value;
    }
  }

  public int DuracaoTratamento
  {
    get
    {
      return _duracaoTratamento;
    }
    set
    {
      __isset.duracaoTratamento = true;
      this._duracaoTratamento = value;
    }
  }

  public long DuracaoTratamentoMedida
  {
    get
    {
      return _duracaoTratamentoMedida;
    }
    set
    {
      __isset.duracaoTratamentoMedida = true;
      this._duracaoTratamentoMedida = value;
    }
  }

  public int QuantidadeReceitada
  {
    get
    {
      return _quantidadeReceitada;
    }
    set
    {
      __isset.quantidadeReceitada = true;
      this._quantidadeReceitada = value;
    }
  }


  public Medicamento __isset;
  public struct Medicamento
    {
    public bool codigoCatmat;
    public bool viaAdministracao;
    public bool @dose;
    public bool doseUnica;
    public bool usoContinuo;
    public bool doseFrequenciaTipo;
    public bool doseFrequencia;
    public bool doseFrequenciaQuantidade;
    public bool doseFrequenciaUnidadeMedida;
    public bool dtInicioTratamento;
    public bool duracaoTratamento;
    public bool duracaoTratamentoMedida;
    public bool quantidadeReceitada;
  }

  public MedicamentoThrift()
  {
  }

  public MedicamentoThrift DeepCopy()
  {
    var tmp30 = new MedicamentoThrift();
    if((CodigoCatmat != null) && __isset.codigoCatmat)
    {
      tmp30.CodigoCatmat = this.CodigoCatmat;
    }
    tmp30.__isset.codigoCatmat = this.__isset.codigoCatmat;
    if(__isset.viaAdministracao)
    {
      tmp30.ViaAdministracao = this.ViaAdministracao;
    }
    tmp30.__isset.viaAdministracao = this.__isset.viaAdministracao;
    if((Dose != null) && __isset.@dose)
    {
      tmp30.Dose = this.Dose;
    }
    tmp30.__isset.@dose = this.__isset.@dose;
    if(__isset.doseUnica)
    {
      tmp30.DoseUnica = this.DoseUnica;
    }
    tmp30.__isset.doseUnica = this.__isset.doseUnica;
    if(__isset.usoContinuo)
    {
      tmp30.UsoContinuo = this.UsoContinuo;
    }
    tmp30.__isset.usoContinuo = this.__isset.usoContinuo;
    if(__isset.doseFrequenciaTipo)
    {
      tmp30.DoseFrequenciaTipo = this.DoseFrequenciaTipo;
    }
    tmp30.__isset.doseFrequenciaTipo = this.__isset.doseFrequenciaTipo;
    if((DoseFrequencia != null) && __isset.doseFrequencia)
    {
      tmp30.DoseFrequencia = this.DoseFrequencia;
    }
    tmp30.__isset.doseFrequencia = this.__isset.doseFrequencia;
    if(__isset.doseFrequenciaQuantidade)
    {
      tmp30.DoseFrequenciaQuantidade = this.DoseFrequenciaQuantidade;
    }
    tmp30.__isset.doseFrequenciaQuantidade = this.__isset.doseFrequenciaQuantidade;
    if(__isset.doseFrequenciaUnidadeMedida)
    {
      tmp30.DoseFrequenciaUnidadeMedida = this.DoseFrequenciaUnidadeMedida;
    }
    tmp30.__isset.doseFrequenciaUnidadeMedida = this.__isset.doseFrequenciaUnidadeMedida;
    if(__isset.dtInicioTratamento)
    {
      tmp30.DtInicioTratamento = this.DtInicioTratamento;
    }
    tmp30.__isset.dtInicioTratamento = this.__isset.dtInicioTratamento;
    if(__isset.duracaoTratamento)
    {
      tmp30.DuracaoTratamento = this.DuracaoTratamento;
    }
    tmp30.__isset.duracaoTratamento = this.__isset.duracaoTratamento;
    if(__isset.duracaoTratamentoMedida)
    {
      tmp30.DuracaoTratamentoMedida = this.DuracaoTratamentoMedida;
    }
    tmp30.__isset.duracaoTratamentoMedida = this.__isset.duracaoTratamentoMedida;
    if(__isset.quantidadeReceitada)
    {
      tmp30.QuantidadeReceitada = this.QuantidadeReceitada;
    }
    tmp30.__isset.quantidadeReceitada = this.__isset.quantidadeReceitada;
    return tmp30;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              CodigoCatmat = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              ViaAdministracao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              Dose = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.Bool)
            {
              DoseUnica = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.Bool)
            {
              UsoContinuo = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.I64)
            {
              DoseFrequenciaTipo = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.String)
            {
              DoseFrequencia = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.I32)
            {
              DoseFrequenciaQuantidade = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.I64)
            {
              DoseFrequenciaUnidadeMedida = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.I64)
            {
              DtInicioTratamento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.I32)
            {
              DuracaoTratamento = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.I64)
            {
              DuracaoTratamentoMedida = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.I32)
            {
              QuantidadeReceitada = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp31 = new TStruct("MedicamentoThrift");
      await oprot.WriteStructBeginAsync(tmp31, cancellationToken);
      var tmp32 = new TField();
      if((CodigoCatmat != null) && __isset.codigoCatmat)
      {
        tmp32.Name = "codigoCatmat";
        tmp32.Type = TType.String;
        tmp32.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(CodigoCatmat, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.viaAdministracao)
      {
        tmp32.Name = "viaAdministracao";
        tmp32.Type = TType.I64;
        tmp32.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(ViaAdministracao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Dose != null) && __isset.@dose)
      {
        tmp32.Name = "dose";
        tmp32.Type = TType.String;
        tmp32.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(Dose, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.doseUnica)
      {
        tmp32.Name = "doseUnica";
        tmp32.Type = TType.Bool;
        tmp32.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteBoolAsync(DoseUnica, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.usoContinuo)
      {
        tmp32.Name = "usoContinuo";
        tmp32.Type = TType.Bool;
        tmp32.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteBoolAsync(UsoContinuo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.doseFrequenciaTipo)
      {
        tmp32.Name = "doseFrequenciaTipo";
        tmp32.Type = TType.I64;
        tmp32.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DoseFrequenciaTipo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((DoseFrequencia != null) && __isset.doseFrequencia)
      {
        tmp32.Name = "doseFrequencia";
        tmp32.Type = TType.String;
        tmp32.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteStringAsync(DoseFrequencia, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.doseFrequenciaQuantidade)
      {
        tmp32.Name = "doseFrequenciaQuantidade";
        tmp32.Type = TType.I32;
        tmp32.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI32Async(DoseFrequenciaQuantidade, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.doseFrequenciaUnidadeMedida)
      {
        tmp32.Name = "doseFrequenciaUnidadeMedida";
        tmp32.Type = TType.I64;
        tmp32.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DoseFrequenciaUnidadeMedida, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dtInicioTratamento)
      {
        tmp32.Name = "dtInicioTratamento";
        tmp32.Type = TType.I64;
        tmp32.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DtInicioTratamento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.duracaoTratamento)
      {
        tmp32.Name = "duracaoTratamento";
        tmp32.Type = TType.I32;
        tmp32.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI32Async(DuracaoTratamento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.duracaoTratamentoMedida)
      {
        tmp32.Name = "duracaoTratamentoMedida";
        tmp32.Type = TType.I64;
        tmp32.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI64Async(DuracaoTratamentoMedida, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.quantidadeReceitada)
      {
        tmp32.Name = "quantidadeReceitada";
        tmp32.Type = TType.I32;
        tmp32.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp32, cancellationToken);
        await oprot.WriteI32Async(QuantidadeReceitada, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is MedicamentoThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.codigoCatmat == other.__isset.codigoCatmat) && ((!__isset.codigoCatmat) || (global::System.Object.Equals(CodigoCatmat, other.CodigoCatmat))))
      && ((__isset.viaAdministracao == other.__isset.viaAdministracao) && ((!__isset.viaAdministracao) || (global::System.Object.Equals(ViaAdministracao, other.ViaAdministracao))))
      && ((__isset.@dose == other.__isset.@dose) && ((!__isset.@dose) || (global::System.Object.Equals(Dose, other.Dose))))
      && ((__isset.doseUnica == other.__isset.doseUnica) && ((!__isset.doseUnica) || (global::System.Object.Equals(DoseUnica, other.DoseUnica))))
      && ((__isset.usoContinuo == other.__isset.usoContinuo) && ((!__isset.usoContinuo) || (global::System.Object.Equals(UsoContinuo, other.UsoContinuo))))
      && ((__isset.doseFrequenciaTipo == other.__isset.doseFrequenciaTipo) && ((!__isset.doseFrequenciaTipo) || (global::System.Object.Equals(DoseFrequenciaTipo, other.DoseFrequenciaTipo))))
      && ((__isset.doseFrequencia == other.__isset.doseFrequencia) && ((!__isset.doseFrequencia) || (global::System.Object.Equals(DoseFrequencia, other.DoseFrequencia))))
      && ((__isset.doseFrequenciaQuantidade == other.__isset.doseFrequenciaQuantidade) && ((!__isset.doseFrequenciaQuantidade) || (global::System.Object.Equals(DoseFrequenciaQuantidade, other.DoseFrequenciaQuantidade))))
      && ((__isset.doseFrequenciaUnidadeMedida == other.__isset.doseFrequenciaUnidadeMedida) && ((!__isset.doseFrequenciaUnidadeMedida) || (global::System.Object.Equals(DoseFrequenciaUnidadeMedida, other.DoseFrequenciaUnidadeMedida))))
      && ((__isset.dtInicioTratamento == other.__isset.dtInicioTratamento) && ((!__isset.dtInicioTratamento) || (global::System.Object.Equals(DtInicioTratamento, other.DtInicioTratamento))))
      && ((__isset.duracaoTratamento == other.__isset.duracaoTratamento) && ((!__isset.duracaoTratamento) || (global::System.Object.Equals(DuracaoTratamento, other.DuracaoTratamento))))
      && ((__isset.duracaoTratamentoMedida == other.__isset.duracaoTratamentoMedida) && ((!__isset.duracaoTratamentoMedida) || (global::System.Object.Equals(DuracaoTratamentoMedida, other.DuracaoTratamentoMedida))))
      && ((__isset.quantidadeReceitada == other.__isset.quantidadeReceitada) && ((!__isset.quantidadeReceitada) || (global::System.Object.Equals(QuantidadeReceitada, other.QuantidadeReceitada))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((CodigoCatmat != null) && __isset.codigoCatmat)
      {
        hashcode = (hashcode * 397) + CodigoCatmat.GetHashCode();
      }
      if(__isset.viaAdministracao)
      {
        hashcode = (hashcode * 397) + ViaAdministracao.GetHashCode();
      }
      if((Dose != null) && __isset.@dose)
      {
        hashcode = (hashcode * 397) + Dose.GetHashCode();
      }
      if(__isset.doseUnica)
      {
        hashcode = (hashcode * 397) + DoseUnica.GetHashCode();
      }
      if(__isset.usoContinuo)
      {
        hashcode = (hashcode * 397) + UsoContinuo.GetHashCode();
      }
      if(__isset.doseFrequenciaTipo)
      {
        hashcode = (hashcode * 397) + DoseFrequenciaTipo.GetHashCode();
      }
      if((DoseFrequencia != null) && __isset.doseFrequencia)
      {
        hashcode = (hashcode * 397) + DoseFrequencia.GetHashCode();
      }
      if(__isset.doseFrequenciaQuantidade)
      {
        hashcode = (hashcode * 397) + DoseFrequenciaQuantidade.GetHashCode();
      }
      if(__isset.doseFrequenciaUnidadeMedida)
      {
        hashcode = (hashcode * 397) + DoseFrequenciaUnidadeMedida.GetHashCode();
      }
      if(__isset.dtInicioTratamento)
      {
        hashcode = (hashcode * 397) + DtInicioTratamento.GetHashCode();
      }
      if(__isset.duracaoTratamento)
      {
        hashcode = (hashcode * 397) + DuracaoTratamento.GetHashCode();
      }
      if(__isset.duracaoTratamentoMedida)
      {
        hashcode = (hashcode * 397) + DuracaoTratamentoMedida.GetHashCode();
      }
      if(__isset.quantidadeReceitada)
      {
        hashcode = (hashcode * 397) + QuantidadeReceitada.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp33 = new StringBuilder("MedicamentoThrift(");
    int tmp34 = 0;
    if((CodigoCatmat != null) && __isset.codigoCatmat)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("CodigoCatmat: ");
      CodigoCatmat.ToString(tmp33);
    }
    if(__isset.viaAdministracao)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("ViaAdministracao: ");
      ViaAdministracao.ToString(tmp33);
    }
    if((Dose != null) && __isset.@dose)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("Dose: ");
      Dose.ToString(tmp33);
    }
    if(__isset.doseUnica)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DoseUnica: ");
      DoseUnica.ToString(tmp33);
    }
    if(__isset.usoContinuo)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("UsoContinuo: ");
      UsoContinuo.ToString(tmp33);
    }
    if(__isset.doseFrequenciaTipo)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DoseFrequenciaTipo: ");
      DoseFrequenciaTipo.ToString(tmp33);
    }
    if((DoseFrequencia != null) && __isset.doseFrequencia)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DoseFrequencia: ");
      DoseFrequencia.ToString(tmp33);
    }
    if(__isset.doseFrequenciaQuantidade)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DoseFrequenciaQuantidade: ");
      DoseFrequenciaQuantidade.ToString(tmp33);
    }
    if(__isset.doseFrequenciaUnidadeMedida)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DoseFrequenciaUnidadeMedida: ");
      DoseFrequenciaUnidadeMedida.ToString(tmp33);
    }
    if(__isset.dtInicioTratamento)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DtInicioTratamento: ");
      DtInicioTratamento.ToString(tmp33);
    }
    if(__isset.duracaoTratamento)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DuracaoTratamento: ");
      DuracaoTratamento.ToString(tmp33);
    }
    if(__isset.duracaoTratamentoMedida)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("DuracaoTratamentoMedida: ");
      DuracaoTratamentoMedida.ToString(tmp33);
    }
    if(__isset.quantidadeReceitada)
    {
      if(0 < tmp34++) { tmp33.Append(", "); }
      tmp33.Append("QuantidadeReceitada: ");
      QuantidadeReceitada.ToString(tmp33);
    }
    tmp33.Append(')');
    return tmp33.ToString();
  }
}

