/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Collections;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class FichaVacinacaoMasterThrift : TBase
{
  private int _tpCdsOrigem;
  private UnicaLotacaoHeaderThrift _headerTransport;
  private List<FichaVacinacaoChildThrift> _vacinacoes;

  public string UuidFicha { get; set; }

  public int TpCdsOrigem
  {
    get
    {
      return _tpCdsOrigem;
    }
    set
    {
      __isset.tpCdsOrigem = true;
      this._tpCdsOrigem = value;
    }
  }

  public UnicaLotacaoHeaderThrift HeaderTransport
  {
    get
    {
      return _headerTransport;
    }
    set
    {
      __isset.headerTransport = true;
      this._headerTransport = value;
    }
  }

  public List<FichaVacinacaoChildThrift> Vacinacoes
  {
    get
    {
      return _vacinacoes;
    }
    set
    {
      __isset.@vacinacoes = true;
      this._vacinacoes = value;
    }
  }


  public FichaVacinacaoMaster __isset;
  public struct FichaVacinacaoMaster
    {
    public bool tpCdsOrigem;
    public bool headerTransport;
    public bool @vacinacoes;
  }

  public FichaVacinacaoMasterThrift()
  {
  }

  public FichaVacinacaoMasterThrift(string uuidFicha) : this()
  {
    this.UuidFicha = uuidFicha;
  }

  public FichaVacinacaoMasterThrift DeepCopy()
  {
    var tmp14 = new FichaVacinacaoMasterThrift();
    if((UuidFicha != null))
    {
      tmp14.UuidFicha = this.UuidFicha;
    }
    if(__isset.tpCdsOrigem)
    {
      tmp14.TpCdsOrigem = this.TpCdsOrigem;
    }
    tmp14.__isset.tpCdsOrigem = this.__isset.tpCdsOrigem;
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp14.HeaderTransport = (UnicaLotacaoHeaderThrift)this.HeaderTransport.DeepCopy();
    }
    tmp14.__isset.headerTransport = this.__isset.headerTransport;
    if((Vacinacoes != null) && __isset.@vacinacoes)
    {
      tmp14.Vacinacoes = this.Vacinacoes.DeepCopy();
    }
    tmp14.__isset.@vacinacoes = this.__isset.@vacinacoes;
    return tmp14;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_uuidFicha = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              UuidFicha = await iprot.ReadStringAsync(cancellationToken);
              isset_uuidFicha = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I32)
            {
              TpCdsOrigem = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Struct)
            {
              HeaderTransport = new UnicaLotacaoHeaderThrift();
              await HeaderTransport.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.List)
            {
              {
                var _list15 = await iprot.ReadListBeginAsync(cancellationToken);
                Vacinacoes = new List<FichaVacinacaoChildThrift>(_list15.Count);
                for(int _i16 = 0; _i16 < _list15.Count; ++_i16)
                {
                  FichaVacinacaoChildThrift _elem17;
                  _elem17 = new FichaVacinacaoChildThrift();
                  await _elem17.ReadAsync(iprot, cancellationToken);
                  Vacinacoes.Add(_elem17);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_uuidFicha)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp18 = new TStruct("FichaVacinacaoMasterThrift");
      await oprot.WriteStructBeginAsync(tmp18, cancellationToken);
      var tmp19 = new TField();
      if((UuidFicha != null))
      {
        tmp19.Name = "uuidFicha";
        tmp19.Type = TType.String;
        tmp19.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
        await oprot.WriteStringAsync(UuidFicha, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.tpCdsOrigem)
      {
        tmp19.Name = "tpCdsOrigem";
        tmp19.Type = TType.I32;
        tmp19.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
        await oprot.WriteI32Async(TpCdsOrigem, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        tmp19.Name = "headerTransport";
        tmp19.Type = TType.Struct;
        tmp19.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
        await HeaderTransport.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Vacinacoes != null) && __isset.@vacinacoes)
      {
        tmp19.Name = "vacinacoes";
        tmp19.Type = TType.List;
        tmp19.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp19, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, Vacinacoes.Count), cancellationToken);
        foreach (FichaVacinacaoChildThrift _iter20 in Vacinacoes)
        {
          await _iter20.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FichaVacinacaoMasterThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(UuidFicha, other.UuidFicha)
      && ((__isset.tpCdsOrigem == other.__isset.tpCdsOrigem) && ((!__isset.tpCdsOrigem) || (global::System.Object.Equals(TpCdsOrigem, other.TpCdsOrigem))))
      && ((__isset.headerTransport == other.__isset.headerTransport) && ((!__isset.headerTransport) || (global::System.Object.Equals(HeaderTransport, other.HeaderTransport))))
      && ((__isset.@vacinacoes == other.__isset.@vacinacoes) && ((!__isset.@vacinacoes) || (TCollections.Equals(Vacinacoes, other.Vacinacoes))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((UuidFicha != null))
      {
        hashcode = (hashcode * 397) + UuidFicha.GetHashCode();
      }
      if(__isset.tpCdsOrigem)
      {
        hashcode = (hashcode * 397) + TpCdsOrigem.GetHashCode();
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        hashcode = (hashcode * 397) + HeaderTransport.GetHashCode();
      }
      if((Vacinacoes != null) && __isset.@vacinacoes)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Vacinacoes);
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp21 = new StringBuilder("FichaVacinacaoMasterThrift(");
    if((UuidFicha != null))
    {
      tmp21.Append(", UuidFicha: ");
      UuidFicha.ToString(tmp21);
    }
    if(__isset.tpCdsOrigem)
    {
      tmp21.Append(", TpCdsOrigem: ");
      TpCdsOrigem.ToString(tmp21);
    }
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp21.Append(", HeaderTransport: ");
      HeaderTransport.ToString(tmp21);
    }
    if((Vacinacoes != null) && __isset.@vacinacoes)
    {
      tmp21.Append(", Vacinacoes: ");
      Vacinacoes.ToString(tmp21);
    }
    tmp21.Append(')');
    return tmp21.ToString();
  }
}

