/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// Dados para identificar a instalacao que cadastrou/gerou os dados e/ou enviou
/// </summary>
public partial class DadoInstalacaoThrift : TBase
{
  private string _uuidInstalacao;
  private string _fone;
  private string _email;
  private string _versaoSistema;
  private string _nomeBancoDados;

  /// <summary>
  /// Identifica o software que gerou o dado (pec/cds, cdsOff ou software de terceiros).
  /// </summary>
  public string ContraChave { get; set; }

  /// <summary>
  /// É um identificador da instalação do software que gerou o dado. Seja ele o e-SUS ou software de terceiro.
  /// </summary>
  public string UuidInstalacao
  {
    get
    {
      return _uuidInstalacao;
    }
    set
    {
      __isset.uuidInstalacao = true;
      this._uuidInstalacao = value;
    }
  }

  /// <summary>
  /// Cpf do responsável ou CNPJ da empresa responsável
  /// </summary>
  public string CpfOuCnpj { get; set; }

  /// <summary>
  /// Nome do responsável ou Razão Social da empresa responsável
  /// </summary>
  public string NomeOuRazaoSocial { get; set; }

  /// <summary>
  /// Telefone da pessoa ou empresa responsável
  /// </summary>
  public string Fone
  {
    get
    {
      return _fone;
    }
    set
    {
      __isset.@fone = true;
      this._fone = value;
    }
  }

  /// <summary>
  /// Email da pessoa ou empresa responsável
  /// </summary>
  public string Email
  {
    get
    {
      return _email;
    }
    set
    {
      __isset.@email = true;
      this._email = value;
    }
  }

  /// <summary>
  /// Versão do software
  /// </summary>
  public string VersaoSistema
  {
    get
    {
      return _versaoSistema;
    }
    set
    {
      __isset.versaoSistema = true;
      this._versaoSistema = value;
    }
  }

  /// <summary>
  /// Nome do banco de dados que o software utiliza
  /// </summary>
  public string NomeBancoDados
  {
    get
    {
      return _nomeBancoDados;
    }
    set
    {
      __isset.nomeBancoDados = true;
      this._nomeBancoDados = value;
    }
  }


  public DadoInstalacao __isset;
  public struct DadoInstalacao
    {
    public bool uuidInstalacao;
    public bool @fone;
    public bool @email;
    public bool versaoSistema;
    public bool nomeBancoDados;
  }

  public DadoInstalacaoThrift()
  {
  }

  public DadoInstalacaoThrift(string contraChave, string cpfOuCnpj, string nomeOuRazaoSocial) : this()
  {
    this.ContraChave = contraChave;
    this.CpfOuCnpj = cpfOuCnpj;
    this.NomeOuRazaoSocial = nomeOuRazaoSocial;
  }

  public DadoInstalacaoThrift DeepCopy()
  {
    var tmp5 = new DadoInstalacaoThrift();
    if((ContraChave != null))
    {
      tmp5.ContraChave = this.ContraChave;
    }
    if((UuidInstalacao != null) && __isset.uuidInstalacao)
    {
      tmp5.UuidInstalacao = this.UuidInstalacao;
    }
    tmp5.__isset.uuidInstalacao = this.__isset.uuidInstalacao;
    if((CpfOuCnpj != null))
    {
      tmp5.CpfOuCnpj = this.CpfOuCnpj;
    }
    if((NomeOuRazaoSocial != null))
    {
      tmp5.NomeOuRazaoSocial = this.NomeOuRazaoSocial;
    }
    if((Fone != null) && __isset.@fone)
    {
      tmp5.Fone = this.Fone;
    }
    tmp5.__isset.@fone = this.__isset.@fone;
    if((Email != null) && __isset.@email)
    {
      tmp5.Email = this.Email;
    }
    tmp5.__isset.@email = this.__isset.@email;
    if((VersaoSistema != null) && __isset.versaoSistema)
    {
      tmp5.VersaoSistema = this.VersaoSistema;
    }
    tmp5.__isset.versaoSistema = this.__isset.versaoSistema;
    if((NomeBancoDados != null) && __isset.nomeBancoDados)
    {
      tmp5.NomeBancoDados = this.NomeBancoDados;
    }
    tmp5.__isset.nomeBancoDados = this.__isset.nomeBancoDados;
    return tmp5;
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_contraChave = false;
      bool isset_cpfOuCnpj = false;
      bool isset_nomeOuRazaoSocial = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              ContraChave = await iprot.ReadStringAsync(cancellationToken);
              isset_contraChave = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              UuidInstalacao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              CpfOuCnpj = await iprot.ReadStringAsync(cancellationToken);
              isset_cpfOuCnpj = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              NomeOuRazaoSocial = await iprot.ReadStringAsync(cancellationToken);
              isset_nomeOuRazaoSocial = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.String)
            {
              Fone = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.String)
            {
              Email = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.String)
            {
              VersaoSistema = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.String)
            {
              NomeBancoDados = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_contraChave)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_cpfOuCnpj)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_nomeOuRazaoSocial)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp6 = new TStruct("DadoInstalacaoThrift");
      await oprot.WriteStructBeginAsync(tmp6, cancellationToken);
      var tmp7 = new TField();
      if((ContraChave != null))
      {
        tmp7.Name = "contraChave";
        tmp7.Type = TType.String;
        tmp7.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(ContraChave, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((UuidInstalacao != null) && __isset.uuidInstalacao)
      {
        tmp7.Name = "uuidInstalacao";
        tmp7.Type = TType.String;
        tmp7.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(UuidInstalacao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CpfOuCnpj != null))
      {
        tmp7.Name = "cpfOuCnpj";
        tmp7.Type = TType.String;
        tmp7.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(CpfOuCnpj, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeOuRazaoSocial != null))
      {
        tmp7.Name = "nomeOuRazaoSocial";
        tmp7.Type = TType.String;
        tmp7.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NomeOuRazaoSocial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Fone != null) && __isset.@fone)
      {
        tmp7.Name = "fone";
        tmp7.Type = TType.String;
        tmp7.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Fone, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Email != null) && __isset.@email)
      {
        tmp7.Name = "email";
        tmp7.Type = TType.String;
        tmp7.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(Email, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((VersaoSistema != null) && __isset.versaoSistema)
      {
        tmp7.Name = "versaoSistema";
        tmp7.Type = TType.String;
        tmp7.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(VersaoSistema, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeBancoDados != null) && __isset.nomeBancoDados)
      {
        tmp7.Name = "nomeBancoDados";
        tmp7.Type = TType.String;
        tmp7.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
        await oprot.WriteStringAsync(NomeBancoDados, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is DadoInstalacaoThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(ContraChave, other.ContraChave)
      && ((__isset.uuidInstalacao == other.__isset.uuidInstalacao) && ((!__isset.uuidInstalacao) || (global::System.Object.Equals(UuidInstalacao, other.UuidInstalacao))))
      && global::System.Object.Equals(CpfOuCnpj, other.CpfOuCnpj)
      && global::System.Object.Equals(NomeOuRazaoSocial, other.NomeOuRazaoSocial)
      && ((__isset.@fone == other.__isset.@fone) && ((!__isset.@fone) || (global::System.Object.Equals(Fone, other.Fone))))
      && ((__isset.@email == other.__isset.@email) && ((!__isset.@email) || (global::System.Object.Equals(Email, other.Email))))
      && ((__isset.versaoSistema == other.__isset.versaoSistema) && ((!__isset.versaoSistema) || (global::System.Object.Equals(VersaoSistema, other.VersaoSistema))))
      && ((__isset.nomeBancoDados == other.__isset.nomeBancoDados) && ((!__isset.nomeBancoDados) || (global::System.Object.Equals(NomeBancoDados, other.NomeBancoDados))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((ContraChave != null))
      {
        hashcode = (hashcode * 397) + ContraChave.GetHashCode();
      }
      if((UuidInstalacao != null) && __isset.uuidInstalacao)
      {
        hashcode = (hashcode * 397) + UuidInstalacao.GetHashCode();
      }
      if((CpfOuCnpj != null))
      {
        hashcode = (hashcode * 397) + CpfOuCnpj.GetHashCode();
      }
      if((NomeOuRazaoSocial != null))
      {
        hashcode = (hashcode * 397) + NomeOuRazaoSocial.GetHashCode();
      }
      if((Fone != null) && __isset.@fone)
      {
        hashcode = (hashcode * 397) + Fone.GetHashCode();
      }
      if((Email != null) && __isset.@email)
      {
        hashcode = (hashcode * 397) + Email.GetHashCode();
      }
      if((VersaoSistema != null) && __isset.versaoSistema)
      {
        hashcode = (hashcode * 397) + VersaoSistema.GetHashCode();
      }
      if((NomeBancoDados != null) && __isset.nomeBancoDados)
      {
        hashcode = (hashcode * 397) + NomeBancoDados.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp8 = new StringBuilder("DadoInstalacaoThrift(");
    if((ContraChave != null))
    {
      tmp8.Append($", ContraChave: {ContraChave.ToString()}");
      ;
    }
    if((UuidInstalacao != null) && __isset.uuidInstalacao)
    {
      tmp8.Append($", UuidInstalacao: {UuidInstalacao.ToString()}");      
    }
    if((CpfOuCnpj != null))
    {
      tmp8.Append($", CpfOuCnpj: {CpfOuCnpj.ToString()}");
    }
    if((NomeOuRazaoSocial != null))
    {
      tmp8.Append($", NomeOuRazaoSocial: {NomeOuRazaoSocial.ToString()}");    
    }
    if((Fone != null) && __isset.@fone)
    {
      tmp8.Append($", Fone: {Fone.ToString()}");
    }
    if((Email != null) && __isset.@email)
    {
      tmp8.Append($", Email: {Email.ToString()}");
    }
    if((VersaoSistema != null) && __isset.versaoSistema)
    {
      tmp8.Append($", VersaoSistema: {VersaoSistema.ToString()}");
    }
    if((NomeBancoDados != null) && __isset.nomeBancoDados)
    {
      tmp8.Append($", NomeBancoDados: {NomeBancoDados.ToString()}");
    }
    tmp8.Append(')');
    return tmp8.ToString();
  }
}

