/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


/// <summary>
/// Indica a versão do dado a ser transportado. A versão do dado não necessariamente reflete a versão do sistema.
/// </summary>
public partial class VersaoThrift : TBase
{

  public int Major { get; set; }

  public int Minor { get; set; }

  public int Revision { get; set; }

  public VersaoThrift()
  {
  }

  public VersaoThrift(int @major, int @minor, int @revision) : this()
  {
    this.Major = @major;
    this.Minor = @minor;
    this.Revision = @revision;
  }

  public VersaoThrift DeepCopy()
  {
    var tmp0 = new VersaoThrift();
    tmp0.Major = this.Major;
    tmp0.Minor = this.Minor;
    tmp0.Revision = this.Revision;
    return tmp0;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_major = false;
      bool isset_minor = false;
      bool isset_revision = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32)
            {
              Major = await iprot.ReadI32Async(cancellationToken);
              isset_major = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I32)
            {
              Minor = await iprot.ReadI32Async(cancellationToken);
              isset_minor = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.I32)
            {
              Revision = await iprot.ReadI32Async(cancellationToken);
              isset_revision = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_major)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_minor)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      if (!isset_revision)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp1 = new TStruct("VersaoThrift");
      await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
      var tmp2 = new TField();
      tmp2.Name = "major";
      tmp2.Type = TType.I32;
      tmp2.ID = 1;
      await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
      await oprot.WriteI32Async(Major, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      tmp2.Name = "minor";
      tmp2.Type = TType.I32;
      tmp2.ID = 2;
      await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
      await oprot.WriteI32Async(Minor, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      tmp2.Name = "revision";
      tmp2.Type = TType.I32;
      tmp2.ID = 3;
      await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
      await oprot.WriteI32Async(Revision, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is VersaoThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(Major, other.Major)
      && global::System.Object.Equals(Minor, other.Minor)
      && global::System.Object.Equals(Revision, other.Revision);
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      hashcode = (hashcode * 397) + Major.GetHashCode();
      hashcode = (hashcode * 397) + Minor.GetHashCode();
      hashcode = (hashcode * 397) + Revision.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp3 = new StringBuilder("VersaoThrift(");
    tmp3.Append($", Major: {Major.ToString()}");
    tmp3.Append($", Minor: {Minor.ToString()}");
    tmp3.Append($", Revision: {Revision.ToString()}");
    tmp3.Append(')');
    return tmp3.ToString();
  }
}

