/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Collections;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class FichaVacinacaoChildThrift : TBase
{
  private long _turno;
  private string _numProntuario;
  private string _cnsCidadao;
  private long _dtNascimento;
  private long _sexo;
  private long _localAtendimento;
  private bool _viajante;
  private bool _comunicanteHanseniase;
  private bool _gestante;
  private bool _puerpera;
  private List<VacinaRowThrift> _vacinas;
  private long _dataHoraInicialAtendimento;
  private long _dataHoraFinalAtendimento;
  private string _cpfCidadao;

  public long Turno
  {
    get
    {
      return _turno;
    }
    set
    {
      __isset.@turno = true;
      this._turno = value;
    }
  }

  public string NumProntuario
  {
    get
    {
      return _numProntuario;
    }
    set
    {
      __isset.numProntuario = true;
      this._numProntuario = value;
    }
  }

  public string CnsCidadao
  {
    get
    {
      return _cnsCidadao;
    }
    set
    {
      __isset.cnsCidadao = true;
      this._cnsCidadao = value;
    }
  }

  public long DtNascimento
  {
    get
    {
      return _dtNascimento;
    }
    set
    {
      __isset.dtNascimento = true;
      this._dtNascimento = value;
    }
  }

  public long Sexo
  {
    get
    {
      return _sexo;
    }
    set
    {
      __isset.@sexo = true;
      this._sexo = value;
    }
  }

  public long LocalAtendimento
  {
    get
    {
      return _localAtendimento;
    }
    set
    {
      __isset.localAtendimento = true;
      this._localAtendimento = value;
    }
  }

  public bool Viajante
  {
    get
    {
      return _viajante;
    }
    set
    {
      __isset.@viajante = true;
      this._viajante = value;
    }
  }

  public bool ComunicanteHanseniase
  {
    get
    {
      return _comunicanteHanseniase;
    }
    set
    {
      __isset.comunicanteHanseniase = true;
      this._comunicanteHanseniase = value;
    }
  }

  public bool Gestante
  {
    get
    {
      return _gestante;
    }
    set
    {
      __isset.@gestante = true;
      this._gestante = value;
    }
  }

  public bool Puerpera
  {
    get
    {
      return _puerpera;
    }
    set
    {
      __isset.@puerpera = true;
      this._puerpera = value;
    }
  }

  public List<VacinaRowThrift> Vacinas
  {
    get
    {
      return _vacinas;
    }
    set
    {
      __isset.@vacinas = true;
      this._vacinas = value;
    }
  }

  public long DataHoraInicialAtendimento
  {
    get
    {
      return _dataHoraInicialAtendimento;
    }
    set
    {
      __isset.dataHoraInicialAtendimento = true;
      this._dataHoraInicialAtendimento = value;
    }
  }

  public long DataHoraFinalAtendimento
  {
    get
    {
      return _dataHoraFinalAtendimento;
    }
    set
    {
      __isset.dataHoraFinalAtendimento = true;
      this._dataHoraFinalAtendimento = value;
    }
  }

  public string CpfCidadao
  {
    get
    {
      return _cpfCidadao;
    }
    set
    {
      __isset.cpfCidadao = true;
      this._cpfCidadao = value;
    }
  }


  public FichaVacinacaoChild __isset;
  public struct FichaVacinacaoChild
    {
    public bool @turno;
    public bool numProntuario;
    public bool cnsCidadao;
    public bool dtNascimento;
    public bool @sexo;
    public bool localAtendimento;
    public bool @viajante;
    public bool comunicanteHanseniase;
    public bool @gestante;
    public bool @puerpera;
    public bool @vacinas;
    public bool dataHoraInicialAtendimento;
    public bool dataHoraFinalAtendimento;
    public bool cpfCidadao;
  }

  public FichaVacinacaoChildThrift()
  {
  }

  public FichaVacinacaoChildThrift DeepCopy()
  {
    var tmp5 = new FichaVacinacaoChildThrift();
    if(__isset.@turno)
    {
      tmp5.Turno = this.Turno;
    }
    tmp5.__isset.@turno = this.__isset.@turno;
    if((NumProntuario != null) && __isset.numProntuario)
    {
      tmp5.NumProntuario = this.NumProntuario;
    }
    tmp5.__isset.numProntuario = this.__isset.numProntuario;
    if((CnsCidadao != null) && __isset.cnsCidadao)
    {
      tmp5.CnsCidadao = this.CnsCidadao;
    }
    tmp5.__isset.cnsCidadao = this.__isset.cnsCidadao;
    if(__isset.dtNascimento)
    {
      tmp5.DtNascimento = this.DtNascimento;
    }
    tmp5.__isset.dtNascimento = this.__isset.dtNascimento;
    if(__isset.@sexo)
    {
      tmp5.Sexo = this.Sexo;
    }
    tmp5.__isset.@sexo = this.__isset.@sexo;
    if(__isset.localAtendimento)
    {
      tmp5.LocalAtendimento = this.LocalAtendimento;
    }
    tmp5.__isset.localAtendimento = this.__isset.localAtendimento;
    if(__isset.@viajante)
    {
      tmp5.Viajante = this.Viajante;
    }
    tmp5.__isset.@viajante = this.__isset.@viajante;
    if(__isset.comunicanteHanseniase)
    {
      tmp5.ComunicanteHanseniase = this.ComunicanteHanseniase;
    }
    tmp5.__isset.comunicanteHanseniase = this.__isset.comunicanteHanseniase;
    if(__isset.@gestante)
    {
      tmp5.Gestante = this.Gestante;
    }
    tmp5.__isset.@gestante = this.__isset.@gestante;
    if(__isset.@puerpera)
    {
      tmp5.Puerpera = this.Puerpera;
    }
    tmp5.__isset.@puerpera = this.__isset.@puerpera;
    if((Vacinas != null) && __isset.@vacinas)
    {
      tmp5.Vacinas = this.Vacinas.DeepCopy();
    }
    tmp5.__isset.@vacinas = this.__isset.@vacinas;
    if(__isset.dataHoraInicialAtendimento)
    {
      tmp5.DataHoraInicialAtendimento = this.DataHoraInicialAtendimento;
    }
    tmp5.__isset.dataHoraInicialAtendimento = this.__isset.dataHoraInicialAtendimento;
    if(__isset.dataHoraFinalAtendimento)
    {
      tmp5.DataHoraFinalAtendimento = this.DataHoraFinalAtendimento;
    }
    tmp5.__isset.dataHoraFinalAtendimento = this.__isset.dataHoraFinalAtendimento;
    if((CpfCidadao != null) && __isset.cpfCidadao)
    {
      tmp5.CpfCidadao = this.CpfCidadao;
    }
    tmp5.__isset.cpfCidadao = this.__isset.cpfCidadao;
    return tmp5;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64)
            {
              Turno = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              NumProntuario = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              CnsCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I64)
            {
              DtNascimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.I64)
            {
              Sexo = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.I64)
            {
              LocalAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.Bool)
            {
              Viajante = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.Bool)
            {
              ComunicanteHanseniase = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.Bool)
            {
              Gestante = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.Bool)
            {
              Puerpera = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.List)
            {
              {
                var _list6 = await iprot.ReadListBeginAsync(cancellationToken);
                Vacinas = new List<VacinaRowThrift>(_list6.Count);
                for(int _i7 = 0; _i7 < _list6.Count; ++_i7)
                {
                  VacinaRowThrift _elem8;
                  _elem8 = new VacinaRowThrift();
                  await _elem8.ReadAsync(iprot, cancellationToken);
                  Vacinas.Add(_elem8);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.I64)
            {
              DataHoraInicialAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.I64)
            {
              DataHoraFinalAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 14:
            if (field.Type == TType.String)
            {
              CpfCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp9 = new TStruct("FichaVacinacaoChildThrift");
      await oprot.WriteStructBeginAsync(tmp9, cancellationToken);
      var tmp10 = new TField();
      if(__isset.@turno)
      {
        tmp10.Name = "turno";
        tmp10.Type = TType.I64;
        tmp10.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteI64Async(Turno, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NumProntuario != null) && __isset.numProntuario)
      {
        tmp10.Name = "numProntuario";
        tmp10.Type = TType.String;
        tmp10.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteStringAsync(NumProntuario, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CnsCidadao != null) && __isset.cnsCidadao)
      {
        tmp10.Name = "cnsCidadao";
        tmp10.Type = TType.String;
        tmp10.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteStringAsync(CnsCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dtNascimento)
      {
        tmp10.Name = "dtNascimento";
        tmp10.Type = TType.I64;
        tmp10.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteI64Async(DtNascimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@sexo)
      {
        tmp10.Name = "sexo";
        tmp10.Type = TType.I64;
        tmp10.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteI64Async(Sexo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.localAtendimento)
      {
        tmp10.Name = "localAtendimento";
        tmp10.Type = TType.I64;
        tmp10.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteI64Async(LocalAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@viajante)
      {
        tmp10.Name = "viajante";
        tmp10.Type = TType.Bool;
        tmp10.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteBoolAsync(Viajante, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.comunicanteHanseniase)
      {
        tmp10.Name = "comunicanteHanseniase";
        tmp10.Type = TType.Bool;
        tmp10.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteBoolAsync(ComunicanteHanseniase, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@gestante)
      {
        tmp10.Name = "gestante";
        tmp10.Type = TType.Bool;
        tmp10.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteBoolAsync(Gestante, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@puerpera)
      {
        tmp10.Name = "puerpera";
        tmp10.Type = TType.Bool;
        tmp10.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteBoolAsync(Puerpera, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Vacinas != null) && __isset.@vacinas)
      {
        tmp10.Name = "vacinas";
        tmp10.Type = TType.List;
        tmp10.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, Vacinas.Count), cancellationToken);
        foreach (VacinaRowThrift _iter11 in Vacinas)
        {
          await _iter11.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataHoraInicialAtendimento)
      {
        tmp10.Name = "dataHoraInicialAtendimento";
        tmp10.Type = TType.I64;
        tmp10.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteI64Async(DataHoraInicialAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataHoraFinalAtendimento)
      {
        tmp10.Name = "dataHoraFinalAtendimento";
        tmp10.Type = TType.I64;
        tmp10.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteI64Async(DataHoraFinalAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CpfCidadao != null) && __isset.cpfCidadao)
      {
        tmp10.Name = "cpfCidadao";
        tmp10.Type = TType.String;
        tmp10.ID = 14;
        await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
        await oprot.WriteStringAsync(CpfCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FichaVacinacaoChildThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.@turno == other.__isset.@turno) && ((!__isset.@turno) || (global::System.Object.Equals(Turno, other.Turno))))
      && ((__isset.numProntuario == other.__isset.numProntuario) && ((!__isset.numProntuario) || (global::System.Object.Equals(NumProntuario, other.NumProntuario))))
      && ((__isset.cnsCidadao == other.__isset.cnsCidadao) && ((!__isset.cnsCidadao) || (global::System.Object.Equals(CnsCidadao, other.CnsCidadao))))
      && ((__isset.dtNascimento == other.__isset.dtNascimento) && ((!__isset.dtNascimento) || (global::System.Object.Equals(DtNascimento, other.DtNascimento))))
      && ((__isset.@sexo == other.__isset.@sexo) && ((!__isset.@sexo) || (global::System.Object.Equals(Sexo, other.Sexo))))
      && ((__isset.localAtendimento == other.__isset.localAtendimento) && ((!__isset.localAtendimento) || (global::System.Object.Equals(LocalAtendimento, other.LocalAtendimento))))
      && ((__isset.@viajante == other.__isset.@viajante) && ((!__isset.@viajante) || (global::System.Object.Equals(Viajante, other.Viajante))))
      && ((__isset.comunicanteHanseniase == other.__isset.comunicanteHanseniase) && ((!__isset.comunicanteHanseniase) || (global::System.Object.Equals(ComunicanteHanseniase, other.ComunicanteHanseniase))))
      && ((__isset.@gestante == other.__isset.@gestante) && ((!__isset.@gestante) || (global::System.Object.Equals(Gestante, other.Gestante))))
      && ((__isset.@puerpera == other.__isset.@puerpera) && ((!__isset.@puerpera) || (global::System.Object.Equals(Puerpera, other.Puerpera))))
      && ((__isset.@vacinas == other.__isset.@vacinas) && ((!__isset.@vacinas) || (TCollections.Equals(Vacinas, other.Vacinas))))
      && ((__isset.dataHoraInicialAtendimento == other.__isset.dataHoraInicialAtendimento) && ((!__isset.dataHoraInicialAtendimento) || (global::System.Object.Equals(DataHoraInicialAtendimento, other.DataHoraInicialAtendimento))))
      && ((__isset.dataHoraFinalAtendimento == other.__isset.dataHoraFinalAtendimento) && ((!__isset.dataHoraFinalAtendimento) || (global::System.Object.Equals(DataHoraFinalAtendimento, other.DataHoraFinalAtendimento))))
      && ((__isset.cpfCidadao == other.__isset.cpfCidadao) && ((!__isset.cpfCidadao) || (global::System.Object.Equals(CpfCidadao, other.CpfCidadao))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.@turno)
      {
        hashcode = (hashcode * 397) + Turno.GetHashCode();
      }
      if((NumProntuario != null) && __isset.numProntuario)
      {
        hashcode = (hashcode * 397) + NumProntuario.GetHashCode();
      }
      if((CnsCidadao != null) && __isset.cnsCidadao)
      {
        hashcode = (hashcode * 397) + CnsCidadao.GetHashCode();
      }
      if(__isset.dtNascimento)
      {
        hashcode = (hashcode * 397) + DtNascimento.GetHashCode();
      }
      if(__isset.@sexo)
      {
        hashcode = (hashcode * 397) + Sexo.GetHashCode();
      }
      if(__isset.localAtendimento)
      {
        hashcode = (hashcode * 397) + LocalAtendimento.GetHashCode();
      }
      if(__isset.@viajante)
      {
        hashcode = (hashcode * 397) + Viajante.GetHashCode();
      }
      if(__isset.comunicanteHanseniase)
      {
        hashcode = (hashcode * 397) + ComunicanteHanseniase.GetHashCode();
      }
      if(__isset.@gestante)
      {
        hashcode = (hashcode * 397) + Gestante.GetHashCode();
      }
      if(__isset.@puerpera)
      {
        hashcode = (hashcode * 397) + Puerpera.GetHashCode();
      }
      if((Vacinas != null) && __isset.@vacinas)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Vacinas);
      }
      if(__isset.dataHoraInicialAtendimento)
      {
        hashcode = (hashcode * 397) + DataHoraInicialAtendimento.GetHashCode();
      }
      if(__isset.dataHoraFinalAtendimento)
      {
        hashcode = (hashcode * 397) + DataHoraFinalAtendimento.GetHashCode();
      }
      if((CpfCidadao != null) && __isset.cpfCidadao)
      {
        hashcode = (hashcode * 397) + CpfCidadao.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp12 = new StringBuilder("FichaVacinacaoChildThrift(");
    int tmp13 = 0;
    if(__isset.@turno)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("Turno: ");
      Turno.ToString(tmp12);
    }
    if((NumProntuario != null) && __isset.numProntuario)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("NumProntuario: ");
      NumProntuario.ToString(tmp12);
    }
    if((CnsCidadao != null) && __isset.cnsCidadao)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("CnsCidadao: ");
      CnsCidadao.ToString(tmp12);
    }
    if(__isset.dtNascimento)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("DtNascimento: ");
      DtNascimento.ToString(tmp12);
    }
    if(__isset.@sexo)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("Sexo: ");
      Sexo.ToString(tmp12);
    }
    if(__isset.localAtendimento)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("LocalAtendimento: ");
      LocalAtendimento.ToString(tmp12);
    }
    if(__isset.@viajante)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("Viajante: ");
      Viajante.ToString(tmp12);
    }
    if(__isset.comunicanteHanseniase)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("ComunicanteHanseniase: ");
      ComunicanteHanseniase.ToString(tmp12);
    }
    if(__isset.@gestante)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("Gestante: ");
      Gestante.ToString(tmp12);
    }
    if(__isset.@puerpera)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("Puerpera: ");
      Puerpera.ToString(tmp12);
    }
    if((Vacinas != null) && __isset.@vacinas)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("Vacinas: ");
      Vacinas.ToString(tmp12);
    }
    if(__isset.dataHoraInicialAtendimento)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("DataHoraInicialAtendimento: ");
      DataHoraInicialAtendimento.ToString(tmp12);
    }
    if(__isset.dataHoraFinalAtendimento)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("DataHoraFinalAtendimento: ");
      DataHoraFinalAtendimento.ToString(tmp12);
    }
    if((CpfCidadao != null) && __isset.cpfCidadao)
    {
      if(0 < tmp13++) { tmp12.Append(", "); }
      tmp12.Append("CpfCidadao: ");
      CpfCidadao.ToString(tmp12);
    }
    tmp12.Append(')');
    return tmp12.ToString();
  }
}

