/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class VacinaRowThrift : TBase
{
  private long _imunobiologico;
  private long _estrategiaVacinacao;
  private long _dose;
  private string _lote;
  private string _fabricante;
  private long _grupoAtendimento;
  private bool _stRegistroAnterior;
  private long _dataRegistroAnterior;
  private bool _stAplicadoExterior;

  public long Imunobiologico
  {
    get
    {
      return _imunobiologico;
    }
    set
    {
      __isset.@imunobiologico = true;
      this._imunobiologico = value;
    }
  }

  public long EstrategiaVacinacao
  {
    get
    {
      return _estrategiaVacinacao;
    }
    set
    {
      __isset.estrategiaVacinacao = true;
      this._estrategiaVacinacao = value;
    }
  }

  public long Dose
  {
    get
    {
      return _dose;
    }
    set
    {
      __isset.@dose = true;
      this._dose = value;
    }
  }

  public string Lote
  {
    get
    {
      return _lote;
    }
    set
    {
      __isset.@lote = true;
      this._lote = value;
    }
  }

  public string Fabricante
  {
    get
    {
      return _fabricante;
    }
    set
    {
      __isset.@fabricante = true;
      this._fabricante = value;
    }
  }

  public long GrupoAtendimento
  {
    get
    {
      return _grupoAtendimento;
    }
    set
    {
      __isset.grupoAtendimento = true;
      this._grupoAtendimento = value;
    }
  }

  public bool StRegistroAnterior
  {
    get
    {
      return _stRegistroAnterior;
    }
    set
    {
      __isset.stRegistroAnterior = true;
      this._stRegistroAnterior = value;
    }
  }

  public long DataRegistroAnterior
  {
    get
    {
      return _dataRegistroAnterior;
    }
    set
    {
      __isset.dataRegistroAnterior = true;
      this._dataRegistroAnterior = value;
    }
  }

  public bool StAplicadoExterior
  {
    get
    {
      return _stAplicadoExterior;
    }
    set
    {
      __isset.stAplicadoExterior = true;
      this._stAplicadoExterior = value;
    }
  }


  public VacinaRow __isset;
  public struct VacinaRow
    {
    public bool @imunobiologico;
    public bool estrategiaVacinacao;
    public bool @dose;
    public bool @lote;
    public bool @fabricante;
    public bool grupoAtendimento;
    public bool stRegistroAnterior;
    public bool dataRegistroAnterior;
    public bool stAplicadoExterior;
  }

  public VacinaRowThrift()
  {
  }

  public VacinaRowThrift DeepCopy()
  {
    var tmp0 = new VacinaRowThrift();
    if(__isset.@imunobiologico)
    {
      tmp0.Imunobiologico = this.Imunobiologico;
    }
    tmp0.__isset.@imunobiologico = this.__isset.@imunobiologico;
    if(__isset.estrategiaVacinacao)
    {
      tmp0.EstrategiaVacinacao = this.EstrategiaVacinacao;
    }
    tmp0.__isset.estrategiaVacinacao = this.__isset.estrategiaVacinacao;
    if(__isset.@dose)
    {
      tmp0.Dose = this.Dose;
    }
    tmp0.__isset.@dose = this.__isset.@dose;
    if((Lote != null) && __isset.@lote)
    {
      tmp0.Lote = this.Lote;
    }
    tmp0.__isset.@lote = this.__isset.@lote;
    if((Fabricante != null) && __isset.@fabricante)
    {
      tmp0.Fabricante = this.Fabricante;
    }
    tmp0.__isset.@fabricante = this.__isset.@fabricante;
    if(__isset.grupoAtendimento)
    {
      tmp0.GrupoAtendimento = this.GrupoAtendimento;
    }
    tmp0.__isset.grupoAtendimento = this.__isset.grupoAtendimento;
    if(__isset.stRegistroAnterior)
    {
      tmp0.StRegistroAnterior = this.StRegistroAnterior;
    }
    tmp0.__isset.stRegistroAnterior = this.__isset.stRegistroAnterior;
    if(__isset.dataRegistroAnterior)
    {
      tmp0.DataRegistroAnterior = this.DataRegistroAnterior;
    }
    tmp0.__isset.dataRegistroAnterior = this.__isset.dataRegistroAnterior;
    if(__isset.stAplicadoExterior)
    {
      tmp0.StAplicadoExterior = this.StAplicadoExterior;
    }
    tmp0.__isset.stAplicadoExterior = this.__isset.stAplicadoExterior;
    return tmp0;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64)
            {
              Imunobiologico = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              EstrategiaVacinacao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.I64)
            {
              Dose = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              Lote = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.String)
            {
              Fabricante = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.I64)
            {
              GrupoAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.Bool)
            {
              StRegistroAnterior = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.I64)
            {
              DataRegistroAnterior = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.Bool)
            {
              StAplicadoExterior = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp1 = new TStruct("VacinaRowThrift");
      await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
      var tmp2 = new TField();
      if(__isset.@imunobiologico)
      {
        tmp2.Name = "imunobiologico";
        tmp2.Type = TType.I64;
        tmp2.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(Imunobiologico, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.estrategiaVacinacao)
      {
        tmp2.Name = "estrategiaVacinacao";
        tmp2.Type = TType.I64;
        tmp2.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(EstrategiaVacinacao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@dose)
      {
        tmp2.Name = "dose";
        tmp2.Type = TType.I64;
        tmp2.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(Dose, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Lote != null) && __isset.@lote)
      {
        tmp2.Name = "lote";
        tmp2.Type = TType.String;
        tmp2.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(Lote, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Fabricante != null) && __isset.@fabricante)
      {
        tmp2.Name = "fabricante";
        tmp2.Type = TType.String;
        tmp2.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(Fabricante, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.grupoAtendimento)
      {
        tmp2.Name = "grupoAtendimento";
        tmp2.Type = TType.I64;
        tmp2.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(GrupoAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.stRegistroAnterior)
      {
        tmp2.Name = "stRegistroAnterior";
        tmp2.Type = TType.Bool;
        tmp2.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteBoolAsync(StRegistroAnterior, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataRegistroAnterior)
      {
        tmp2.Name = "dataRegistroAnterior";
        tmp2.Type = TType.I64;
        tmp2.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(DataRegistroAnterior, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.stAplicadoExterior)
      {
        tmp2.Name = "stAplicadoExterior";
        tmp2.Type = TType.Bool;
        tmp2.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteBoolAsync(StAplicadoExterior, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is VacinaRowThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.@imunobiologico == other.__isset.@imunobiologico) && ((!__isset.@imunobiologico) || (global::System.Object.Equals(Imunobiologico, other.Imunobiologico))))
      && ((__isset.estrategiaVacinacao == other.__isset.estrategiaVacinacao) && ((!__isset.estrategiaVacinacao) || (global::System.Object.Equals(EstrategiaVacinacao, other.EstrategiaVacinacao))))
      && ((__isset.@dose == other.__isset.@dose) && ((!__isset.@dose) || (global::System.Object.Equals(Dose, other.Dose))))
      && ((__isset.@lote == other.__isset.@lote) && ((!__isset.@lote) || (global::System.Object.Equals(Lote, other.Lote))))
      && ((__isset.@fabricante == other.__isset.@fabricante) && ((!__isset.@fabricante) || (global::System.Object.Equals(Fabricante, other.Fabricante))))
      && ((__isset.grupoAtendimento == other.__isset.grupoAtendimento) && ((!__isset.grupoAtendimento) || (global::System.Object.Equals(GrupoAtendimento, other.GrupoAtendimento))))
      && ((__isset.stRegistroAnterior == other.__isset.stRegistroAnterior) && ((!__isset.stRegistroAnterior) || (global::System.Object.Equals(StRegistroAnterior, other.StRegistroAnterior))))
      && ((__isset.dataRegistroAnterior == other.__isset.dataRegistroAnterior) && ((!__isset.dataRegistroAnterior) || (global::System.Object.Equals(DataRegistroAnterior, other.DataRegistroAnterior))))
      && ((__isset.stAplicadoExterior == other.__isset.stAplicadoExterior) && ((!__isset.stAplicadoExterior) || (global::System.Object.Equals(StAplicadoExterior, other.StAplicadoExterior))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.@imunobiologico)
      {
        hashcode = (hashcode * 397) + Imunobiologico.GetHashCode();
      }
      if(__isset.estrategiaVacinacao)
      {
        hashcode = (hashcode * 397) + EstrategiaVacinacao.GetHashCode();
      }
      if(__isset.@dose)
      {
        hashcode = (hashcode * 397) + Dose.GetHashCode();
      }
      if((Lote != null) && __isset.@lote)
      {
        hashcode = (hashcode * 397) + Lote.GetHashCode();
      }
      if((Fabricante != null) && __isset.@fabricante)
      {
        hashcode = (hashcode * 397) + Fabricante.GetHashCode();
      }
      if(__isset.grupoAtendimento)
      {
        hashcode = (hashcode * 397) + GrupoAtendimento.GetHashCode();
      }
      if(__isset.stRegistroAnterior)
      {
        hashcode = (hashcode * 397) + StRegistroAnterior.GetHashCode();
      }
      if(__isset.dataRegistroAnterior)
      {
        hashcode = (hashcode * 397) + DataRegistroAnterior.GetHashCode();
      }
      if(__isset.stAplicadoExterior)
      {
        hashcode = (hashcode * 397) + StAplicadoExterior.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp3 = new StringBuilder("VacinaRowThrift(");
    int tmp4 = 0;
    if(__isset.@imunobiologico)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Imunobiologico: ");
      Imunobiologico.ToString(tmp3);
    }
    if(__isset.estrategiaVacinacao)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("EstrategiaVacinacao: ");
      EstrategiaVacinacao.ToString(tmp3);
    }
    if(__isset.@dose)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Dose: ");
      Dose.ToString(tmp3);
    }
    if((Lote != null) && __isset.@lote)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Lote: ");
      Lote.ToString(tmp3);
    }
    if((Fabricante != null) && __isset.@fabricante)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Fabricante: ");
      Fabricante.ToString(tmp3);
    }
    if(__isset.grupoAtendimento)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("GrupoAtendimento: ");
      GrupoAtendimento.ToString(tmp3);
    }
    if(__isset.stRegistroAnterior)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("StRegistroAnterior: ");
      StRegistroAnterior.ToString(tmp3);
    }
    if(__isset.dataRegistroAnterior)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("DataRegistroAnterior: ");
      DataRegistroAnterior.ToString(tmp3);
    }
    if(__isset.stAplicadoExterior)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("StAplicadoExterior: ");
      StAplicadoExterior.ToString(tmp3);
    }
    tmp3.Append(')');
    return tmp3.ToString();
  }
}

