/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System.Text;
using Encore.Domain.Core.Extensions;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class InformacoesSocioEconomicasThrift : TBase
{
  private bool _alimentosAcabaramAntesTerDinheiroComprarMais;
  private bool _comeuAlgunsAlimentosQueTinhaDinheiroAcabou;

  public bool AlimentosAcabaramAntesTerDinheiroComprarMais
  {
    get
    {
      return _alimentosAcabaramAntesTerDinheiroComprarMais;
    }
    set
    {
      __isset.alimentosAcabaramAntesTerDinheiroComprarMais = true;
      this._alimentosAcabaramAntesTerDinheiroComprarMais = value;
    }
  }

  public bool ComeuAlgunsAlimentosQueTinhaDinheiroAcabou
  {
    get
    {
      return _comeuAlgunsAlimentosQueTinhaDinheiroAcabou;
    }
    set
    {
      __isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou = true;
      this._comeuAlgunsAlimentosQueTinhaDinheiroAcabou = value;
    }
  }


  public InformacoesSocioEconomicas __isset;
  public struct InformacoesSocioEconomicas
    {
    public bool alimentosAcabaramAntesTerDinheiroComprarMais;
    public bool comeuAlgunsAlimentosQueTinhaDinheiroAcabou;
  }

  public InformacoesSocioEconomicasThrift()
  {
  }

  public InformacoesSocioEconomicasThrift DeepCopy()
  {
    var tmp48 = new InformacoesSocioEconomicasThrift();
    if(__isset.alimentosAcabaramAntesTerDinheiroComprarMais)
    {
      tmp48.AlimentosAcabaramAntesTerDinheiroComprarMais = this.AlimentosAcabaramAntesTerDinheiroComprarMais;
    }
    tmp48.__isset.alimentosAcabaramAntesTerDinheiroComprarMais = this.__isset.alimentosAcabaramAntesTerDinheiroComprarMais;
    if(__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou)
    {
      tmp48.ComeuAlgunsAlimentosQueTinhaDinheiroAcabou = this.ComeuAlgunsAlimentosQueTinhaDinheiroAcabou;
    }
    tmp48.__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou = this.__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou;
    return tmp48;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool)
            {
              AlimentosAcabaramAntesTerDinheiroComprarMais = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Bool)
            {
              ComeuAlgunsAlimentosQueTinhaDinheiroAcabou = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp49 = new TStruct("InformacoesSocioEconomicasThrift");
      await oprot.WriteStructBeginAsync(tmp49, cancellationToken);
      var tmp50 = new TField();
      if(__isset.alimentosAcabaramAntesTerDinheiroComprarMais)
      {
        tmp50.Name = "alimentosAcabaramAntesTerDinheiroComprarMais";
        tmp50.Type = TType.Bool;
        tmp50.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp50, cancellationToken);
        await oprot.WriteBoolAsync(AlimentosAcabaramAntesTerDinheiroComprarMais, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou)
      {
        tmp50.Name = "comeuAlgunsAlimentosQueTinhaDinheiroAcabou";
        tmp50.Type = TType.Bool;
        tmp50.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp50, cancellationToken);
        await oprot.WriteBoolAsync(ComeuAlgunsAlimentosQueTinhaDinheiroAcabou, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is InformacoesSocioEconomicasThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.alimentosAcabaramAntesTerDinheiroComprarMais == other.__isset.alimentosAcabaramAntesTerDinheiroComprarMais) && ((!__isset.alimentosAcabaramAntesTerDinheiroComprarMais) || (global::System.Object.Equals(AlimentosAcabaramAntesTerDinheiroComprarMais, other.AlimentosAcabaramAntesTerDinheiroComprarMais))))
      && ((__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou == other.__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou) && ((!__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou) || (global::System.Object.Equals(ComeuAlgunsAlimentosQueTinhaDinheiroAcabou, other.ComeuAlgunsAlimentosQueTinhaDinheiroAcabou))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.alimentosAcabaramAntesTerDinheiroComprarMais)
      {
        hashcode = (hashcode * 397) + AlimentosAcabaramAntesTerDinheiroComprarMais.GetHashCode();
      }
      if(__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou)
      {
        hashcode = (hashcode * 397) + ComeuAlgunsAlimentosQueTinhaDinheiroAcabou.GetHashCode();
      }
    }
    return hashcode;
  }    

  public override string ToString()
  {
    var tmp51 = new StringBuilder("InformacoesSocioEconomicasThrift(");
    int tmp52 = 0;
    if(__isset.alimentosAcabaramAntesTerDinheiroComprarMais)
    {
      if(0 < tmp52++) { tmp51.Append(", "); }
      tmp51.Append("AlimentosAcabaramAntesTerDinheiroComprarMais: ");
      AlimentosAcabaramAntesTerDinheiroComprarMais.ToString(tmp51);
    }
    if(__isset.comeuAlgunsAlimentosQueTinhaDinheiroAcabou)
    {
      if(0 < tmp52++) { tmp51.Append(", "); }
      tmp51.Append("ComeuAlgunsAlimentosQueTinhaDinheiroAcabou: ");
      ComeuAlgunsAlimentosQueTinhaDinheiroAcabou.ToString(tmp51);
    }
    tmp51.Append(')');
    return tmp51.ToString();
  }
}

