/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Collections;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class InformacoesSocioDemograficasThrift : TBase
{
  private List<long> _deficienciasCidadao;
  private long _grauInstrucaoCidadao;
  private string _ocupacaoCodigoCbo2002;
  private long _orientacaoSexualCidadao;
  private long _relacaoParentescoCidadao;
  private long _situacaoMercadoTrabalhoCidadao;
  private bool _statusDesejaInformarOrientacaoSexual;
  private bool _statusFrequentaBenzedeira;
  private bool _statusFrequentaEscola;
  private bool _statusMembroPovoComunidadeTradicional;
  private bool _statusParticipaGrupoComunitario;
  private bool _statusPossuiPlanoSaudePrivado;
  private bool _statusTemAlgumaDeficiencia;
  private long _identidadeGeneroCidadao;
  private bool _statusDesejaInformarIdentidadeGenero;
  private List<long> _responsavelPorCrianca;
  private long _coPovoComunidadeTradicional;

  public List<long> DeficienciasCidadao
  {
    get
    {
      return _deficienciasCidadao;
    }
    set
    {
      __isset.deficienciasCidadao = true;
      this._deficienciasCidadao = value;
    }
  }

  public long GrauInstrucaoCidadao
  {
    get
    {
      return _grauInstrucaoCidadao;
    }
    set
    {
      __isset.grauInstrucaoCidadao = true;
      this._grauInstrucaoCidadao = value;
    }
  }

  public string OcupacaoCodigoCbo2002
  {
    get
    {
      return _ocupacaoCodigoCbo2002;
    }
    set
    {
      __isset.ocupacaoCodigoCbo2002 = true;
      this._ocupacaoCodigoCbo2002 = value;
    }
  }

  public long OrientacaoSexualCidadao
  {
    get
    {
      return _orientacaoSexualCidadao;
    }
    set
    {
      __isset.orientacaoSexualCidadao = true;
      this._orientacaoSexualCidadao = value;
    }
  }

  public long RelacaoParentescoCidadao
  {
    get
    {
      return _relacaoParentescoCidadao;
    }
    set
    {
      __isset.relacaoParentescoCidadao = true;
      this._relacaoParentescoCidadao = value;
    }
  }

  public long SituacaoMercadoTrabalhoCidadao
  {
    get
    {
      return _situacaoMercadoTrabalhoCidadao;
    }
    set
    {
      __isset.situacaoMercadoTrabalhoCidadao = true;
      this._situacaoMercadoTrabalhoCidadao = value;
    }
  }

  public bool StatusDesejaInformarOrientacaoSexual
  {
    get
    {
      return _statusDesejaInformarOrientacaoSexual;
    }
    set
    {
      __isset.statusDesejaInformarOrientacaoSexual = true;
      this._statusDesejaInformarOrientacaoSexual = value;
    }
  }

  public bool StatusFrequentaBenzedeira
  {
    get
    {
      return _statusFrequentaBenzedeira;
    }
    set
    {
      __isset.statusFrequentaBenzedeira = true;
      this._statusFrequentaBenzedeira = value;
    }
  }

  public bool StatusFrequentaEscola
  {
    get
    {
      return _statusFrequentaEscola;
    }
    set
    {
      __isset.statusFrequentaEscola = true;
      this._statusFrequentaEscola = value;
    }
  }

  public bool StatusMembroPovoComunidadeTradicional
  {
    get
    {
      return _statusMembroPovoComunidadeTradicional;
    }
    set
    {
      __isset.statusMembroPovoComunidadeTradicional = true;
      this._statusMembroPovoComunidadeTradicional = value;
    }
  }

  public bool StatusParticipaGrupoComunitario
  {
    get
    {
      return _statusParticipaGrupoComunitario;
    }
    set
    {
      __isset.statusParticipaGrupoComunitario = true;
      this._statusParticipaGrupoComunitario = value;
    }
  }

  public bool StatusPossuiPlanoSaudePrivado
  {
    get
    {
      return _statusPossuiPlanoSaudePrivado;
    }
    set
    {
      __isset.statusPossuiPlanoSaudePrivado = true;
      this._statusPossuiPlanoSaudePrivado = value;
    }
  }

  public bool StatusTemAlgumaDeficiencia
  {
    get
    {
      return _statusTemAlgumaDeficiencia;
    }
    set
    {
      __isset.statusTemAlgumaDeficiencia = true;
      this._statusTemAlgumaDeficiencia = value;
    }
  }

  public long IdentidadeGeneroCidadao
  {
    get
    {
      return _identidadeGeneroCidadao;
    }
    set
    {
      __isset.identidadeGeneroCidadao = true;
      this._identidadeGeneroCidadao = value;
    }
  }

  public bool StatusDesejaInformarIdentidadeGenero
  {
    get
    {
      return _statusDesejaInformarIdentidadeGenero;
    }
    set
    {
      __isset.statusDesejaInformarIdentidadeGenero = true;
      this._statusDesejaInformarIdentidadeGenero = value;
    }
  }

  public List<long> ResponsavelPorCrianca
  {
    get
    {
      return _responsavelPorCrianca;
    }
    set
    {
      __isset.responsavelPorCrianca = true;
      this._responsavelPorCrianca = value;
    }
  }

  public long CoPovoComunidadeTradicional
  {
    get
    {
      return _coPovoComunidadeTradicional;
    }
    set
    {
      __isset.coPovoComunidadeTradicional = true;
      this._coPovoComunidadeTradicional = value;
    }
  }


  public InformacoesSocioDemograficas __isset;
  public struct InformacoesSocioDemograficas
    {
    public bool deficienciasCidadao;
    public bool grauInstrucaoCidadao;
    public bool ocupacaoCodigoCbo2002;
    public bool orientacaoSexualCidadao;
    public bool relacaoParentescoCidadao;
    public bool situacaoMercadoTrabalhoCidadao;
    public bool statusDesejaInformarOrientacaoSexual;
    public bool statusFrequentaBenzedeira;
    public bool statusFrequentaEscola;
    public bool statusMembroPovoComunidadeTradicional;
    public bool statusParticipaGrupoComunitario;
    public bool statusPossuiPlanoSaudePrivado;
    public bool statusTemAlgumaDeficiencia;
    public bool identidadeGeneroCidadao;
    public bool statusDesejaInformarIdentidadeGenero;
    public bool responsavelPorCrianca;
    public bool coPovoComunidadeTradicional;
  }

  public InformacoesSocioDemograficasThrift()
  {
  }

  public InformacoesSocioDemograficasThrift DeepCopy()
  {
    var tmp35 = new InformacoesSocioDemograficasThrift();
    if((DeficienciasCidadao != null) && __isset.deficienciasCidadao)
    {
      tmp35.DeficienciasCidadao = this.DeficienciasCidadao.DeepCopy();
    }
    tmp35.__isset.deficienciasCidadao = this.__isset.deficienciasCidadao;
    if(__isset.grauInstrucaoCidadao)
    {
      tmp35.GrauInstrucaoCidadao = this.GrauInstrucaoCidadao;
    }
    tmp35.__isset.grauInstrucaoCidadao = this.__isset.grauInstrucaoCidadao;
    if((OcupacaoCodigoCbo2002 != null) && __isset.ocupacaoCodigoCbo2002)
    {
      tmp35.OcupacaoCodigoCbo2002 = this.OcupacaoCodigoCbo2002;
    }
    tmp35.__isset.ocupacaoCodigoCbo2002 = this.__isset.ocupacaoCodigoCbo2002;
    if(__isset.orientacaoSexualCidadao)
    {
      tmp35.OrientacaoSexualCidadao = this.OrientacaoSexualCidadao;
    }
    tmp35.__isset.orientacaoSexualCidadao = this.__isset.orientacaoSexualCidadao;
    if(__isset.relacaoParentescoCidadao)
    {
      tmp35.RelacaoParentescoCidadao = this.RelacaoParentescoCidadao;
    }
    tmp35.__isset.relacaoParentescoCidadao = this.__isset.relacaoParentescoCidadao;
    if(__isset.situacaoMercadoTrabalhoCidadao)
    {
      tmp35.SituacaoMercadoTrabalhoCidadao = this.SituacaoMercadoTrabalhoCidadao;
    }
    tmp35.__isset.situacaoMercadoTrabalhoCidadao = this.__isset.situacaoMercadoTrabalhoCidadao;
    if(__isset.statusDesejaInformarOrientacaoSexual)
    {
      tmp35.StatusDesejaInformarOrientacaoSexual = this.StatusDesejaInformarOrientacaoSexual;
    }
    tmp35.__isset.statusDesejaInformarOrientacaoSexual = this.__isset.statusDesejaInformarOrientacaoSexual;
    if(__isset.statusFrequentaBenzedeira)
    {
      tmp35.StatusFrequentaBenzedeira = this.StatusFrequentaBenzedeira;
    }
    tmp35.__isset.statusFrequentaBenzedeira = this.__isset.statusFrequentaBenzedeira;
    if(__isset.statusFrequentaEscola)
    {
      tmp35.StatusFrequentaEscola = this.StatusFrequentaEscola;
    }
    tmp35.__isset.statusFrequentaEscola = this.__isset.statusFrequentaEscola;
    if(__isset.statusMembroPovoComunidadeTradicional)
    {
      tmp35.StatusMembroPovoComunidadeTradicional = this.StatusMembroPovoComunidadeTradicional;
    }
    tmp35.__isset.statusMembroPovoComunidadeTradicional = this.__isset.statusMembroPovoComunidadeTradicional;
    if(__isset.statusParticipaGrupoComunitario)
    {
      tmp35.StatusParticipaGrupoComunitario = this.StatusParticipaGrupoComunitario;
    }
    tmp35.__isset.statusParticipaGrupoComunitario = this.__isset.statusParticipaGrupoComunitario;
    if(__isset.statusPossuiPlanoSaudePrivado)
    {
      tmp35.StatusPossuiPlanoSaudePrivado = this.StatusPossuiPlanoSaudePrivado;
    }
    tmp35.__isset.statusPossuiPlanoSaudePrivado = this.__isset.statusPossuiPlanoSaudePrivado;
    if(__isset.statusTemAlgumaDeficiencia)
    {
      tmp35.StatusTemAlgumaDeficiencia = this.StatusTemAlgumaDeficiencia;
    }
    tmp35.__isset.statusTemAlgumaDeficiencia = this.__isset.statusTemAlgumaDeficiencia;
    if(__isset.identidadeGeneroCidadao)
    {
      tmp35.IdentidadeGeneroCidadao = this.IdentidadeGeneroCidadao;
    }
    tmp35.__isset.identidadeGeneroCidadao = this.__isset.identidadeGeneroCidadao;
    if(__isset.statusDesejaInformarIdentidadeGenero)
    {
      tmp35.StatusDesejaInformarIdentidadeGenero = this.StatusDesejaInformarIdentidadeGenero;
    }
    tmp35.__isset.statusDesejaInformarIdentidadeGenero = this.__isset.statusDesejaInformarIdentidadeGenero;
    if((ResponsavelPorCrianca != null) && __isset.responsavelPorCrianca)
    {
      tmp35.ResponsavelPorCrianca = this.ResponsavelPorCrianca.DeepCopy();
    }
    tmp35.__isset.responsavelPorCrianca = this.__isset.responsavelPorCrianca;
    if(__isset.coPovoComunidadeTradicional)
    {
      tmp35.CoPovoComunidadeTradicional = this.CoPovoComunidadeTradicional;
    }
    tmp35.__isset.coPovoComunidadeTradicional = this.__isset.coPovoComunidadeTradicional;
    return tmp35;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List)
            {
              {
                var _list36 = await iprot.ReadListBeginAsync(cancellationToken);
                DeficienciasCidadao = new List<long>(_list36.Count);
                for(int _i37 = 0; _i37 < _list36.Count; ++_i37)
                {
                  long _elem38;
                  _elem38 = await iprot.ReadI64Async(cancellationToken);
                  DeficienciasCidadao.Add(_elem38);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              GrauInstrucaoCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              OcupacaoCodigoCbo2002 = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.I64)
            {
              OrientacaoSexualCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.I64)
            {
              RelacaoParentescoCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.I64)
            {
              SituacaoMercadoTrabalhoCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.Bool)
            {
              StatusDesejaInformarOrientacaoSexual = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.Bool)
            {
              StatusFrequentaBenzedeira = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.Bool)
            {
              StatusFrequentaEscola = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.Bool)
            {
              StatusMembroPovoComunidadeTradicional = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 14:
            if (field.Type == TType.Bool)
            {
              StatusParticipaGrupoComunitario = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 15:
            if (field.Type == TType.Bool)
            {
              StatusPossuiPlanoSaudePrivado = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 16:
            if (field.Type == TType.Bool)
            {
              StatusTemAlgumaDeficiencia = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 17:
            if (field.Type == TType.I64)
            {
              IdentidadeGeneroCidadao = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 18:
            if (field.Type == TType.Bool)
            {
              StatusDesejaInformarIdentidadeGenero = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 19:
            if (field.Type == TType.List)
            {
              {
                var _list39 = await iprot.ReadListBeginAsync(cancellationToken);
                ResponsavelPorCrianca = new List<long>(_list39.Count);
                for(int _i40 = 0; _i40 < _list39.Count; ++_i40)
                {
                  long _elem41;
                  _elem41 = await iprot.ReadI64Async(cancellationToken);
                  ResponsavelPorCrianca.Add(_elem41);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 20:
            if (field.Type == TType.I64)
            {
              CoPovoComunidadeTradicional = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp42 = new TStruct("InformacoesSocioDemograficasThrift");
      await oprot.WriteStructBeginAsync(tmp42, cancellationToken);
      var tmp43 = new TField();
      if((DeficienciasCidadao != null) && __isset.deficienciasCidadao)
      {
        tmp43.Name = "deficienciasCidadao";
        tmp43.Type = TType.List;
        tmp43.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.I64, DeficienciasCidadao.Count), cancellationToken);
        foreach (long _iter44 in DeficienciasCidadao)
        {
          await oprot.WriteI64Async(_iter44, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.grauInstrucaoCidadao)
      {
        tmp43.Name = "grauInstrucaoCidadao";
        tmp43.Type = TType.I64;
        tmp43.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteI64Async(GrauInstrucaoCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((OcupacaoCodigoCbo2002 != null) && __isset.ocupacaoCodigoCbo2002)
      {
        tmp43.Name = "ocupacaoCodigoCbo2002";
        tmp43.Type = TType.String;
        tmp43.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteStringAsync(OcupacaoCodigoCbo2002, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.orientacaoSexualCidadao)
      {
        tmp43.Name = "orientacaoSexualCidadao";
        tmp43.Type = TType.I64;
        tmp43.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteI64Async(OrientacaoSexualCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.relacaoParentescoCidadao)
      {
        tmp43.Name = "relacaoParentescoCidadao";
        tmp43.Type = TType.I64;
        tmp43.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteI64Async(RelacaoParentescoCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.situacaoMercadoTrabalhoCidadao)
      {
        tmp43.Name = "situacaoMercadoTrabalhoCidadao";
        tmp43.Type = TType.I64;
        tmp43.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteI64Async(SituacaoMercadoTrabalhoCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusDesejaInformarOrientacaoSexual)
      {
        tmp43.Name = "statusDesejaInformarOrientacaoSexual";
        tmp43.Type = TType.Bool;
        tmp43.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusDesejaInformarOrientacaoSexual, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusFrequentaBenzedeira)
      {
        tmp43.Name = "statusFrequentaBenzedeira";
        tmp43.Type = TType.Bool;
        tmp43.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusFrequentaBenzedeira, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusFrequentaEscola)
      {
        tmp43.Name = "statusFrequentaEscola";
        tmp43.Type = TType.Bool;
        tmp43.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusFrequentaEscola, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusMembroPovoComunidadeTradicional)
      {
        tmp43.Name = "statusMembroPovoComunidadeTradicional";
        tmp43.Type = TType.Bool;
        tmp43.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusMembroPovoComunidadeTradicional, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusParticipaGrupoComunitario)
      {
        tmp43.Name = "statusParticipaGrupoComunitario";
        tmp43.Type = TType.Bool;
        tmp43.ID = 14;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusParticipaGrupoComunitario, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusPossuiPlanoSaudePrivado)
      {
        tmp43.Name = "statusPossuiPlanoSaudePrivado";
        tmp43.Type = TType.Bool;
        tmp43.ID = 15;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusPossuiPlanoSaudePrivado, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusTemAlgumaDeficiencia)
      {
        tmp43.Name = "statusTemAlgumaDeficiencia";
        tmp43.Type = TType.Bool;
        tmp43.ID = 16;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusTemAlgumaDeficiencia, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.identidadeGeneroCidadao)
      {
        tmp43.Name = "identidadeGeneroCidadao";
        tmp43.Type = TType.I64;
        tmp43.ID = 17;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteI64Async(IdentidadeGeneroCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.statusDesejaInformarIdentidadeGenero)
      {
        tmp43.Name = "statusDesejaInformarIdentidadeGenero";
        tmp43.Type = TType.Bool;
        tmp43.ID = 18;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteBoolAsync(StatusDesejaInformarIdentidadeGenero, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((ResponsavelPorCrianca != null) && __isset.responsavelPorCrianca)
      {
        tmp43.Name = "responsavelPorCrianca";
        tmp43.Type = TType.List;
        tmp43.ID = 19;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.I64, ResponsavelPorCrianca.Count), cancellationToken);
        foreach (long _iter45 in ResponsavelPorCrianca)
        {
          await oprot.WriteI64Async(_iter45, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.coPovoComunidadeTradicional)
      {
        tmp43.Name = "coPovoComunidadeTradicional";
        tmp43.Type = TType.I64;
        tmp43.ID = 20;
        await oprot.WriteFieldBeginAsync(tmp43, cancellationToken);
        await oprot.WriteI64Async(CoPovoComunidadeTradicional, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is InformacoesSocioDemograficasThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.deficienciasCidadao == other.__isset.deficienciasCidadao) && ((!__isset.deficienciasCidadao) || (TCollections.Equals(DeficienciasCidadao, other.DeficienciasCidadao))))
      && ((__isset.grauInstrucaoCidadao == other.__isset.grauInstrucaoCidadao) && ((!__isset.grauInstrucaoCidadao) || (global::System.Object.Equals(GrauInstrucaoCidadao, other.GrauInstrucaoCidadao))))
      && ((__isset.ocupacaoCodigoCbo2002 == other.__isset.ocupacaoCodigoCbo2002) && ((!__isset.ocupacaoCodigoCbo2002) || (global::System.Object.Equals(OcupacaoCodigoCbo2002, other.OcupacaoCodigoCbo2002))))
      && ((__isset.orientacaoSexualCidadao == other.__isset.orientacaoSexualCidadao) && ((!__isset.orientacaoSexualCidadao) || (global::System.Object.Equals(OrientacaoSexualCidadao, other.OrientacaoSexualCidadao))))
      && ((__isset.relacaoParentescoCidadao == other.__isset.relacaoParentescoCidadao) && ((!__isset.relacaoParentescoCidadao) || (global::System.Object.Equals(RelacaoParentescoCidadao, other.RelacaoParentescoCidadao))))
      && ((__isset.situacaoMercadoTrabalhoCidadao == other.__isset.situacaoMercadoTrabalhoCidadao) && ((!__isset.situacaoMercadoTrabalhoCidadao) || (global::System.Object.Equals(SituacaoMercadoTrabalhoCidadao, other.SituacaoMercadoTrabalhoCidadao))))
      && ((__isset.statusDesejaInformarOrientacaoSexual == other.__isset.statusDesejaInformarOrientacaoSexual) && ((!__isset.statusDesejaInformarOrientacaoSexual) || (global::System.Object.Equals(StatusDesejaInformarOrientacaoSexual, other.StatusDesejaInformarOrientacaoSexual))))
      && ((__isset.statusFrequentaBenzedeira == other.__isset.statusFrequentaBenzedeira) && ((!__isset.statusFrequentaBenzedeira) || (global::System.Object.Equals(StatusFrequentaBenzedeira, other.StatusFrequentaBenzedeira))))
      && ((__isset.statusFrequentaEscola == other.__isset.statusFrequentaEscola) && ((!__isset.statusFrequentaEscola) || (global::System.Object.Equals(StatusFrequentaEscola, other.StatusFrequentaEscola))))
      && ((__isset.statusMembroPovoComunidadeTradicional == other.__isset.statusMembroPovoComunidadeTradicional) && ((!__isset.statusMembroPovoComunidadeTradicional) || (global::System.Object.Equals(StatusMembroPovoComunidadeTradicional, other.StatusMembroPovoComunidadeTradicional))))
      && ((__isset.statusParticipaGrupoComunitario == other.__isset.statusParticipaGrupoComunitario) && ((!__isset.statusParticipaGrupoComunitario) || (global::System.Object.Equals(StatusParticipaGrupoComunitario, other.StatusParticipaGrupoComunitario))))
      && ((__isset.statusPossuiPlanoSaudePrivado == other.__isset.statusPossuiPlanoSaudePrivado) && ((!__isset.statusPossuiPlanoSaudePrivado) || (global::System.Object.Equals(StatusPossuiPlanoSaudePrivado, other.StatusPossuiPlanoSaudePrivado))))
      && ((__isset.statusTemAlgumaDeficiencia == other.__isset.statusTemAlgumaDeficiencia) && ((!__isset.statusTemAlgumaDeficiencia) || (global::System.Object.Equals(StatusTemAlgumaDeficiencia, other.StatusTemAlgumaDeficiencia))))
      && ((__isset.identidadeGeneroCidadao == other.__isset.identidadeGeneroCidadao) && ((!__isset.identidadeGeneroCidadao) || (global::System.Object.Equals(IdentidadeGeneroCidadao, other.IdentidadeGeneroCidadao))))
      && ((__isset.statusDesejaInformarIdentidadeGenero == other.__isset.statusDesejaInformarIdentidadeGenero) && ((!__isset.statusDesejaInformarIdentidadeGenero) || (global::System.Object.Equals(StatusDesejaInformarIdentidadeGenero, other.StatusDesejaInformarIdentidadeGenero))))
      && ((__isset.responsavelPorCrianca == other.__isset.responsavelPorCrianca) && ((!__isset.responsavelPorCrianca) || (TCollections.Equals(ResponsavelPorCrianca, other.ResponsavelPorCrianca))))
      && ((__isset.coPovoComunidadeTradicional == other.__isset.coPovoComunidadeTradicional) && ((!__isset.coPovoComunidadeTradicional) || (global::System.Object.Equals(CoPovoComunidadeTradicional, other.CoPovoComunidadeTradicional))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((DeficienciasCidadao != null) && __isset.deficienciasCidadao)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(DeficienciasCidadao);
      }
      if(__isset.grauInstrucaoCidadao)
      {
        hashcode = (hashcode * 397) + GrauInstrucaoCidadao.GetHashCode();
      }
      if((OcupacaoCodigoCbo2002 != null) && __isset.ocupacaoCodigoCbo2002)
      {
        hashcode = (hashcode * 397) + OcupacaoCodigoCbo2002.GetHashCode();
      }
      if(__isset.orientacaoSexualCidadao)
      {
        hashcode = (hashcode * 397) + OrientacaoSexualCidadao.GetHashCode();
      }
      if(__isset.relacaoParentescoCidadao)
      {
        hashcode = (hashcode * 397) + RelacaoParentescoCidadao.GetHashCode();
      }
      if(__isset.situacaoMercadoTrabalhoCidadao)
      {
        hashcode = (hashcode * 397) + SituacaoMercadoTrabalhoCidadao.GetHashCode();
      }
      if(__isset.statusDesejaInformarOrientacaoSexual)
      {
        hashcode = (hashcode * 397) + StatusDesejaInformarOrientacaoSexual.GetHashCode();
      }
      if(__isset.statusFrequentaBenzedeira)
      {
        hashcode = (hashcode * 397) + StatusFrequentaBenzedeira.GetHashCode();
      }
      if(__isset.statusFrequentaEscola)
      {
        hashcode = (hashcode * 397) + StatusFrequentaEscola.GetHashCode();
      }
      if(__isset.statusMembroPovoComunidadeTradicional)
      {
        hashcode = (hashcode * 397) + StatusMembroPovoComunidadeTradicional.GetHashCode();
      }
      if(__isset.statusParticipaGrupoComunitario)
      {
        hashcode = (hashcode * 397) + StatusParticipaGrupoComunitario.GetHashCode();
      }
      if(__isset.statusPossuiPlanoSaudePrivado)
      {
        hashcode = (hashcode * 397) + StatusPossuiPlanoSaudePrivado.GetHashCode();
      }
      if(__isset.statusTemAlgumaDeficiencia)
      {
        hashcode = (hashcode * 397) + StatusTemAlgumaDeficiencia.GetHashCode();
      }
      if(__isset.identidadeGeneroCidadao)
      {
        hashcode = (hashcode * 397) + IdentidadeGeneroCidadao.GetHashCode();
      }
      if(__isset.statusDesejaInformarIdentidadeGenero)
      {
        hashcode = (hashcode * 397) + StatusDesejaInformarIdentidadeGenero.GetHashCode();
      }
      if((ResponsavelPorCrianca != null) && __isset.responsavelPorCrianca)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(ResponsavelPorCrianca);
      }
      if(__isset.coPovoComunidadeTradicional)
      {
        hashcode = (hashcode * 397) + CoPovoComunidadeTradicional.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp46 = new StringBuilder("InformacoesSocioDemograficasThrift(");
    int tmp47 = 0;
    if((DeficienciasCidadao != null) && __isset.deficienciasCidadao)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("DeficienciasCidadao: ");
      DeficienciasCidadao.ToString(tmp46);
    }
    if(__isset.grauInstrucaoCidadao)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("GrauInstrucaoCidadao: ");
      GrauInstrucaoCidadao.ToString(tmp46);
    }
    if((OcupacaoCodigoCbo2002 != null) && __isset.ocupacaoCodigoCbo2002)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("OcupacaoCodigoCbo2002: ");
      OcupacaoCodigoCbo2002.ToString(tmp46);
    }
    if(__isset.orientacaoSexualCidadao)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("OrientacaoSexualCidadao: ");
      OrientacaoSexualCidadao.ToString(tmp46);
    }
    if(__isset.relacaoParentescoCidadao)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("RelacaoParentescoCidadao: ");
      RelacaoParentescoCidadao.ToString(tmp46);
    }
    if(__isset.situacaoMercadoTrabalhoCidadao)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("SituacaoMercadoTrabalhoCidadao: ");
      SituacaoMercadoTrabalhoCidadao.ToString(tmp46);
    }
    if(__isset.statusDesejaInformarOrientacaoSexual)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusDesejaInformarOrientacaoSexual: ");
      StatusDesejaInformarOrientacaoSexual.ToString(tmp46);
    }
    if(__isset.statusFrequentaBenzedeira)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusFrequentaBenzedeira: ");
      StatusFrequentaBenzedeira.ToString(tmp46);
    }
    if(__isset.statusFrequentaEscola)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusFrequentaEscola: ");
      StatusFrequentaEscola.ToString(tmp46);
    }
    if(__isset.statusMembroPovoComunidadeTradicional)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusMembroPovoComunidadeTradicional: ");
      StatusMembroPovoComunidadeTradicional.ToString(tmp46);
    }
    if(__isset.statusParticipaGrupoComunitario)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusParticipaGrupoComunitario: ");
      StatusParticipaGrupoComunitario.ToString(tmp46);
    }
    if(__isset.statusPossuiPlanoSaudePrivado)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusPossuiPlanoSaudePrivado: ");
      StatusPossuiPlanoSaudePrivado.ToString(tmp46);
    }
    if(__isset.statusTemAlgumaDeficiencia)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusTemAlgumaDeficiencia: ");
      StatusTemAlgumaDeficiencia.ToString(tmp46);
    }
    if(__isset.identidadeGeneroCidadao)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("IdentidadeGeneroCidadao: ");
      IdentidadeGeneroCidadao.ToString(tmp46);
    }
    if(__isset.statusDesejaInformarIdentidadeGenero)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("StatusDesejaInformarIdentidadeGenero: ");
      StatusDesejaInformarIdentidadeGenero.ToString(tmp46);
    }
    if((ResponsavelPorCrianca != null) && __isset.responsavelPorCrianca)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("ResponsavelPorCrianca: ");
      ResponsavelPorCrianca.ToString(tmp46);
    }
    if(__isset.coPovoComunidadeTradicional)
    {
      if(0 < tmp47++) { tmp46.Append(", "); }
      tmp46.Append("CoPovoComunidadeTradicional: ");
      CoPovoComunidadeTradicional.ToString(tmp46);
    }
    tmp46.Append(')');
    return tmp46.ToString();
  }
}

