/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class EnderecoLocalPermanenciaThrift : TBase
{
  private string _bairro;
  private string _cep;
  private string _codigoIbgeMunicipio;
  private string _complemento;
  private string _nomeLogradouro;
  private string _numero;
  private string _numeroDneUf;
  private string _telefoneContato;
  private string _telefoneResidencia;
  private string _tipoLogradouroNumeroDne;
  private bool _stSemNumero;
  private string _pontoReferencia;
  private string _microArea;
  private bool _stForaArea;

  public string Bairro
  {
    get
    {
      return _bairro;
    }
    set
    {
      __isset.@bairro = true;
      this._bairro = value;
    }
  }

  public string Cep
  {
    get
    {
      return _cep;
    }
    set
    {
      __isset.@cep = true;
      this._cep = value;
    }
  }

  public string CodigoIbgeMunicipio
  {
    get
    {
      return _codigoIbgeMunicipio;
    }
    set
    {
      __isset.codigoIbgeMunicipio = true;
      this._codigoIbgeMunicipio = value;
    }
  }

  public string Complemento
  {
    get
    {
      return _complemento;
    }
    set
    {
      __isset.@complemento = true;
      this._complemento = value;
    }
  }

  public string NomeLogradouro
  {
    get
    {
      return _nomeLogradouro;
    }
    set
    {
      __isset.nomeLogradouro = true;
      this._nomeLogradouro = value;
    }
  }

  public string Numero
  {
    get
    {
      return _numero;
    }
    set
    {
      __isset.@numero = true;
      this._numero = value;
    }
  }

  public string NumeroDneUf
  {
    get
    {
      return _numeroDneUf;
    }
    set
    {
      __isset.numeroDneUf = true;
      this._numeroDneUf = value;
    }
  }

  public string TelefoneContato
  {
    get
    {
      return _telefoneContato;
    }
    set
    {
      __isset.telefoneContato = true;
      this._telefoneContato = value;
    }
  }

  public string TelefoneResidencia
  {
    get
    {
      return _telefoneResidencia;
    }
    set
    {
      __isset.telefoneResidencia = true;
      this._telefoneResidencia = value;
    }
  }

  public string TipoLogradouroNumeroDne
  {
    get
    {
      return _tipoLogradouroNumeroDne;
    }
    set
    {
      __isset.tipoLogradouroNumeroDne = true;
      this._tipoLogradouroNumeroDne = value;
    }
  }

  public bool StSemNumero
  {
    get
    {
      return _stSemNumero;
    }
    set
    {
      __isset.stSemNumero = true;
      this._stSemNumero = value;
    }
  }

  public string PontoReferencia
  {
    get
    {
      return _pontoReferencia;
    }
    set
    {
      __isset.pontoReferencia = true;
      this._pontoReferencia = value;
    }
  }

  public string MicroArea
  {
    get
    {
      return _microArea;
    }
    set
    {
      __isset.microArea = true;
      this._microArea = value;
    }
  }

  public bool StForaArea
  {
    get
    {
      return _stForaArea;
    }
    set
    {
      __isset.stForaArea = true;
      this._stForaArea = value;
    }
  }


  public EnderecoLocalPermanencia __isset;
  public struct EnderecoLocalPermanencia
    {
    public bool @bairro;
    public bool @cep;
    public bool codigoIbgeMunicipio;
    public bool @complemento;
    public bool nomeLogradouro;
    public bool @numero;
    public bool numeroDneUf;
    public bool telefoneContato;
    public bool telefoneResidencia;
    public bool tipoLogradouroNumeroDne;
    public bool stSemNumero;
    public bool pontoReferencia;
    public bool microArea;
    public bool stForaArea;
  }

  public EnderecoLocalPermanenciaThrift()
  {
  }

  public EnderecoLocalPermanenciaThrift DeepCopy()
  {
    var tmp25 = new EnderecoLocalPermanenciaThrift();
    if((Bairro != null) && __isset.@bairro)
    {
      tmp25.Bairro = this.Bairro;
    }
    tmp25.__isset.@bairro = this.__isset.@bairro;
    if((Cep != null) && __isset.@cep)
    {
      tmp25.Cep = this.Cep;
    }
    tmp25.__isset.@cep = this.__isset.@cep;
    if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
    {
      tmp25.CodigoIbgeMunicipio = this.CodigoIbgeMunicipio;
    }
    tmp25.__isset.codigoIbgeMunicipio = this.__isset.codigoIbgeMunicipio;
    if((Complemento != null) && __isset.@complemento)
    {
      tmp25.Complemento = this.Complemento;
    }
    tmp25.__isset.@complemento = this.__isset.@complemento;
    if((NomeLogradouro != null) && __isset.nomeLogradouro)
    {
      tmp25.NomeLogradouro = this.NomeLogradouro;
    }
    tmp25.__isset.nomeLogradouro = this.__isset.nomeLogradouro;
    if((Numero != null) && __isset.@numero)
    {
      tmp25.Numero = this.Numero;
    }
    tmp25.__isset.@numero = this.__isset.@numero;
    if((NumeroDneUf != null) && __isset.numeroDneUf)
    {
      tmp25.NumeroDneUf = this.NumeroDneUf;
    }
    tmp25.__isset.numeroDneUf = this.__isset.numeroDneUf;
    if((TelefoneContato != null) && __isset.telefoneContato)
    {
      tmp25.TelefoneContato = this.TelefoneContato;
    }
    tmp25.__isset.telefoneContato = this.__isset.telefoneContato;
    if((TelefoneResidencia != null) && __isset.telefoneResidencia)
    {
      tmp25.TelefoneResidencia = this.TelefoneResidencia;
    }
    tmp25.__isset.telefoneResidencia = this.__isset.telefoneResidencia;
    if((TipoLogradouroNumeroDne != null) && __isset.tipoLogradouroNumeroDne)
    {
      tmp25.TipoLogradouroNumeroDne = this.TipoLogradouroNumeroDne;
    }
    tmp25.__isset.tipoLogradouroNumeroDne = this.__isset.tipoLogradouroNumeroDne;
    if(__isset.stSemNumero)
    {
      tmp25.StSemNumero = this.StSemNumero;
    }
    tmp25.__isset.stSemNumero = this.__isset.stSemNumero;
    if((PontoReferencia != null) && __isset.pontoReferencia)
    {
      tmp25.PontoReferencia = this.PontoReferencia;
    }
    tmp25.__isset.pontoReferencia = this.__isset.pontoReferencia;
    if((MicroArea != null) && __isset.microArea)
    {
      tmp25.MicroArea = this.MicroArea;
    }
    tmp25.__isset.microArea = this.__isset.microArea;
    if(__isset.stForaArea)
    {
      tmp25.StForaArea = this.StForaArea;
    }
    tmp25.__isset.stForaArea = this.__isset.stForaArea;
    return tmp25;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              Bairro = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Cep = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              CodigoIbgeMunicipio = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              Complemento = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.String)
            {
              NomeLogradouro = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.String)
            {
              Numero = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.String)
            {
              NumeroDneUf = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.String)
            {
              TelefoneContato = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.String)
            {
              TelefoneResidencia = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.String)
            {
              TipoLogradouroNumeroDne = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.Bool)
            {
              StSemNumero = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.String)
            {
              PontoReferencia = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 13:
            if (field.Type == TType.String)
            {
              MicroArea = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 14:
            if (field.Type == TType.Bool)
            {
              StForaArea = await iprot.ReadBoolAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp26 = new TStruct("EnderecoLocalPermanenciaThrift");
      await oprot.WriteStructBeginAsync(tmp26, cancellationToken);
      var tmp27 = new TField();
      if((Bairro != null) && __isset.@bairro)
      {
        tmp27.Name = "bairro";
        tmp27.Type = TType.String;
        tmp27.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(Bairro, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Cep != null) && __isset.@cep)
      {
        tmp27.Name = "cep";
        tmp27.Type = TType.String;
        tmp27.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(Cep, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
      {
        tmp27.Name = "codigoIbgeMunicipio";
        tmp27.Type = TType.String;
        tmp27.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(CodigoIbgeMunicipio, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Complemento != null) && __isset.@complemento)
      {
        tmp27.Name = "complemento";
        tmp27.Type = TType.String;
        tmp27.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(Complemento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NomeLogradouro != null) && __isset.nomeLogradouro)
      {
        tmp27.Name = "nomeLogradouro";
        tmp27.Type = TType.String;
        tmp27.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(NomeLogradouro, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Numero != null) && __isset.@numero)
      {
        tmp27.Name = "numero";
        tmp27.Type = TType.String;
        tmp27.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(Numero, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((NumeroDneUf != null) && __isset.numeroDneUf)
      {
        tmp27.Name = "numeroDneUf";
        tmp27.Type = TType.String;
        tmp27.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(NumeroDneUf, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TelefoneContato != null) && __isset.telefoneContato)
      {
        tmp27.Name = "telefoneContato";
        tmp27.Type = TType.String;
        tmp27.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(TelefoneContato, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TelefoneResidencia != null) && __isset.telefoneResidencia)
      {
        tmp27.Name = "telefoneResidencia";
        tmp27.Type = TType.String;
        tmp27.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(TelefoneResidencia, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((TipoLogradouroNumeroDne != null) && __isset.tipoLogradouroNumeroDne)
      {
        tmp27.Name = "tipoLogradouroNumeroDne";
        tmp27.Type = TType.String;
        tmp27.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(TipoLogradouroNumeroDne, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.stSemNumero)
      {
        tmp27.Name = "stSemNumero";
        tmp27.Type = TType.Bool;
        tmp27.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteBoolAsync(StSemNumero, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((PontoReferencia != null) && __isset.pontoReferencia)
      {
        tmp27.Name = "pontoReferencia";
        tmp27.Type = TType.String;
        tmp27.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(PontoReferencia, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((MicroArea != null) && __isset.microArea)
      {
        tmp27.Name = "microArea";
        tmp27.Type = TType.String;
        tmp27.ID = 13;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteStringAsync(MicroArea, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.stForaArea)
      {
        tmp27.Name = "stForaArea";
        tmp27.Type = TType.Bool;
        tmp27.ID = 14;
        await oprot.WriteFieldBeginAsync(tmp27, cancellationToken);
        await oprot.WriteBoolAsync(StForaArea, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is EnderecoLocalPermanenciaThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.@bairro == other.__isset.@bairro) && ((!__isset.@bairro) || (global::System.Object.Equals(Bairro, other.Bairro))))
      && ((__isset.@cep == other.__isset.@cep) && ((!__isset.@cep) || (global::System.Object.Equals(Cep, other.Cep))))
      && ((__isset.codigoIbgeMunicipio == other.__isset.codigoIbgeMunicipio) && ((!__isset.codigoIbgeMunicipio) || (global::System.Object.Equals(CodigoIbgeMunicipio, other.CodigoIbgeMunicipio))))
      && ((__isset.@complemento == other.__isset.@complemento) && ((!__isset.@complemento) || (global::System.Object.Equals(Complemento, other.Complemento))))
      && ((__isset.nomeLogradouro == other.__isset.nomeLogradouro) && ((!__isset.nomeLogradouro) || (global::System.Object.Equals(NomeLogradouro, other.NomeLogradouro))))
      && ((__isset.@numero == other.__isset.@numero) && ((!__isset.@numero) || (global::System.Object.Equals(Numero, other.Numero))))
      && ((__isset.numeroDneUf == other.__isset.numeroDneUf) && ((!__isset.numeroDneUf) || (global::System.Object.Equals(NumeroDneUf, other.NumeroDneUf))))
      && ((__isset.telefoneContato == other.__isset.telefoneContato) && ((!__isset.telefoneContato) || (global::System.Object.Equals(TelefoneContato, other.TelefoneContato))))
      && ((__isset.telefoneResidencia == other.__isset.telefoneResidencia) && ((!__isset.telefoneResidencia) || (global::System.Object.Equals(TelefoneResidencia, other.TelefoneResidencia))))
      && ((__isset.tipoLogradouroNumeroDne == other.__isset.tipoLogradouroNumeroDne) && ((!__isset.tipoLogradouroNumeroDne) || (global::System.Object.Equals(TipoLogradouroNumeroDne, other.TipoLogradouroNumeroDne))))
      && ((__isset.stSemNumero == other.__isset.stSemNumero) && ((!__isset.stSemNumero) || (global::System.Object.Equals(StSemNumero, other.StSemNumero))))
      && ((__isset.pontoReferencia == other.__isset.pontoReferencia) && ((!__isset.pontoReferencia) || (global::System.Object.Equals(PontoReferencia, other.PontoReferencia))))
      && ((__isset.microArea == other.__isset.microArea) && ((!__isset.microArea) || (global::System.Object.Equals(MicroArea, other.MicroArea))))
      && ((__isset.stForaArea == other.__isset.stForaArea) && ((!__isset.stForaArea) || (global::System.Object.Equals(StForaArea, other.StForaArea))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((Bairro != null) && __isset.@bairro)
      {
        hashcode = (hashcode * 397) + Bairro.GetHashCode();
      }
      if((Cep != null) && __isset.@cep)
      {
        hashcode = (hashcode * 397) + Cep.GetHashCode();
      }
      if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
      {
        hashcode = (hashcode * 397) + CodigoIbgeMunicipio.GetHashCode();
      }
      if((Complemento != null) && __isset.@complemento)
      {
        hashcode = (hashcode * 397) + Complemento.GetHashCode();
      }
      if((NomeLogradouro != null) && __isset.nomeLogradouro)
      {
        hashcode = (hashcode * 397) + NomeLogradouro.GetHashCode();
      }
      if((Numero != null) && __isset.@numero)
      {
        hashcode = (hashcode * 397) + Numero.GetHashCode();
      }
      if((NumeroDneUf != null) && __isset.numeroDneUf)
      {
        hashcode = (hashcode * 397) + NumeroDneUf.GetHashCode();
      }
      if((TelefoneContato != null) && __isset.telefoneContato)
      {
        hashcode = (hashcode * 397) + TelefoneContato.GetHashCode();
      }
      if((TelefoneResidencia != null) && __isset.telefoneResidencia)
      {
        hashcode = (hashcode * 397) + TelefoneResidencia.GetHashCode();
      }
      if((TipoLogradouroNumeroDne != null) && __isset.tipoLogradouroNumeroDne)
      {
        hashcode = (hashcode * 397) + TipoLogradouroNumeroDne.GetHashCode();
      }
      if(__isset.stSemNumero)
      {
        hashcode = (hashcode * 397) + StSemNumero.GetHashCode();
      }
      if((PontoReferencia != null) && __isset.pontoReferencia)
      {
        hashcode = (hashcode * 397) + PontoReferencia.GetHashCode();
      }
      if((MicroArea != null) && __isset.microArea)
      {
        hashcode = (hashcode * 397) + MicroArea.GetHashCode();
      }
      if(__isset.stForaArea)
      {
        hashcode = (hashcode * 397) + StForaArea.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp28 = new StringBuilder("EnderecoLocalPermanenciaThrift(");
    int tmp29 = 0;
    if((Bairro != null) && __isset.@bairro)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("Bairro: ");
      Bairro.ToString(tmp28);
    }
    if((Cep != null) && __isset.@cep)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("Cep: ");
      Cep.ToString(tmp28);
    }
    if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("CodigoIbgeMunicipio: ");
      CodigoIbgeMunicipio.ToString(tmp28);
    }
    if((Complemento != null) && __isset.@complemento)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("Complemento: ");
      Complemento.ToString(tmp28);
    }
    if((NomeLogradouro != null) && __isset.nomeLogradouro)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("NomeLogradouro: ");
      NomeLogradouro.ToString(tmp28);
    }
    if((Numero != null) && __isset.@numero)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("Numero: ");
      Numero.ToString(tmp28);
    }
    if((NumeroDneUf != null) && __isset.numeroDneUf)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("NumeroDneUf: ");
      NumeroDneUf.ToString(tmp28);
    }
    if((TelefoneContato != null) && __isset.telefoneContato)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("TelefoneContato: ");
      TelefoneContato.ToString(tmp28);
    }
    if((TelefoneResidencia != null) && __isset.telefoneResidencia)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("TelefoneResidencia: ");
      TelefoneResidencia.ToString(tmp28);
    }
    if((TipoLogradouroNumeroDne != null) && __isset.tipoLogradouroNumeroDne)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("TipoLogradouroNumeroDne: ");
      TipoLogradouroNumeroDne.ToString(tmp28);
    }
    if(__isset.stSemNumero)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("StSemNumero: ");
      StSemNumero.ToString(tmp28);
    }
    if((PontoReferencia != null) && __isset.pontoReferencia)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("PontoReferencia: ");
      PontoReferencia.ToString(tmp28);
    }
    if((MicroArea != null) && __isset.microArea)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("MicroArea: ");
      MicroArea.ToString(tmp28);
    }
    if(__isset.stForaArea)
    {
      if(0 < tmp29++) { tmp28.Append(", "); }
      tmp28.Append("StForaArea: ");
      StForaArea.ToString(tmp28);
    }
    tmp28.Append(')');
    return tmp28.ToString();
  }
}

