/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class HeaderCdsCadastroThrift : TBase
{
  private string _cnesUnidadeSaude;
  private string _cnsProfissional;
  private string _codigoIbgeMunicipio;
  private long _dataAtendimento;
  private string _ineEquipe;
  private long _microarea;

  public string CnesUnidadeSaude
  {
    get
    {
      return _cnesUnidadeSaude;
    }
    set
    {
      __isset.cnesUnidadeSaude = true;
      this._cnesUnidadeSaude = value;
    }
  }

  public string CnsProfissional
  {
    get
    {
      return _cnsProfissional;
    }
    set
    {
      __isset.cnsProfissional = true;
      this._cnsProfissional = value;
    }
  }

  public string CodigoIbgeMunicipio
  {
    get
    {
      return _codigoIbgeMunicipio;
    }
    set
    {
      __isset.codigoIbgeMunicipio = true;
      this._codigoIbgeMunicipio = value;
    }
  }

  public long DataAtendimento
  {
    get
    {
      return _dataAtendimento;
    }
    set
    {
      __isset.dataAtendimento = true;
      this._dataAtendimento = value;
    }
  }

  public string IneEquipe
  {
    get
    {
      return _ineEquipe;
    }
    set
    {
      __isset.ineEquipe = true;
      this._ineEquipe = value;
    }
  }

  public long Microarea
  {
    get
    {
      return _microarea;
    }
    set
    {
      __isset.@microarea = true;
      this._microarea = value;
    }
  }


  public HeaderCdsCadastro __isset;
  public struct HeaderCdsCadastro
    {
    public bool cnesUnidadeSaude;
    public bool cnsProfissional;
    public bool codigoIbgeMunicipio;
    public bool dataAtendimento;
    public bool ineEquipe;
    public bool @microarea;
  }

  public HeaderCdsCadastroThrift()
  {
  }

  public HeaderCdsCadastroThrift DeepCopy()
  {
    var tmp0 = new HeaderCdsCadastroThrift();
    if((CnesUnidadeSaude != null) && __isset.cnesUnidadeSaude)
    {
      tmp0.CnesUnidadeSaude = this.CnesUnidadeSaude;
    }
    tmp0.__isset.cnesUnidadeSaude = this.__isset.cnesUnidadeSaude;
    if((CnsProfissional != null) && __isset.cnsProfissional)
    {
      tmp0.CnsProfissional = this.CnsProfissional;
    }
    tmp0.__isset.cnsProfissional = this.__isset.cnsProfissional;
    if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
    {
      tmp0.CodigoIbgeMunicipio = this.CodigoIbgeMunicipio;
    }
    tmp0.__isset.codigoIbgeMunicipio = this.__isset.codigoIbgeMunicipio;
    if(__isset.dataAtendimento)
    {
      tmp0.DataAtendimento = this.DataAtendimento;
    }
    tmp0.__isset.dataAtendimento = this.__isset.dataAtendimento;
    if((IneEquipe != null) && __isset.ineEquipe)
    {
      tmp0.IneEquipe = this.IneEquipe;
    }
    tmp0.__isset.ineEquipe = this.__isset.ineEquipe;
    if(__isset.@microarea)
    {
      tmp0.Microarea = this.Microarea;
    }
    tmp0.__isset.@microarea = this.__isset.@microarea;
    return tmp0;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              CnesUnidadeSaude = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              CnsProfissional = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              CodigoIbgeMunicipio = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I64)
            {
              DataAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.String)
            {
              IneEquipe = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.I64)
            {
              Microarea = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp1 = new TStruct("HeaderCdsCadastroThrift");
      await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
      var tmp2 = new TField();
      if((CnesUnidadeSaude != null) && __isset.cnesUnidadeSaude)
      {
        tmp2.Name = "cnesUnidadeSaude";
        tmp2.Type = TType.String;
        tmp2.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(CnesUnidadeSaude, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CnsProfissional != null) && __isset.cnsProfissional)
      {
        tmp2.Name = "cnsProfissional";
        tmp2.Type = TType.String;
        tmp2.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(CnsProfissional, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
      {
        tmp2.Name = "codigoIbgeMunicipio";
        tmp2.Type = TType.String;
        tmp2.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(CodigoIbgeMunicipio, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataAtendimento)
      {
        tmp2.Name = "dataAtendimento";
        tmp2.Type = TType.I64;
        tmp2.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(DataAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((IneEquipe != null) && __isset.ineEquipe)
      {
        tmp2.Name = "ineEquipe";
        tmp2.Type = TType.String;
        tmp2.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(IneEquipe, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@microarea)
      {
        tmp2.Name = "microarea";
        tmp2.Type = TType.I64;
        tmp2.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI64Async(Microarea, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is HeaderCdsCadastroThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.cnesUnidadeSaude == other.__isset.cnesUnidadeSaude) && ((!__isset.cnesUnidadeSaude) || (global::System.Object.Equals(CnesUnidadeSaude, other.CnesUnidadeSaude))))
      && ((__isset.cnsProfissional == other.__isset.cnsProfissional) && ((!__isset.cnsProfissional) || (global::System.Object.Equals(CnsProfissional, other.CnsProfissional))))
      && ((__isset.codigoIbgeMunicipio == other.__isset.codigoIbgeMunicipio) && ((!__isset.codigoIbgeMunicipio) || (global::System.Object.Equals(CodigoIbgeMunicipio, other.CodigoIbgeMunicipio))))
      && ((__isset.dataAtendimento == other.__isset.dataAtendimento) && ((!__isset.dataAtendimento) || (global::System.Object.Equals(DataAtendimento, other.DataAtendimento))))
      && ((__isset.ineEquipe == other.__isset.ineEquipe) && ((!__isset.ineEquipe) || (global::System.Object.Equals(IneEquipe, other.IneEquipe))))
      && ((__isset.@microarea == other.__isset.@microarea) && ((!__isset.@microarea) || (global::System.Object.Equals(Microarea, other.Microarea))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((CnesUnidadeSaude != null) && __isset.cnesUnidadeSaude)
      {
        hashcode = (hashcode * 397) + CnesUnidadeSaude.GetHashCode();
      }
      if((CnsProfissional != null) && __isset.cnsProfissional)
      {
        hashcode = (hashcode * 397) + CnsProfissional.GetHashCode();
      }
      if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
      {
        hashcode = (hashcode * 397) + CodigoIbgeMunicipio.GetHashCode();
      }
      if(__isset.dataAtendimento)
      {
        hashcode = (hashcode * 397) + DataAtendimento.GetHashCode();
      }
      if((IneEquipe != null) && __isset.ineEquipe)
      {
        hashcode = (hashcode * 397) + IneEquipe.GetHashCode();
      }
      if(__isset.@microarea)
      {
        hashcode = (hashcode * 397) + Microarea.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp3 = new StringBuilder("HeaderCdsCadastroThrift(");
    int tmp4 = 0;
    if((CnesUnidadeSaude != null) && __isset.cnesUnidadeSaude)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CnesUnidadeSaude: ");
      CnesUnidadeSaude.ToString(tmp3);
    }
    if((CnsProfissional != null) && __isset.cnsProfissional)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CnsProfissional: ");
      CnsProfissional.ToString(tmp3);
    }
    if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CodigoIbgeMunicipio: ");
      CodigoIbgeMunicipio.ToString(tmp3);
    }
    if(__isset.dataAtendimento)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("DataAtendimento: ");
      DataAtendimento.ToString(tmp3);
    }
    if((IneEquipe != null) && __isset.ineEquipe)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("IneEquipe: ");
      IneEquipe.ToString(tmp3);
    }
    if(__isset.@microarea)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Microarea: ");
      Microarea.ToString(tmp3);
    }
    tmp3.Append(')');
    return tmp3.ToString();
  }
}

