/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class UnicaLotacaoHeaderThrift : TBase
{
  private string _profissionalCNS;
  private string _cboCodigo_2002;
  private string _cnes;
  private string _ine;
  private long _dataAtendimento;
  private string _codigoIbgeMunicipio;

  public string ProfissionalCNS
  {
    get
    {
      return _profissionalCNS;
    }
    set
    {
      __isset.profissionalCNS = true;
      this._profissionalCNS = value;
    }
  }

  public string CboCodigo_2002
  {
    get
    {
      return _cboCodigo_2002;
    }
    set
    {
      __isset.cboCodigo_2002 = true;
      this._cboCodigo_2002 = value;
    }
  }

  public string Cnes
  {
    get
    {
      return _cnes;
    }
    set
    {
      __isset.@cnes = true;
      this._cnes = value;
    }
  }

  public string Ine
  {
    get
    {
      return _ine;
    }
    set
    {
      __isset.@ine = true;
      this._ine = value;
    }
  }

  public long DataAtendimento
  {
    get
    {
      return _dataAtendimento;
    }
    set
    {
      __isset.dataAtendimento = true;
      this._dataAtendimento = value;
    }
  }

  public string CodigoIbgeMunicipio
  {
    get
    {
      return _codigoIbgeMunicipio;
    }
    set
    {
      __isset.codigoIbgeMunicipio = true;
      this._codigoIbgeMunicipio = value;
    }
  }


  public UnicaLotacaoHeader __isset;
  public struct UnicaLotacaoHeader
    {
    public bool profissionalCNS;
    public bool cboCodigo_2002;
    public bool @cnes;
    public bool @ine;
    public bool dataAtendimento;
    public bool codigoIbgeMunicipio;
  }

  public UnicaLotacaoHeaderThrift()
  {
  }

  public UnicaLotacaoHeaderThrift DeepCopy()
  {
    var tmp10 = new UnicaLotacaoHeaderThrift();
    if((ProfissionalCNS != null) && __isset.profissionalCNS)
    {
      tmp10.ProfissionalCNS = this.ProfissionalCNS;
    }
    tmp10.__isset.profissionalCNS = this.__isset.profissionalCNS;
    if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
    {
      tmp10.CboCodigo_2002 = this.CboCodigo_2002;
    }
    tmp10.__isset.cboCodigo_2002 = this.__isset.cboCodigo_2002;
    if((Cnes != null) && __isset.@cnes)
    {
      tmp10.Cnes = this.Cnes;
    }
    tmp10.__isset.@cnes = this.__isset.@cnes;
    if((Ine != null) && __isset.@ine)
    {
      tmp10.Ine = this.Ine;
    }
    tmp10.__isset.@ine = this.__isset.@ine;
    if(__isset.dataAtendimento)
    {
      tmp10.DataAtendimento = this.DataAtendimento;
    }
    tmp10.__isset.dataAtendimento = this.__isset.dataAtendimento;
    if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
    {
      tmp10.CodigoIbgeMunicipio = this.CodigoIbgeMunicipio;
    }
    tmp10.__isset.codigoIbgeMunicipio = this.__isset.codigoIbgeMunicipio;
    return tmp10;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              ProfissionalCNS = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              CboCodigo_2002 = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              Cnes = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              Ine = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.I64)
            {
              DataAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.String)
            {
              CodigoIbgeMunicipio = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp11 = new TStruct("UnicaLotacaoHeaderThrift");
      await oprot.WriteStructBeginAsync(tmp11, cancellationToken);
      var tmp12 = new TField();
      if((ProfissionalCNS != null) && __isset.profissionalCNS)
      {
        tmp12.Name = "profissionalCNS";
        tmp12.Type = TType.String;
        tmp12.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp12, cancellationToken);
        await oprot.WriteStringAsync(ProfissionalCNS, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
      {
        tmp12.Name = "cboCodigo_2002";
        tmp12.Type = TType.String;
        tmp12.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp12, cancellationToken);
        await oprot.WriteStringAsync(CboCodigo_2002, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Cnes != null) && __isset.@cnes)
      {
        tmp12.Name = "cnes";
        tmp12.Type = TType.String;
        tmp12.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp12, cancellationToken);
        await oprot.WriteStringAsync(Cnes, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((Ine != null) && __isset.@ine)
      {
        tmp12.Name = "ine";
        tmp12.Type = TType.String;
        tmp12.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp12, cancellationToken);
        await oprot.WriteStringAsync(Ine, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataAtendimento)
      {
        tmp12.Name = "dataAtendimento";
        tmp12.Type = TType.I64;
        tmp12.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp12, cancellationToken);
        await oprot.WriteI64Async(DataAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
      {
        tmp12.Name = "codigoIbgeMunicipio";
        tmp12.Type = TType.String;
        tmp12.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp12, cancellationToken);
        await oprot.WriteStringAsync(CodigoIbgeMunicipio, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is UnicaLotacaoHeaderThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.profissionalCNS == other.__isset.profissionalCNS) && ((!__isset.profissionalCNS) || (global::System.Object.Equals(ProfissionalCNS, other.ProfissionalCNS))))
      && ((__isset.cboCodigo_2002 == other.__isset.cboCodigo_2002) && ((!__isset.cboCodigo_2002) || (global::System.Object.Equals(CboCodigo_2002, other.CboCodigo_2002))))
      && ((__isset.@cnes == other.__isset.@cnes) && ((!__isset.@cnes) || (global::System.Object.Equals(Cnes, other.Cnes))))
      && ((__isset.@ine == other.__isset.@ine) && ((!__isset.@ine) || (global::System.Object.Equals(Ine, other.Ine))))
      && ((__isset.dataAtendimento == other.__isset.dataAtendimento) && ((!__isset.dataAtendimento) || (global::System.Object.Equals(DataAtendimento, other.DataAtendimento))))
      && ((__isset.codigoIbgeMunicipio == other.__isset.codigoIbgeMunicipio) && ((!__isset.codigoIbgeMunicipio) || (global::System.Object.Equals(CodigoIbgeMunicipio, other.CodigoIbgeMunicipio))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((ProfissionalCNS != null) && __isset.profissionalCNS)
      {
        hashcode = (hashcode * 397) + ProfissionalCNS.GetHashCode();
      }
      if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
      {
        hashcode = (hashcode * 397) + CboCodigo_2002.GetHashCode();
      }
      if((Cnes != null) && __isset.@cnes)
      {
        hashcode = (hashcode * 397) + Cnes.GetHashCode();
      }
      if((Ine != null) && __isset.@ine)
      {
        hashcode = (hashcode * 397) + Ine.GetHashCode();
      }
      if(__isset.dataAtendimento)
      {
        hashcode = (hashcode * 397) + DataAtendimento.GetHashCode();
      }
      if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
      {
        hashcode = (hashcode * 397) + CodigoIbgeMunicipio.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp13 = new StringBuilder("UnicaLotacaoHeaderThrift(");
    int tmp14 = 0;
    if((ProfissionalCNS != null) && __isset.profissionalCNS)
    {
      if(0 < tmp14++) { tmp13.Append(", "); }
      tmp13.Append("ProfissionalCNS: ");
      ProfissionalCNS.ToString(tmp13);
    }
    if((CboCodigo_2002 != null) && __isset.cboCodigo_2002)
    {
      if(0 < tmp14++) { tmp13.Append(", "); }
      tmp13.Append("CboCodigo_2002: ");
      CboCodigo_2002.ToString(tmp13);
    }
    if((Cnes != null) && __isset.@cnes)
    {
      if(0 < tmp14++) { tmp13.Append(", "); }
      tmp13.Append("Cnes: ");
      Cnes.ToString(tmp13);
    }
    if((Ine != null) && __isset.@ine)
    {
      if(0 < tmp14++) { tmp13.Append(", "); }
      tmp13.Append("Ine: ");
      Ine.ToString(tmp13);
    }
    if(__isset.dataAtendimento)
    {
      if(0 < tmp14++) { tmp13.Append(", "); }
      tmp13.Append("DataAtendimento: ");
      DataAtendimento.ToString(tmp13);
    }
    if((CodigoIbgeMunicipio != null) && __isset.codigoIbgeMunicipio)
    {
      if(0 < tmp14++) { tmp13.Append(", "); }
      tmp13.Append("CodigoIbgeMunicipio: ");
      CodigoIbgeMunicipio.ToString(tmp13);
    }
    tmp13.Append(')');
    return tmp13.ToString();
  }
}

