// <auto-generated />
using System;
using Encore.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Encore.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230808014424_SeedFormHomeAddressQuestions")]
    partial class SeedFormHomeAddressQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Encore.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("City");

                    b.Property<string>("Landmark")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Landmark");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Neighborhood");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("State");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Street");

                    b.Property<string>("StreetComplement")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StreetComplement");

                    b.Property<string>("StreetType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StreetType");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("HealthCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MicroregionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HealthCenterId");

                    b.HasIndex("MicroregionId");

                    b.HasIndex("UserId");

                    b.ToTable("Agent", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.HealthCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnes")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountableId")
                        .IsUnique();

                    b.HasIndex("AddressId");

                    b.ToTable("HealthCenter", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.HealthCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CauseHospotalization")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("DiagnoseMentalHealthProblem")
                        .HasColumnType("bit");

                    b.Property<bool>("HadCanser")
                        .HasColumnType("bit");

                    b.Property<bool>("HadHeartAttack")
                        .HasColumnType("bit");

                    b.Property<bool>("HadStroke")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLeprosy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRespiratoryDisease")
                        .HasColumnType("bit");

                    b.Property<string>("HeartDisease")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsBedridden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDomiciled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<string>("MedicinalPlants")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherHealthConditions")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ReacentlyHospitalization")
                        .HasColumnType("bit");

                    b.Property<string>("RespiratoryDisease")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("StreetSituation")
                        .HasColumnType("bit");

                    b.Property<bool>("UseAlcohol")
                        .HasColumnType("bit");

                    b.Property<bool>("UseMedicinalPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesOtherDrugs")
                        .HasColumnType("bit");

                    b.Property<string>("WeightCondition")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("HealthCondition", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountAnimals")
                        .HasColumnType("int");

                    b.Property<string>("Animals")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("Electricity")
                        .HasColumnType("bit");

                    b.Property<string>("GarbageDestination")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("HouseholdIncome")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MedicalRecordNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("MicroregionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberMembers")
                        .HasColumnType("int");

                    b.Property<int>("NumberRooms")
                        .HasColumnType("int");

                    b.Property<string>("PredominantMaterial")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("RuralProductionArea")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("SanitaryDrainage")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("TypeAccess")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("TypeDomicile")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("TypeProperty")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("WaterConsumption")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("WaterSupply")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("MicroregionId");

                    b.ToTable("Home", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Microregion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("HealthCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HealthCenterId");

                    b.ToTable("Microregion", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.OtherQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubQuestionId");

                    b.ToTable("OtherQuestion", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHeadFamily")
                        .HasColumnType("bit");

                    b.Property<Guid>("MicroregionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SocialIdentification")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SocialName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.HasIndex("HomeId");

                    b.HasIndex("MicroregionId");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Order")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<decimal>("ResponseType")
                        .HasColumnType("numeric(2,0)");

                    b.Property<string>("SlugProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("VisitId");

                    b.ToTable("QuestionAnswer", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.SociodemographicSituation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendSchool")
                        .HasColumnType("bit");

                    b.Property<string>("Disability")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GenderIdentity")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("HasDisability")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGenderIdentity")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasPrivateHealthPlan")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSexualOrientation")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTraditionalCaregiver")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMemberCommunityGroup")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMemberTraditionalCommunity")
                        .HasColumnType("bit");

                    b.Property<string>("LaborMarketSituation")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("LevelEducation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Occupation")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SexualOrientation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TraditionalCommunity")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("SociodemographicSituation", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermission", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MicroregionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("HomeId");

                    b.HasIndex("MicroregionId");

                    b.HasIndex("PersonId");

                    b.ToTable("Visit", (string)null);
                });

            modelBuilder.Entity("Encore.Domain.Models.Agent", b =>
                {
                    b.HasOne("Encore.Domain.Models.HealthCenter", "HealthCenter")
                        .WithMany("Agents")
                        .HasForeignKey("HealthCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Microregion", "Microregion")
                        .WithMany("Agents")
                        .HasForeignKey("MicroregionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.User", "User")
                        .WithMany("Agents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCenter");

                    b.Navigation("Microregion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Encore.Domain.Models.HealthCenter", b =>
                {
                    b.HasOne("Encore.Domain.Models.User", "Accountable")
                        .WithOne("HealthCenter")
                        .HasForeignKey("Encore.Domain.Models.HealthCenter", "AccountableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Address", "Address")
                        .WithMany("HealthCenters")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accountable");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Encore.Domain.Models.HealthCondition", b =>
                {
                    b.HasOne("Encore.Domain.Models.Person", "Person")
                        .WithMany("HealthConditions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Encore.Domain.Models.Home", b =>
                {
                    b.HasOne("Encore.Domain.Models.Address", "Address")
                        .WithMany("Homes")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Microregion", "Microregion")
                        .WithMany("Homes")
                        .HasForeignKey("MicroregionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Microregion");
                });

            modelBuilder.Entity("Encore.Domain.Models.Microregion", b =>
                {
                    b.HasOne("Encore.Domain.Models.HealthCenter", "HealthCenter")
                        .WithMany("Microregions")
                        .HasForeignKey("HealthCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCenter");
                });

            modelBuilder.Entity("Encore.Domain.Models.OtherQuestion", b =>
                {
                    b.HasOne("Encore.Domain.Models.Question", "Question")
                        .WithMany("OtherQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Encore.Domain.Models.Question", "SubQuestion")
                        .WithMany("OtherSubQuestions")
                        .HasForeignKey("SubQuestionId");

                    b.Navigation("Question");

                    b.Navigation("SubQuestion");
                });

            modelBuilder.Entity("Encore.Domain.Models.Person", b =>
                {
                    b.HasOne("Encore.Domain.Models.Home", "Home")
                        .WithMany("Persons")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Microregion", "Microregion")
                        .WithMany("Persons")
                        .HasForeignKey("MicroregionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("Microregion");
                });

            modelBuilder.Entity("Encore.Domain.Models.Question", b =>
                {
                    b.HasOne("Encore.Domain.Models.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Encore.Domain.Models.QuestionAnswer", b =>
                {
                    b.HasOne("Encore.Domain.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Visit", "Visit")
                        .WithMany("Answers")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Encore.Domain.Models.SociodemographicSituation", b =>
                {
                    b.HasOne("Encore.Domain.Models.Person", "Person")
                        .WithMany("SociodemographicSituations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Encore.Domain.Models.UserPermission", b =>
                {
                    b.HasOne("Encore.Domain.Models.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Encore.Domain.Models.Visit", b =>
                {
                    b.HasOne("Encore.Domain.Models.Agent", "Agent")
                        .WithMany("Visits")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Home", "Home")
                        .WithMany("Visits")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Microregion", "Microregion")
                        .WithMany("Visits")
                        .HasForeignKey("MicroregionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Encore.Domain.Models.Person", "Person")
                        .WithMany("Visits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Home");

                    b.Navigation("Microregion");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Encore.Domain.Models.Address", b =>
                {
                    b.Navigation("HealthCenters");

                    b.Navigation("Homes");
                });

            modelBuilder.Entity("Encore.Domain.Models.Agent", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Encore.Domain.Models.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Encore.Domain.Models.HealthCenter", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Microregions");
                });

            modelBuilder.Entity("Encore.Domain.Models.Home", b =>
                {
                    b.Navigation("Persons");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Encore.Domain.Models.Microregion", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Homes");

                    b.Navigation("Persons");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Encore.Domain.Models.Permission", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Encore.Domain.Models.Person", b =>
                {
                    b.Navigation("HealthConditions");

                    b.Navigation("SociodemographicSituations");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Encore.Domain.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("OtherQuestions");

                    b.Navigation("OtherSubQuestions");
                });

            modelBuilder.Entity("Encore.Domain.Models.User", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("HealthCenter")
                        .IsRequired();

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Encore.Domain.Models.Visit", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
