/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Collections;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class FichaConsumoAlimentarThrift : TBase
{
  private UnicaLotacaoHeaderThrift _headerTransport;
  private string _cnsCidadao;
  private long _dataNascimento;
  private long _sexo;
  private long _localAtendimento;
  private List<PerguntaQuestionarioCriancasMenoresSeisMesesThrift> _perguntasQuestionarioCriancasMenoresSeisMeses;
  private List<PerguntaQuestionarioCriancasDeSeisVinteTresMesesThrift> _perguntasQuestionarioCriancasDeSeisVinteTresMeses;
  private List<PerguntaQuestionarioCriancasComMaisDoisAnosThrift> _perguntasQuestionarioCriancasComMaisDoisAnos;
  private int _tpCdsOrigem;
  private string _cpfCidadao;

  public UnicaLotacaoHeaderThrift HeaderTransport
  {
    get
    {
      return _headerTransport;
    }
    set
    {
      __isset.headerTransport = true;
      this._headerTransport = value;
    }
  }

  public string CnsCidadao
  {
    get
    {
      return _cnsCidadao;
    }
    set
    {
      __isset.cnsCidadao = true;
      this._cnsCidadao = value;
    }
  }

  public long DataNascimento
  {
    get
    {
      return _dataNascimento;
    }
    set
    {
      __isset.dataNascimento = true;
      this._dataNascimento = value;
    }
  }

  public long Sexo
  {
    get
    {
      return _sexo;
    }
    set
    {
      __isset.@sexo = true;
      this._sexo = value;
    }
  }

  public long LocalAtendimento
  {
    get
    {
      return _localAtendimento;
    }
    set
    {
      __isset.localAtendimento = true;
      this._localAtendimento = value;
    }
  }

  public List<PerguntaQuestionarioCriancasMenoresSeisMesesThrift> PerguntasQuestionarioCriancasMenoresSeisMeses
  {
    get
    {
      return _perguntasQuestionarioCriancasMenoresSeisMeses;
    }
    set
    {
      __isset.perguntasQuestionarioCriancasMenoresSeisMeses = true;
      this._perguntasQuestionarioCriancasMenoresSeisMeses = value;
    }
  }

  public List<PerguntaQuestionarioCriancasDeSeisVinteTresMesesThrift> PerguntasQuestionarioCriancasDeSeisVinteTresMeses
  {
    get
    {
      return _perguntasQuestionarioCriancasDeSeisVinteTresMeses;
    }
    set
    {
      __isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses = true;
      this._perguntasQuestionarioCriancasDeSeisVinteTresMeses = value;
    }
  }

  public List<PerguntaQuestionarioCriancasComMaisDoisAnosThrift> PerguntasQuestionarioCriancasComMaisDoisAnos
  {
    get
    {
      return _perguntasQuestionarioCriancasComMaisDoisAnos;
    }
    set
    {
      __isset.perguntasQuestionarioCriancasComMaisDoisAnos = true;
      this._perguntasQuestionarioCriancasComMaisDoisAnos = value;
    }
  }

  public string UuidFicha { get; set; }

  public int TpCdsOrigem
  {
    get
    {
      return _tpCdsOrigem;
    }
    set
    {
      __isset.tpCdsOrigem = true;
      this._tpCdsOrigem = value;
    }
  }

  public string CpfCidadao
  {
    get
    {
      return _cpfCidadao;
    }
    set
    {
      __isset.cpfCidadao = true;
      this._cpfCidadao = value;
    }
  }


  public FichaConsumoAlimentar __isset;
  public struct FichaConsumoAlimentar
    {
    public bool headerTransport;
    public bool cnsCidadao;
    public bool dataNascimento;
    public bool @sexo;
    public bool localAtendimento;
    public bool perguntasQuestionarioCriancasMenoresSeisMeses;
    public bool perguntasQuestionarioCriancasDeSeisVinteTresMeses;
    public bool perguntasQuestionarioCriancasComMaisDoisAnos;
    public bool tpCdsOrigem;
    public bool cpfCidadao;
  }

  public FichaConsumoAlimentarThrift()
  {
  }

  public FichaConsumoAlimentarThrift(string uuidFicha) : this()
  {
    this.UuidFicha = uuidFicha;
  }

  public FichaConsumoAlimentarThrift DeepCopy()
  {
    var tmp19 = new FichaConsumoAlimentarThrift();
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp19.HeaderTransport = (UnicaLotacaoHeaderThrift)this.HeaderTransport.DeepCopy();
    }
    tmp19.__isset.headerTransport = this.__isset.headerTransport;
    if((CnsCidadao != null) && __isset.cnsCidadao)
    {
      tmp19.CnsCidadao = this.CnsCidadao;
    }
    tmp19.__isset.cnsCidadao = this.__isset.cnsCidadao;
    if(__isset.dataNascimento)
    {
      tmp19.DataNascimento = this.DataNascimento;
    }
    tmp19.__isset.dataNascimento = this.__isset.dataNascimento;
    if(__isset.@sexo)
    {
      tmp19.Sexo = this.Sexo;
    }
    tmp19.__isset.@sexo = this.__isset.@sexo;
    if(__isset.localAtendimento)
    {
      tmp19.LocalAtendimento = this.LocalAtendimento;
    }
    tmp19.__isset.localAtendimento = this.__isset.localAtendimento;
    if((PerguntasQuestionarioCriancasMenoresSeisMeses != null) && __isset.perguntasQuestionarioCriancasMenoresSeisMeses)
    {
      tmp19.PerguntasQuestionarioCriancasMenoresSeisMeses = this.PerguntasQuestionarioCriancasMenoresSeisMeses.DeepCopy();
    }
    tmp19.__isset.perguntasQuestionarioCriancasMenoresSeisMeses = this.__isset.perguntasQuestionarioCriancasMenoresSeisMeses;
    if((PerguntasQuestionarioCriancasDeSeisVinteTresMeses != null) && __isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses)
    {
      tmp19.PerguntasQuestionarioCriancasDeSeisVinteTresMeses = this.PerguntasQuestionarioCriancasDeSeisVinteTresMeses.DeepCopy();
    }
    tmp19.__isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses = this.__isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses;
    if((PerguntasQuestionarioCriancasComMaisDoisAnos != null) && __isset.perguntasQuestionarioCriancasComMaisDoisAnos)
    {
      tmp19.PerguntasQuestionarioCriancasComMaisDoisAnos = this.PerguntasQuestionarioCriancasComMaisDoisAnos.DeepCopy();
    }
    tmp19.__isset.perguntasQuestionarioCriancasComMaisDoisAnos = this.__isset.perguntasQuestionarioCriancasComMaisDoisAnos;
    if((UuidFicha != null))
    {
      tmp19.UuidFicha = this.UuidFicha;
    }
    if(__isset.tpCdsOrigem)
    {
      tmp19.TpCdsOrigem = this.TpCdsOrigem;
    }
    tmp19.__isset.tpCdsOrigem = this.__isset.tpCdsOrigem;
    if((CpfCidadao != null) && __isset.cpfCidadao)
    {
      tmp19.CpfCidadao = this.CpfCidadao;
    }
    tmp19.__isset.cpfCidadao = this.__isset.cpfCidadao;
    return tmp19;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_uuidFicha = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              HeaderTransport = new UnicaLotacaoHeaderThrift();
              await HeaderTransport.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              CnsCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I64)
            {
              DataNascimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.I64)
            {
              Sexo = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 6:
            if (field.Type == TType.I64)
            {
              LocalAtendimento = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 7:
            if (field.Type == TType.List)
            {
              {
                var _list20 = await iprot.ReadListBeginAsync(cancellationToken);
                PerguntasQuestionarioCriancasMenoresSeisMeses = new List<PerguntaQuestionarioCriancasMenoresSeisMesesThrift>(_list20.Count);
                for(int _i21 = 0; _i21 < _list20.Count; ++_i21)
                {
                  PerguntaQuestionarioCriancasMenoresSeisMesesThrift _elem22;
                  _elem22 = new PerguntaQuestionarioCriancasMenoresSeisMesesThrift();
                  await _elem22.ReadAsync(iprot, cancellationToken);
                  PerguntasQuestionarioCriancasMenoresSeisMeses.Add(_elem22);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 8:
            if (field.Type == TType.List)
            {
              {
                var _list23 = await iprot.ReadListBeginAsync(cancellationToken);
                PerguntasQuestionarioCriancasDeSeisVinteTresMeses = new List<PerguntaQuestionarioCriancasDeSeisVinteTresMesesThrift>(_list23.Count);
                for(int _i24 = 0; _i24 < _list23.Count; ++_i24)
                {
                  PerguntaQuestionarioCriancasDeSeisVinteTresMesesThrift _elem25;
                  _elem25 = new PerguntaQuestionarioCriancasDeSeisVinteTresMesesThrift();
                  await _elem25.ReadAsync(iprot, cancellationToken);
                  PerguntasQuestionarioCriancasDeSeisVinteTresMeses.Add(_elem25);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 9:
            if (field.Type == TType.List)
            {
              {
                var _list26 = await iprot.ReadListBeginAsync(cancellationToken);
                PerguntasQuestionarioCriancasComMaisDoisAnos = new List<PerguntaQuestionarioCriancasComMaisDoisAnosThrift>(_list26.Count);
                for(int _i27 = 0; _i27 < _list26.Count; ++_i27)
                {
                  PerguntaQuestionarioCriancasComMaisDoisAnosThrift _elem28;
                  _elem28 = new PerguntaQuestionarioCriancasComMaisDoisAnosThrift();
                  await _elem28.ReadAsync(iprot, cancellationToken);
                  PerguntasQuestionarioCriancasComMaisDoisAnos.Add(_elem28);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 10:
            if (field.Type == TType.String)
            {
              UuidFicha = await iprot.ReadStringAsync(cancellationToken);
              isset_uuidFicha = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 11:
            if (field.Type == TType.I32)
            {
              TpCdsOrigem = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 12:
            if (field.Type == TType.String)
            {
              CpfCidadao = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_uuidFicha)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp29 = new TStruct("FichaConsumoAlimentarThrift");
      await oprot.WriteStructBeginAsync(tmp29, cancellationToken);
      var tmp30 = new TField();
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        tmp30.Name = "headerTransport";
        tmp30.Type = TType.Struct;
        tmp30.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await HeaderTransport.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CnsCidadao != null) && __isset.cnsCidadao)
      {
        tmp30.Name = "cnsCidadao";
        tmp30.Type = TType.String;
        tmp30.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteStringAsync(CnsCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.dataNascimento)
      {
        tmp30.Name = "dataNascimento";
        tmp30.Type = TType.I64;
        tmp30.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteI64Async(DataNascimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@sexo)
      {
        tmp30.Name = "sexo";
        tmp30.Type = TType.I64;
        tmp30.ID = 5;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteI64Async(Sexo, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.localAtendimento)
      {
        tmp30.Name = "localAtendimento";
        tmp30.Type = TType.I64;
        tmp30.ID = 6;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteI64Async(LocalAtendimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((PerguntasQuestionarioCriancasMenoresSeisMeses != null) && __isset.perguntasQuestionarioCriancasMenoresSeisMeses)
      {
        tmp30.Name = "perguntasQuestionarioCriancasMenoresSeisMeses";
        tmp30.Type = TType.List;
        tmp30.ID = 7;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, PerguntasQuestionarioCriancasMenoresSeisMeses.Count), cancellationToken);
        foreach (PerguntaQuestionarioCriancasMenoresSeisMesesThrift _iter31 in PerguntasQuestionarioCriancasMenoresSeisMeses)
        {
          await _iter31.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((PerguntasQuestionarioCriancasDeSeisVinteTresMeses != null) && __isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses)
      {
        tmp30.Name = "perguntasQuestionarioCriancasDeSeisVinteTresMeses";
        tmp30.Type = TType.List;
        tmp30.ID = 8;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, PerguntasQuestionarioCriancasDeSeisVinteTresMeses.Count), cancellationToken);
        foreach (PerguntaQuestionarioCriancasDeSeisVinteTresMesesThrift _iter32 in PerguntasQuestionarioCriancasDeSeisVinteTresMeses)
        {
          await _iter32.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((PerguntasQuestionarioCriancasComMaisDoisAnos != null) && __isset.perguntasQuestionarioCriancasComMaisDoisAnos)
      {
        tmp30.Name = "perguntasQuestionarioCriancasComMaisDoisAnos";
        tmp30.Type = TType.List;
        tmp30.ID = 9;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, PerguntasQuestionarioCriancasComMaisDoisAnos.Count), cancellationToken);
        foreach (PerguntaQuestionarioCriancasComMaisDoisAnosThrift _iter33 in PerguntasQuestionarioCriancasComMaisDoisAnos)
        {
          await _iter33.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((UuidFicha != null))
      {
        tmp30.Name = "uuidFicha";
        tmp30.Type = TType.String;
        tmp30.ID = 10;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteStringAsync(UuidFicha, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.tpCdsOrigem)
      {
        tmp30.Name = "tpCdsOrigem";
        tmp30.Type = TType.I32;
        tmp30.ID = 11;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteI32Async(TpCdsOrigem, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((CpfCidadao != null) && __isset.cpfCidadao)
      {
        tmp30.Name = "cpfCidadao";
        tmp30.Type = TType.String;
        tmp30.ID = 12;
        await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
        await oprot.WriteStringAsync(CpfCidadao, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FichaConsumoAlimentarThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.headerTransport == other.__isset.headerTransport) && ((!__isset.headerTransport) || (global::System.Object.Equals(HeaderTransport, other.HeaderTransport))))
      && ((__isset.cnsCidadao == other.__isset.cnsCidadao) && ((!__isset.cnsCidadao) || (global::System.Object.Equals(CnsCidadao, other.CnsCidadao))))
      && ((__isset.dataNascimento == other.__isset.dataNascimento) && ((!__isset.dataNascimento) || (global::System.Object.Equals(DataNascimento, other.DataNascimento))))
      && ((__isset.@sexo == other.__isset.@sexo) && ((!__isset.@sexo) || (global::System.Object.Equals(Sexo, other.Sexo))))
      && ((__isset.localAtendimento == other.__isset.localAtendimento) && ((!__isset.localAtendimento) || (global::System.Object.Equals(LocalAtendimento, other.LocalAtendimento))))
      && ((__isset.perguntasQuestionarioCriancasMenoresSeisMeses == other.__isset.perguntasQuestionarioCriancasMenoresSeisMeses) && ((!__isset.perguntasQuestionarioCriancasMenoresSeisMeses) || (TCollections.Equals(PerguntasQuestionarioCriancasMenoresSeisMeses, other.PerguntasQuestionarioCriancasMenoresSeisMeses))))
      && ((__isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses == other.__isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses) && ((!__isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses) || (TCollections.Equals(PerguntasQuestionarioCriancasDeSeisVinteTresMeses, other.PerguntasQuestionarioCriancasDeSeisVinteTresMeses))))
      && ((__isset.perguntasQuestionarioCriancasComMaisDoisAnos == other.__isset.perguntasQuestionarioCriancasComMaisDoisAnos) && ((!__isset.perguntasQuestionarioCriancasComMaisDoisAnos) || (TCollections.Equals(PerguntasQuestionarioCriancasComMaisDoisAnos, other.PerguntasQuestionarioCriancasComMaisDoisAnos))))
      && global::System.Object.Equals(UuidFicha, other.UuidFicha)
      && ((__isset.tpCdsOrigem == other.__isset.tpCdsOrigem) && ((!__isset.tpCdsOrigem) || (global::System.Object.Equals(TpCdsOrigem, other.TpCdsOrigem))))
      && ((__isset.cpfCidadao == other.__isset.cpfCidadao) && ((!__isset.cpfCidadao) || (global::System.Object.Equals(CpfCidadao, other.CpfCidadao))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        hashcode = (hashcode * 397) + HeaderTransport.GetHashCode();
      }
      if((CnsCidadao != null) && __isset.cnsCidadao)
      {
        hashcode = (hashcode * 397) + CnsCidadao.GetHashCode();
      }
      if(__isset.dataNascimento)
      {
        hashcode = (hashcode * 397) + DataNascimento.GetHashCode();
      }
      if(__isset.@sexo)
      {
        hashcode = (hashcode * 397) + Sexo.GetHashCode();
      }
      if(__isset.localAtendimento)
      {
        hashcode = (hashcode * 397) + LocalAtendimento.GetHashCode();
      }
      if((PerguntasQuestionarioCriancasMenoresSeisMeses != null) && __isset.perguntasQuestionarioCriancasMenoresSeisMeses)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(PerguntasQuestionarioCriancasMenoresSeisMeses);
      }
      if((PerguntasQuestionarioCriancasDeSeisVinteTresMeses != null) && __isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(PerguntasQuestionarioCriancasDeSeisVinteTresMeses);
      }
      if((PerguntasQuestionarioCriancasComMaisDoisAnos != null) && __isset.perguntasQuestionarioCriancasComMaisDoisAnos)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(PerguntasQuestionarioCriancasComMaisDoisAnos);
      }
      if((UuidFicha != null))
      {
        hashcode = (hashcode * 397) + UuidFicha.GetHashCode();
      }
      if(__isset.tpCdsOrigem)
      {
        hashcode = (hashcode * 397) + TpCdsOrigem.GetHashCode();
      }
      if((CpfCidadao != null) && __isset.cpfCidadao)
      {
        hashcode = (hashcode * 397) + CpfCidadao.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp34 = new StringBuilder("FichaConsumoAlimentarThrift(");
    int tmp35 = 0;
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("HeaderTransport: ");
      HeaderTransport.ToString(tmp34);
    }
    if((CnsCidadao != null) && __isset.cnsCidadao)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("CnsCidadao: ");
      CnsCidadao.ToString(tmp34);
    }
    if(__isset.dataNascimento)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("DataNascimento: ");
      DataNascimento.ToString(tmp34);
    }
    if(__isset.@sexo)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("Sexo: ");
      Sexo.ToString(tmp34);
    }
    if(__isset.localAtendimento)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("LocalAtendimento: ");
      LocalAtendimento.ToString(tmp34);
    }
    if((PerguntasQuestionarioCriancasMenoresSeisMeses != null) && __isset.perguntasQuestionarioCriancasMenoresSeisMeses)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("PerguntasQuestionarioCriancasMenoresSeisMeses: ");
      PerguntasQuestionarioCriancasMenoresSeisMeses.ToString(tmp34);
    }
    if((PerguntasQuestionarioCriancasDeSeisVinteTresMeses != null) && __isset.perguntasQuestionarioCriancasDeSeisVinteTresMeses)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("PerguntasQuestionarioCriancasDeSeisVinteTresMeses: ");
      PerguntasQuestionarioCriancasDeSeisVinteTresMeses.ToString(tmp34);
    }
    if((PerguntasQuestionarioCriancasComMaisDoisAnos != null) && __isset.perguntasQuestionarioCriancasComMaisDoisAnos)
    {
      if(0 < tmp35++) { tmp34.Append(", "); }
      tmp34.Append("PerguntasQuestionarioCriancasComMaisDoisAnos: ");
      PerguntasQuestionarioCriancasComMaisDoisAnos.ToString(tmp34);
    }
    if((UuidFicha != null))
    {
      if(0 < tmp35) { tmp34.Append(", "); }
      tmp34.Append("UuidFicha: ");
      UuidFicha.ToString(tmp34);
    }
    if(__isset.tpCdsOrigem)
    {
      tmp34.Append(", TpCdsOrigem: ");
      TpCdsOrigem.ToString(tmp34);
    }
    if((CpfCidadao != null) && __isset.cpfCidadao)
    {
      tmp34.Append(", CpfCidadao: ");
      CpfCidadao.ToString(tmp34);
    }
    tmp34.Append(')');
    return tmp34.ToString();
  }
}

