/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Collections;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class FichaAtendimentoOdontologicoMasterThrift : TBase
{
  private VariasLotacoesHeaderThrift _headerTransport;
  private List<FichaAtendimentoOdontologicoChildThrift> _atendimentosOdontologicos;
  private int _tpCdsOrigem;

  public string UuidFicha { get; set; }

  public VariasLotacoesHeaderThrift HeaderTransport
  {
    get
    {
      return _headerTransport;
    }
    set
    {
      __isset.headerTransport = true;
      this._headerTransport = value;
    }
  }

  public List<FichaAtendimentoOdontologicoChildThrift> AtendimentosOdontologicos
  {
    get
    {
      return _atendimentosOdontologicos;
    }
    set
    {
      __isset.atendimentosOdontologicos = true;
      this._atendimentosOdontologicos = value;
    }
  }

  public int TpCdsOrigem
  {
    get
    {
      return _tpCdsOrigem;
    }
    set
    {
      __isset.tpCdsOrigem = true;
      this._tpCdsOrigem = value;
    }
  }


  public FichaAtendimentoOdontologicoMaster __isset;
  public struct FichaAtendimentoOdontologicoMaster
    {
    public bool headerTransport;
    public bool atendimentosOdontologicos;
    public bool tpCdsOrigem;
  }

  public FichaAtendimentoOdontologicoMasterThrift()
  {
  }

  public FichaAtendimentoOdontologicoMasterThrift(string uuidFicha) : this()
  {
    this.UuidFicha = uuidFicha;
  }

  public FichaAtendimentoOdontologicoMasterThrift DeepCopy()
  {
    var tmp42 = new FichaAtendimentoOdontologicoMasterThrift();
    if((UuidFicha != null))
    {
      tmp42.UuidFicha = this.UuidFicha;
    }
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp42.HeaderTransport = (VariasLotacoesHeaderThrift)this.HeaderTransport.DeepCopy();
    }
    tmp42.__isset.headerTransport = this.__isset.headerTransport;
    if((AtendimentosOdontologicos != null) && __isset.atendimentosOdontologicos)
    {
      tmp42.AtendimentosOdontologicos = this.AtendimentosOdontologicos.DeepCopy();
    }
    tmp42.__isset.atendimentosOdontologicos = this.__isset.atendimentosOdontologicos;
    if(__isset.tpCdsOrigem)
    {
      tmp42.TpCdsOrigem = this.TpCdsOrigem;
    }
    tmp42.__isset.tpCdsOrigem = this.__isset.tpCdsOrigem;
    return tmp42;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_uuidFicha = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              UuidFicha = await iprot.ReadStringAsync(cancellationToken);
              isset_uuidFicha = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Struct)
            {
              HeaderTransport = new VariasLotacoesHeaderThrift();
              await HeaderTransport.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                var _list43 = await iprot.ReadListBeginAsync(cancellationToken);
                AtendimentosOdontologicos = new List<FichaAtendimentoOdontologicoChildThrift>(_list43.Count);
                for(int _i44 = 0; _i44 < _list43.Count; ++_i44)
                {
                  FichaAtendimentoOdontologicoChildThrift _elem45;
                  _elem45 = new FichaAtendimentoOdontologicoChildThrift();
                  await _elem45.ReadAsync(iprot, cancellationToken);
                  AtendimentosOdontologicos.Add(_elem45);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.I32)
            {
              TpCdsOrigem = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_uuidFicha)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp46 = new TStruct("FichaAtendimentoOdontologicoMasterThrift");
      await oprot.WriteStructBeginAsync(tmp46, cancellationToken);
      var tmp47 = new TField();
      if((UuidFicha != null))
      {
        tmp47.Name = "uuidFicha";
        tmp47.Type = TType.String;
        tmp47.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
        await oprot.WriteStringAsync(UuidFicha, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        tmp47.Name = "headerTransport";
        tmp47.Type = TType.Struct;
        tmp47.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
        await HeaderTransport.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if((AtendimentosOdontologicos != null) && __isset.atendimentosOdontologicos)
      {
        tmp47.Name = "atendimentosOdontologicos";
        tmp47.Type = TType.List;
        tmp47.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
        await oprot.WriteListBeginAsync(new TList(TType.Struct, AtendimentosOdontologicos.Count), cancellationToken);
        foreach (FichaAtendimentoOdontologicoChildThrift _iter48 in AtendimentosOdontologicos)
        {
          await _iter48.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteListEndAsync(cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.tpCdsOrigem)
      {
        tmp47.Name = "tpCdsOrigem";
        tmp47.Type = TType.I32;
        tmp47.ID = 4;
        await oprot.WriteFieldBeginAsync(tmp47, cancellationToken);
        await oprot.WriteI32Async(TpCdsOrigem, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is FichaAtendimentoOdontologicoMasterThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return global::System.Object.Equals(UuidFicha, other.UuidFicha)
      && ((__isset.headerTransport == other.__isset.headerTransport) && ((!__isset.headerTransport) || (global::System.Object.Equals(HeaderTransport, other.HeaderTransport))))
      && ((__isset.atendimentosOdontologicos == other.__isset.atendimentosOdontologicos) && ((!__isset.atendimentosOdontologicos) || (TCollections.Equals(AtendimentosOdontologicos, other.AtendimentosOdontologicos))))
      && ((__isset.tpCdsOrigem == other.__isset.tpCdsOrigem) && ((!__isset.tpCdsOrigem) || (global::System.Object.Equals(TpCdsOrigem, other.TpCdsOrigem))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((UuidFicha != null))
      {
        hashcode = (hashcode * 397) + UuidFicha.GetHashCode();
      }
      if((HeaderTransport != null) && __isset.headerTransport)
      {
        hashcode = (hashcode * 397) + HeaderTransport.GetHashCode();
      }
      if((AtendimentosOdontologicos != null) && __isset.atendimentosOdontologicos)
      {
        hashcode = (hashcode * 397) + TCollections.GetHashCode(AtendimentosOdontologicos);
      }
      if(__isset.tpCdsOrigem)
      {
        hashcode = (hashcode * 397) + TpCdsOrigem.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp49 = new StringBuilder("FichaAtendimentoOdontologicoMasterThrift(");
    if((UuidFicha != null))
    {
      tmp49.Append(", UuidFicha: ");
      UuidFicha.ToString(tmp49);
    }
    if((HeaderTransport != null) && __isset.headerTransport)
    {
      tmp49.Append(", HeaderTransport: ");
      HeaderTransport.ToString(tmp49);
    }
    if((AtendimentosOdontologicos != null) && __isset.atendimentosOdontologicos)
    {
      tmp49.Append(", AtendimentosOdontologicos: ");
      AtendimentosOdontologicos.ToString(tmp49);
    }
    if(__isset.tpCdsOrigem)
    {
      tmp49.Append(", TpCdsOrigem: ");
      TpCdsOrigem.ToString(tmp49);
    }
    tmp49.Append(')');
    return tmp49.ToString();
  }
}

