/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using Encore.Domain.Core.Extensions;
using System.Text;
using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions


public partial class ProcedimentoQuantidadeThrift : TBase
{
  private string _coMsProcedimento;
  private int _quantidade;

  public string CoMsProcedimento
  {
    get
    {
      return _coMsProcedimento;
    }
    set
    {
      __isset.coMsProcedimento = true;
      this._coMsProcedimento = value;
    }
  }

  public int Quantidade
  {
    get
    {
      return _quantidade;
    }
    set
    {
      __isset.@quantidade = true;
      this._quantidade = value;
    }
  }


  public ProcedimentoQuantidade __isset;
  public struct ProcedimentoQuantidade
    {
    public bool coMsProcedimento;
    public bool @quantidade;
  }

  public ProcedimentoQuantidadeThrift()
  {
  }

  public ProcedimentoQuantidadeThrift DeepCopy()
  {
    var tmp0 = new ProcedimentoQuantidadeThrift();
    if((CoMsProcedimento != null) && __isset.coMsProcedimento)
    {
      tmp0.CoMsProcedimento = this.CoMsProcedimento;
    }
    tmp0.__isset.coMsProcedimento = this.__isset.coMsProcedimento;
    if(__isset.@quantidade)
    {
      tmp0.Quantidade = this.Quantidade;
    }
    tmp0.__isset.@quantidade = this.__isset.@quantidade;
    return tmp0;
  }

  public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              CoMsProcedimento = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I32)
            {
              Quantidade = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var tmp1 = new TStruct("ProcedimentoQuantidadeThrift");
      await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
      var tmp2 = new TField();
      if((CoMsProcedimento != null) && __isset.coMsProcedimento)
      {
        tmp2.Name = "coMsProcedimento";
        tmp2.Type = TType.String;
        tmp2.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteStringAsync(CoMsProcedimento, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if(__isset.@quantidade)
      {
        tmp2.Name = "quantidade";
        tmp2.Type = TType.I32;
        tmp2.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
        await oprot.WriteI32Async(Quantidade, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    if (!(that is ProcedimentoQuantidadeThrift other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.coMsProcedimento == other.__isset.coMsProcedimento) && ((!__isset.coMsProcedimento) || (global::System.Object.Equals(CoMsProcedimento, other.CoMsProcedimento))))
      && ((__isset.@quantidade == other.__isset.@quantidade) && ((!__isset.@quantidade) || (global::System.Object.Equals(Quantidade, other.Quantidade))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if((CoMsProcedimento != null) && __isset.coMsProcedimento)
      {
        hashcode = (hashcode * 397) + CoMsProcedimento.GetHashCode();
      }
      if(__isset.@quantidade)
      {
        hashcode = (hashcode * 397) + Quantidade.GetHashCode();
      }
    }
    return hashcode;
  }

  public override string ToString()
  {
    var tmp3 = new StringBuilder("ProcedimentoQuantidadeThrift(");
    int tmp4 = 0;
    if((CoMsProcedimento != null) && __isset.coMsProcedimento)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("CoMsProcedimento: ");
      CoMsProcedimento.ToString(tmp3);
    }
    if(__isset.@quantidade)
    {
      if(0 < tmp4++) { tmp3.Append(", "); }
      tmp3.Append("Quantidade: ");
      Quantidade.ToString(tmp3);
    }
    tmp3.Append(')');
    return tmp3.ToString();
  }
}

