using Encore.Domain.Enum;

namespace Encore.Domain.ValueObjects.Person
{
    public class HighestEducationLevel : EsusIntegrationBase<HighestEducationLevel>
    {
        public static HighestEducationLevel Daycare => new HighestEducationLevel { Code = 51, Description = "Creche" };
        public static HighestEducationLevel Preschool => new HighestEducationLevel { Code = 52, Description = "Pré-escola (exceto CA)" };
        public static HighestEducationLevel CAAlphabetizationClass => new HighestEducationLevel { Code = 53, Description = "Classe de alfabetização - CA" };
        public static HighestEducationLevel Elementary1to4 => new HighestEducationLevel { Code = 54, Description = "Ensino fundamental 1ª a 4ª séries" };
        public static HighestEducationLevel Elementary5to8 => new HighestEducationLevel { Code = 55, Description = "Ensino fundamental 5ª a 8ª séries" };
        public static HighestEducationLevel CompleteElementary => new HighestEducationLevel { Code = 56, Description = "Ensino fundamental completo" };
        public static HighestEducationLevel SpecialElementary => new HighestEducationLevel { Code = 61, Description = "Ensino fundamental especial" };
        public static HighestEducationLevel ElementaryEJAStart => new HighestEducationLevel { Code = 58, Description = "Ensino fundamental EJA - séries iniciais (supletivo 1ª a 4ª)" };
        public static HighestEducationLevel ElementaryEJAEnd => new HighestEducationLevel { Code = 59, Description = "Ensino fundamental EJA - séries finais (supletivo 5ª a 8ª)" };
        public static HighestEducationLevel HighSchool => new HighestEducationLevel { Code = 60, Description = "Ensino médio, médio 2º ciclo (científico, técnico e etc)" };
        public static HighestEducationLevel SpecialHighSchool => new HighestEducationLevel { Code = 57, Description = "Ensino médio especial" };
        public static HighestEducationLevel HighSchoolEJA => new HighestEducationLevel { Code = 62, Description = "Ensino médio EJA (supletivo)" };
        public static HighestEducationLevel HigherEducation => new HighestEducationLevel { Code = 63, Description = "Superior, aperfeiçoamento, especialização, mestrado, doutorado" };
        public static HighestEducationLevel AdultLiteracy => new HighestEducationLevel { Code = 64, Description = "Alfabetização para adultos (Mobral, etc)" };
        public static HighestEducationLevel None => new HighestEducationLevel { Code = 65, Description = "Nenhum" };
    }

    public class Occupation : EsusIntegrationBase<Occupation>
    {
        public static Occupation Abatedor => new Occupation { Code = 848505, Description = "ABATEDOR" };
        public static Occupation AcabadorCalcados => new Occupation { Code = 764305, Description = "ACABADOR DE CALÇADOS" };
        public static Occupation AcabadorEmbalagens => new Occupation { Code = 766305, Description = "ACABADOR DE EMBALAGENS (FLEXÍVEIS E CARTOTÉCNICAS)" };
        public static Occupation AcabadorSuperficiesConcreto => new Occupation { Code = 716105, Description = "ACABADOR DE SUPERFÍCIES DE CONCRETO" };
        public static Occupation Acougueiro => new Occupation { Code = 848510, Description = "AÇOUGUEIRO" };
        public static Occupation Acrobata => new Occupation { Code = 376205, Description = "ACROBATA" };
        public static Occupation AdestradorAnimais => new Occupation { Code = 623005, Description = "ADESTRADOR DE ANIMAIS" };
        public static Occupation Administrador => new Occupation { Code = 252105, Description = "ADMINISTRADOR" };
        public static Occupation AdministradorBancoDados => new Occupation { Code = 212305, Description = "ADMINISTRADOR DE BANCO DE DADOS" };
        public static Occupation AdministradorEdificios => new Occupation { Code = 510110, Description = "ADMINISTRADOR DE EDIFÍCIOS" };
        public static Occupation AdministradorFundos => new Occupation { Code = 252505, Description = "ADMINISTRADOR DE FUNDOS E CARTEIRAS DE INVESTIMENTO" };
        public static Occupation AdministradorRedes => new Occupation { Code = 212310, Description = "ADMINISTRADOR DE REDES" };
        public static Occupation AdministradorSistemasOperacionais => new Occupation { Code = 212315, Description = "ADMINISTRADOR DE SISTEMAS OPERACIONAIS" };
        public static Occupation AdministradorSegurancaInformacao => new Occupation { Code = 212320, Description = "ADMINISTRADOR EM SEGURANÇA DA INFORMAÇÃO" };
        public static Occupation Advogado => new Occupation { Code = 241005, Description = "ADVOGADO" };
        public static Occupation AdvogadoAreasEspeciais => new Occupation { Code = 241030, Description = "ADVOGADO (ÁREAS ESPECIAIS)" };
        public static Occupation AdvogadoDireitoCivil => new Occupation { Code = 241015, Description = "ADVOGADO (DIREITO CIVIL)" };
        public static Occupation AdvogadoDireitoTrabalho => new Occupation { Code = 241035, Description = "ADVOGADO (DIREITO DO TRABALHO)" };
        public static Occupation AdvogadoDireitoPenal => new Occupation { Code = 241025, Description = "ADVOGADO (DIREITO PENAL)" };
        public static Occupation AdvogadoDireitoPublico => new Occupation { Code = 241020, Description = "ADVOGADO (DIREITO PÚBLICO)" };
        public static Occupation AdvogadoUniao => new Occupation { Code = 241205, Description = "ADVOGADO DA UNIÃO" };
        public static Occupation AdvogadoEmpresa => new Occupation { Code = 241010, Description = "ADVOGADO DE EMPRESA" };
        public static Occupation AfiadorCardas => new Occupation { Code = 721305, Description = "AFIADOR DE CARDAS" };
        public static Occupation AfiadorCutelaria => new Occupation { Code = 721310, Description = "AFIADOR DE CUTELARIA" };
        public static Occupation AfiadorFerramentas => new Occupation { Code = 721315, Description = "AFIADOR DE FERRAMENTAS" };
        public static Occupation AfiadorSerras => new Occupation { Code = 721320, Description = "AFIADOR DE SERRAS" };
        public static Occupation AfinadorInstrumentosMusicais => new Occupation { Code = 742105, Description = "AFINADOR DE INSTRUMENTOS MUSICAIS" };
        public static Occupation Afretador => new Occupation { Code = 342120, Description = "AFRETADOR" };
        public static Occupation AgenciadorPropaganda => new Occupation { Code = 253140, Description = "AGENCIADOR DE PROPAGANDA" };
        public static Occupation AgenteComunitarioSaude => new Occupation { Code = 515105, Description = "AGENTE COMUNITÁRIO DE SAÚDE" };
        public static Occupation AgenteAcaoSocial => new Occupation { Code = 515310, Description = "AGENTE DE AÇÃO SOCIAL" };
        public static Occupation AgenteCombateEndemias => new Occupation { Code = 515140, Description = "AGENTE DE COMBATE ÀS ENDEMIAS" };
        public static Occupation AgenteDefesaAmbiental => new Occupation { Code = 352205, Description = "AGENTE DE DEFESA AMBIENTAL" };
        public static Occupation AgenteDireitosAutorais => new Occupation { Code = 352405, Description = "AGENTE DE DIREITOS AUTORAIS" };
        public static Occupation AgenteEstacao => new Occupation { Code = 342405, Description = "AGENTE DE ESTAÇÃO (FERROVIA E METRÔ)" };
        public static Occupation AgenteHigieneSeguranca => new Occupation { Code = 254310, Description = "AGENTE DE HIGIENE E SEGURANÇA" };
        public static Occupation AgenteInteligencia => new Occupation { Code = 351905, Description = "AGENTE DE INTELIGÊNCIA" };
        public static Occupation AgenteManobraDocagem => new Occupation { Code = 215105, Description = "AGENTE DE MANOBRA E DOCAGEM" };
        public static Occupation AgenteMicrocredito => new Occupation { Code = 411050, Description = "AGENTE DE MICROCRÉDITO" };
        public static Occupation AgentePatio => new Occupation { Code = 783105, Description = "AGENTE DE PÁTIO" };
        public static Occupation AgentePolíciaFederal => new Occupation { Code = 517205, Description = "AGENTE DE POLÍCIA FEDERAL" };
        public static Occupation AgenteProtecaoAeroporto => new Occupation { Code = 517305, Description = "AGENTE DE PROTEÇÃO DE AEROPORTO" };
        public static Occupation AgenteProtecaoAviacaoCivil => new Occupation { Code = 342550, Description = "AGENTE DE PROTEÇÃO DE AVIAÇÃO CIVIL" };
        public static Occupation AgenteRecrutamentoSelecao => new Occupation { Code = 351315, Description = "AGENTE DE RECRUTAMENTO E SELEÇÃO" };
        public static Occupation AgenteSaudePublica => new Occupation { Code = 352210, Description = "AGENTE DE SAÚDE PÚBLICA" };
        public static Occupation AgenteSeguranca => new Occupation { Code = 517310, Description = "AGENTE DE SEGURANÇA" };
        public static Occupation AgenteSegurancaPenitenciaria => new Occupation { Code = 517315, Description = "AGENTE DE SEGURANÇA PENITENCIÁRIA" };
        public static Occupation AgenteTransito => new Occupation { Code = 517220, Description = "AGENTE DE TRÂNSITO" };
        public static Occupation AgenteVendasServicos => new Occupation { Code = 354120, Description = "AGENTE DE VENDAS DE SERVIÇOS" };
        public static Occupation AgenteViagem => new Occupation { Code = 354815, Description = "AGENTE DE VIAGEM" };
        public static Occupation AgenteFiscalQualidade => new Occupation { Code = 352310, Description = "AGENTE FISCAL DE QUALIDADE" };
        public static Occupation AgenteFiscalMetrologico => new Occupation { Code = 352315, Description = "AGENTE FISCAL METROLÓGICO" };
        public static Occupation AgenteFiscalTextil => new Occupation { Code = 352320, Description = "AGENTE FISCAL TÊXTIL" };
        public static Occupation AgenteFunerario => new Occupation { Code = 516505, Description = "AGENTE FUNERÁRIO" };
        public static Occupation AgenteIndigenaSaneamento => new Occupation { Code = 515130, Description = "AGENTE INDÍGENA DE SANEAMENTO" };
        public static Occupation AgenteIndigenaSaude => new Occupation { Code = 515125, Description = "AGENTE INDÍGENA DE SAÚDE" };
        public static Occupation AgentePublicitario => new Occupation { Code = 253115, Description = "AGENTE PUBLICITÁRIO" };
        public static Occupation AgenteTecnicoInteligencia => new Occupation { Code = 351910, Description = "AGENTE TÉCNICO DE INTELIGÊNCIA" };
        public static Occupation AjudanteCarvoaria => new Occupation { Code = 632615, Description = "AJUDANTE DE CARVOARIA" };
        public static Occupation AjudanteConfeccao => new Occupation { Code = 763125, Description = "AJUDANTE DE CONFECÇÃO" };
        public static Occupation AjudanteDespachanteAduaneiro => new Occupation { Code = 342205, Description = "AJUDANTE DE DESPACHANTE ADUANEIRO" };
        public static Occupation AjudanteMotorista => new Occupation { Code = 783225, Description = "AJUDANTE DE MOTORISTA" };
        public static Occupation AjustadorInstrumentosPrecisao => new Occupation { Code = 741105, Description = "AJUSTADOR DE INSTRUMENTOS DE PRECISÃO" };
        public static Occupation AjustadorFerramenteiro => new Occupation { Code = 725005, Description = "AJUSTADOR FERRAMENTEIRO" };
        public static Occupation AjustadorMecanico => new Occupation { Code = 725010, Description = "AJUSTADOR MECÂNICO" };
        public static Occupation AjustadorMecanicoUsinagem => new Occupation { Code = 725015, Description = "AJUSTADOR MECÂNICO (USINAGEM EM BANCADA E EM MÁQUINAS-FERRAMENTAS)" };
        public static Occupation AjustadorMecanicoBancada => new Occupation { Code = 725020, Description = "AJUSTADOR MECÂNICO EM BANCADA" };
        public static Occupation AjustadorNaval => new Occupation { Code = 725025, Description = "AJUSTADOR NAVAL (REPARO E CONSTRUÇÃO)" };
        public static Occupation Alambiqueiro => new Occupation { Code = 841705, Description = "ALAMBIQUEIRO" };
        public static Occupation Alfaiate => new Occupation { Code = 763005, Description = "ALFAIATE" };
        public static Occupation AlimentadorLinhaProducao => new Occupation { Code = 784205, Description = "ALIMENTADOR DE LINHA DE PRODUÇÃO" };
        public static Occupation AlinhadorPneus => new Occupation { Code = 992105, Description = "ALINHADOR DE PNEUS" };
        public static Occupation Almoxarife => new Occupation { Code = 414105, Description = "ALMOXARIFE" };
        public static Occupation AlvejadorTecidos => new Occupation { Code = 761405, Description = "ALVEJADOR (TECIDOS)" };
        public static Occupation AmostradorMinerios => new Occupation { Code = 711105, Description = "AMOSTRADOR DE MINÉRIOS" };
        public static Occupation AnalistaCambio => new Occupation { Code = 252510, Description = "ANALISTA DE CÂMBIO" };
        public static Occupation AnalistaCobranca => new Occupation { Code = 252515, Description = "ANALISTA DE COBRANÇA (INSTITUIÇÕES FINANCEIRAS)" };
        public static Occupation AnalistaCredito => new Occupation { Code = 252525, Description = "ANALISTA DE CRÉDITO (INSTITUIÇÕES FINANCEIRAS)" };
        public static Occupation AnalistaCreditoRural => new Occupation { Code = 252530, Description = "ANALISTA DE CRÉDITO RURAL" };
        public static Occupation AnalistaDesenvolvimentoSistemas => new Occupation { Code = 212405, Description = "ANALISTA DE DESENVOLVIMENTO DE SISTEMAS" };
        public static Occupation AnalistaExportacaoImportacao => new Occupation { Code = 354305, Description = "ANALISTA DE EXPORTAÇÃO E IMPORTAÇÃO" };
        public static Occupation AnalistaFolhaPagamento => new Occupation { Code = 413105, Description = "ANALISTA DE FOLHA DE PAGAMENTO" };
        public static Occupation AnalistaInformacoes => new Occupation { Code = 261215, Description = "ANALISTA DE INFORMAÇÕES (PESQUISADOR DE INFORMAÇÕES DE REDE)" };
        public static Occupation AnalistaLeasing => new Occupation { Code = 252535, Description = "ANALISTA DE LEASING" };
        public static Occupation AnalistaNegocios => new Occupation { Code = 142330, Description = "ANALISTA DE NEGÓCIOS" };
        public static Occupation AnalistaPesquisaMercado => new Occupation { Code = 142335, Description = "ANALISTA DE PESQUISA DE MERCADO" };
        public static Occupation AnalistaPlanejamentoOrcamento => new Occupation { Code = 111510, Description = "ANALISTA DE PLANEJAMENTO E ORÇAMENTO - APO" };
        public static Occupation AnalistaProdutosBancarios => new Occupation { Code = 252540, Description = "ANALISTA DE PRODUTOS BANCÁRIOS" };
        public static Occupation AnalistaRecursosHumanos => new Occupation { Code = 252405, Description = "ANALISTA DE RECURSOS HUMANOS" };
        public static Occupation AnalistaRedesComunicacaoDados => new Occupation { Code = 212410, Description = "ANALISTA DE REDES E DE COMUNICAÇÃO DE DADOS" };
        public static Occupation AnalistaSeguros => new Occupation { Code = 351705, Description = "ANALISTA DE SEGUROS (TÉCNICO)" };
        public static Occupation AnalistaSinistros => new Occupation { Code = 351710, Description = "ANALISTA DE SINISTROS" };
        public static Occupation AnalistaSistemasAutomacao => new Occupation { Code = 212415, Description = "ANALISTA DE SISTEMAS DE AUTOMAÇÃO" };
        public static Occupation AnalistaSuporteComputacional => new Occupation { Code = 212420, Description = "ANALISTA DE SUPORTE COMPUTACIONAL" };
        public static Occupation AnalistaTransporteComercioExterior => new Occupation { Code = 342105, Description = "ANALISTA DE TRANSPORTE EM COMÉRCIO EXTERIOR" };
        public static Occupation AnalistaFinanceiro => new Occupation { Code = 252545, Description = "ANALISTA FINANCEIRO (INSTITUIÇÕES FINANCEIRAS)" };
        public static Occupation AncoraRadioTelevisao => new Occupation { Code = 261705, Description = "ANCORA DE RÁDIO E TELEVISÃO" };
        public static Occupation Antropologo => new Occupation { Code = 251105, Description = "ANTROPÓLOGO" };
        public static Occupation Apicultor => new Occupation { Code = 613405, Description = "APICULTOR" };
        public static Occupation AplicadorAsfaltoImpermeabilizante => new Occupation { Code = 715705, Description = "APLICADOR DE ASFALTO IMPERMEABILIZANTE (COBERTURAS)" };
        public static Occupation AplicadorSerigraficoVidros => new Occupation { Code = 752205, Description = "APLICADOR SERIGRÁFICO EM VIDROS" };
        public static Occupation ApontadorMaoObra => new Occupation { Code = 414205, Description = "APONTADOR DE MÃO-DE-OBRA" };
        public static Occupation ApontadorProducao => new Occupation { Code = 414210, Description = "APONTADOR DE PRODUÇÃO" };
        public static Occupation ApresentadorCirco => new Occupation { Code = 376325, Description = "APRESENTADOR DE CIRCO" };
        public static Occupation ApresentadorEventos => new Occupation { Code = 376305, Description = "APRESENTADOR DE EVENTOS" };
        public static Occupation ApresentadorFestasPopulares => new Occupation { Code = 376310, Description = "APRESENTADOR DE FESTAS POPULARES" };
        public static Occupation ApresentadorProgramasRadio => new Occupation { Code = 376315, Description = "APRESENTADOR DE PROGRAMAS DE RÁDIO" };
        public static Occupation ApresentadorProgramasTelevisao => new Occupation { Code = 376320, Description = "APRESENTADOR DE PROGRAMAS DE TELEVISÃO" };
        public static Occupation ArbitroAtletismo => new Occupation { Code = 377210, Description = "ARBITRO DE ATLETISMO" };
        public static Occupation ArbitroBasquete => new Occupation { Code = 377215, Description = "ARBITRO DE BASQUETE" };
        public static Occupation ArbitroFutebol => new Occupation { Code = 377220, Description = "ARBITRO DE FUTEBOL" };
        public static Occupation ArbitroFutebolSalao => new Occupation { Code = 377225, Description = "ARBITRO DE FUTEBOL DE SALÃO" };
        public static Occupation ArbitroJudo => new Occupation { Code = 377230, Description = "ARBITRO DE JUDÔ" };
        public static Occupation ArbitroKarate => new Occupation { Code = 377235, Description = "ARBITRO DE KARATÊ" };
        public static Occupation ArbitroPoloAquatico => new Occupation { Code = 377240, Description = "ARBITRO DE POLÓ AQUÁTICO" };
        public static Occupation ArbitroDesportivo => new Occupation { Code = 377205, Description = "ARBITRO DESPORTIVO" };
        public static Occupation ArbitroVolei => new Occupation { Code = 377245, Description = "ARBITRO DE VÔLEI" };
        public static Occupation ArmadorEstruturaConcreto => new Occupation { Code = 715305, Description = "ARMADOR DE ESTRUTURA DE CONCRETO" };
        public static Occupation ArmadorEstruturaConcretoArmado => new Occupation { Code = 715315, Description = "ARMADOR DE ESTRUTURA DE CONCRETO ARMADO" };
        public static Occupation Armazenista => new Occupation { Code = 414110, Description = "ARMAZENISTA" };
        public static Occupation Aromista => new Occupation { Code = 325010, Description = "AROMISTA" };
        public static Occupation Arqueologo => new Occupation { Code = 251110, Description = "ARQUEÓLOGO" };
        public static Occupation ArquitetoEdificacoes => new Occupation { Code = 214105, Description = "ARQUITETO DE EDIFICAÇÕES" };
        public static Occupation ArquitetoInteriores => new Occupation { Code = 214110, Description = "ARQUITETO DE INTERIORES" };
        public static Occupation ArquitetoPatrimonio => new Occupation { Code = 214115, Description = "ARQUITETO DE PATRIMÔNIO" };
        public static Occupation ArquitetoPaisagista => new Occupation { Code = 214120, Description = "ARQUITETO PAISAGISTA" };
        public static Occupation ArquitetoUrbanista => new Occupation { Code = 214125, Description = "ARQUITETO URBANISTA" };
        public static Occupation Arquivista => new Occupation { Code = 261305, Description = "ARQUIVISTA" };
        public static Occupation ArquivistaDocumentos => new Occupation { Code = 415105, Description = "ARQUIVISTA DE DOCUMENTOS" };
        public static Occupation ArquivistaPesquisadorJornalismo => new Occupation { Code = 261105, Description = "ARQUIVISTA PESQUISADOR (JORNALISMO)" };
        public static Occupation Arrematadeira => new Occupation { Code = 763305, Description = "ARREMATADEIRA" };
        public static Occupation ArtesaoBordador => new Occupation { Code = 791105, Description = "ARTESÃO BORDADOR" };
        public static Occupation ArtesaoCeramista => new Occupation { Code = 791110, Description = "ARTESÃO CERAMISTA" };
        public static Occupation ArtesaoMaterialReciclavel => new Occupation { Code = 791115, Description = "ARTESÃO COM MATERIAL RECICLÁVEL" };
        public static Occupation ArtesaoConfeccionadorBiojoiasEcjoias => new Occupation { Code = 791120, Description = "ARTESÃO CONFECCIONADOR DE BIOJÓIAS E ECOJÓIAS" };
        public static Occupation ArtesaoCrocheteiro => new Occupation { Code = 791150, Description = "ARTESÃO CROCHETEIRO" };
        public static Occupation ArtesaoCouro => new Occupation { Code = 791125, Description = "ARTESÃO DO COURO" };
        public static Occupation ArtesaoEscultor => new Occupation { Code = 791130, Description = "ARTESÃO ESCULTOR" };
        public static Occupation ArtesaoModeladorVidros => new Occupation { Code = 752105, Description = "ARTESÃO MODELADOR (VIDROS)" };
        public static Occupation ArtesaoMoveleiro => new Occupation { Code = 791135, Description = "ARTESÃO MOVELEIRO (EXCETO RECICLADO)" };
        public static Occupation ArtesaoRendeiro => new Occupation { Code = 791160, Description = "ARTESÃO RENDEIRO" };
        public static Occupation ArtesaoTecelao => new Occupation { Code = 791140, Description = "ARTESÃO TECELÃO" };
        public static Occupation ArtesaoTrancador => new Occupation { Code = 791145, Description = "ARTESÃO TRANÇADOR" };
        public static Occupation ArtesaoTricoteiro => new Occupation { Code = 791155, Description = "ARTESÃO TRICOTEIRO" };
        public static Occupation Arteterapeuta => new Occupation { Code = 226310, Description = "ARTETERAPEUTA" };
        public static Occupation ArtificeCouro => new Occupation { Code = 768305, Description = "ARTÍFICE DO COURO" };
        public static Occupation ArtistaArtesVisuais => new Occupation { Code = 262405, Description = "ARTISTA (ARTES VISUAIS)" };
        public static Occupation ArtistaAereo => new Occupation { Code = 376210, Description = "ARTISTA AÉREO" };
        public static Occupation ArtistaCirco => new Occupation { Code = 376215, Description = "ARTISTA DE CIRCO (OUTROS)" };
        public static Occupation Ascensorista => new Occupation { Code = 514105, Description = "ASCENSORISTA" };
        public static Occupation AssentadorCanalizacao => new Occupation { Code = 724105, Description = "ASSENTADOR DE CANALIZAÇÃO (EDIFICAÇÕES)" };
        public static Occupation AssessorImprensa => new Occupation { Code = 261110, Description = "ASSESSOR DE IMPRENSA" };
        public static Occupation AssistenteAdministrativo => new Occupation { Code = 411010, Description = "ASSISTENTE ADMINISTRATIVO" };
        public static Occupation AssistenteComercialSeguros => new Occupation { Code = 351715, Description = "ASSISTENTE COMERCIAL DE SEGUROS" };
        public static Occupation AssistenteCoreografia => new Occupation { Code = 262805, Description = "ASSISTENTE DE COREOGRAFIA" };
        public static Occupation AssistenteLaboratorioIndustrial => new Occupation { Code = 818105, Description = "ASSISTENTE DE LABORATÓRIO INDUSTRIAL" };
        public static Occupation AssistenteVendas => new Occupation { Code = 354125, Description = "ASSISTENTE DE VENDAS" };
        public static Occupation AssistenteSocial => new Occupation { Code = 251605, Description = "ASSISTENTE SOCIAL" };
        public static Occupation AssistenteTecnicoSeguros => new Occupation { Code = 351720, Description = "ASSISTENTE TÉCNICO DE SEGUROS" };
        public static Occupation Assoalhador => new Occupation { Code = 716505, Description = "ASSOALHADOR" };
        public static Occupation Astrólogo => new Occupation { Code = 516705, Description = "ASTRÓLOGO" };
        public static Occupation Astronomo => new Occupation { Code = 213305, Description = "ASTRÔNOMO" };
        public static Occupation AtendenteComercialAgenciaPostal => new Occupation { Code = 421105, Description = "ATENDENTE COMERCIAL (AGÊNCIA POSTAL)" };
        public static Occupation AtendenteAgencia => new Occupation { Code = 413205, Description = "ATENDENTE DE AGÊNCIA" };
        public static Occupation AtendenteEnfermagem => new Occupation { Code = 515110, Description = "ATENDENTE DE ENFERMAGEM" };
        public static Occupation AtendenteFarmaciaBalconista => new Occupation { Code = 521130, Description = "ATENDENTE DE FARMÁCIA - BALCONISTA" };
        public static Occupation AtendenteJudiciario => new Occupation { Code = 411015, Description = "ATENDENTE DE JUDICIÁRIO" };
        public static Occupation AtendenteLanchonete => new Occupation { Code = 513435, Description = "ATENDENTE DE LANCHONETE" };
        public static Occupation AtendenteLavanderia => new Occupation { Code = 516340, Description = "ATENDENTE DE LAVANDERIA" };
        public static Occupation AtendenteLojasMercados => new Occupation { Code = 521140, Description = "ATENDENTE DE LOJAS E MERCADOS" };
        public static Occupation AtletaProfissionalOutrasModalidades => new Occupation { Code = 377105, Description = "ATLETA PROFISSIONAL (OUTRAS MODALIDADES)" };
        public static Occupation AtletaProfissionalFutebol => new Occupation { Code = 377110, Description = "ATLETA PROFISSIONAL DE FUTEBOL" };
        public static Occupation AtletaProfissionalGolfe => new Occupation { Code = 377115, Description = "ATLETA PROFISSIONAL DE GOLFE" };
        public static Occupation AtletaProfissionalLuta => new Occupation { Code = 377120, Description = "ATLETA PROFISSIONAL DE LUTA" };
        public static Occupation AtletaProfissionalTenis => new Occupation { Code = 377125, Description = "ATLETA PROFISSIONAL DE TÊNIS" };
        public static Occupation Ator => new Occupation { Code = 262505, Description = "ATOR" };
        public static Occupation Atuario => new Occupation { Code = 211105, Description = "ATUÁRIO" };
        public static Occupation Audiodescritor => new Occupation { Code = 261430, Description = "AUDIODESCRITOR" };
        public static Occupation AuditorContadoresAfins => new Occupation { Code = 252205, Description = "AUDITOR (CONTADORES E AFINS)" };
        public static Occupation AuditorFiscalPrevidenciaSocial => new Occupation { Code = 254205, Description = "AUDITOR-FISCAL DA PREVIDÊNCIA SOCIAL" };
        public static Occupation AuditorFiscalReceitaFederal => new Occupation { Code = 254105, Description = "AUDITOR-FISCAL DA RECEITA FEDERAL" };
        public static Occupation AuditorFiscalTrabalho => new Occupation { Code = 254305, Description = "AUDITOR-FISCAL DO TRABALHO" };
        public static Occupation AutorRoteirista => new Occupation { Code = 261505, Description = "AUTOR-ROTEIRISTA" };
        public static Occupation AuxiliarBancoSangue => new Occupation { Code = 515205, Description = "AUXILIAR DE BANCO DE SANGUE" };
        public static Occupation AuxiliarBiblioteca => new Occupation { Code = 371105, Description = "AUXILIAR DE BIBLIOTECA" };
        public static Occupation AuxiliarCartorio => new Occupation { Code = 411025, Description = "AUXILIAR DE CARTÓRIO" };
        public static Occupation AuxiliarContabilidade => new Occupation { Code = 413110, Description = "AUXILIAR DE CONTABILIDADE" };
        public static Occupation AuxiliarCortePreparacaoConfeccaoRoupas => new Occupation { Code = 763105, Description = "AUXILIAR DE CORTE (PREPARAÇÃO DA CONFECÇÃO DE ROUPAS)" };
        public static Occupation AuxiliarDesenvolvimentoInfantil => new Occupation { Code = 331110, Description = "AUXILIAR DE DESENVOLVIMENTO INFANTIL" };
        public static Occupation AuxiliarEnfermagem => new Occupation { Code = 322230, Description = "AUXILIAR DE ENFERMAGEM" };
        public static Occupation AuxiliarEnfermagemEstrategiaSaudeFamilia => new Occupation { Code = 322250, Description = "AUXILIAR DE ENFERMAGEM DA ESTRATÉGIA DE SAÚDE DA FAMÍLIA" };
        public static Occupation AuxiliarEnfermagemTrabalho => new Occupation { Code = 322235, Description = "AUXILIAR DE ENFERMAGEM DO TRABALHO" };
        public static Occupation AuxiliarEscritorioGeral => new Occupation { Code = 411005, Description = "AUXILIAR DE ESCRITÓRIO, EM GERAL" };
        public static Occupation AuxiliarEstatistica => new Occupation { Code = 411035, Description = "AUXILIAR DE ESTATÍSTICA" };
        public static Occupation AuxiliarFarmaciaManipulacao => new Occupation { Code = 515210, Description = "AUXILIAR DE FARMÁCIA DE MANIPULAÇÃO" };
        public static Occupation AuxiliarFaturamento => new Occupation { Code = 413115, Description = "AUXILIAR DE FATURAMENTO" };
        public static Occupation AuxiliarJudiciario => new Occupation { Code = 411020, Description = "AUXILIAR DE JUDICIÁRIO" };
        public static Occupation AuxiliarLaboratorioAnalisesClinicas => new Occupation { Code = 515215, Description = "AUXILIAR DE LABORATÓRIO DE ANÁLISES CLÍNICAS" };
        public static Occupation AuxiliarLaboratorioAnalisesFisicoQuimicas => new Occupation { Code = 818110, Description = "AUXILIAR DE LABORATÓRIO DE ANÁLISES FÍSICO-QUÍMICAS" };
        public static Occupation AuxiliarLaboratorioImunobiologicos => new Occupation { Code = 515220, Description = "AUXILIAR DE LABORATÓRIO DE IMUNOBIOLÓGICOS" };
        public static Occupation AuxiliarLavanderia => new Occupation { Code = 516345, Description = "AUXILIAR DE LAVANDERIA" };
        public static Occupation AuxiliarManutencaoPredial => new Occupation { Code = 514310, Description = "AUXILIAR DE MANUTENÇÃO PREDIAL" };
        public static Occupation AuxiliarMaquinistaTrem => new Occupation { Code = 782625, Description = "AUXILIAR DE MAQUINISTA DE TREM" };
        public static Occupation AuxiliarPessoal => new Occupation { Code = 411030, Description = "AUXILIAR DE PESSOAL" };
        public static Occupation AuxiliarProcessamentoFumo => new Occupation { Code = 842120, Description = "AUXILIAR DE PROCESSAMENTO DE FUMO" };
        public static Occupation AuxiliarProducaoFarmaceutica => new Occupation { Code = 515225, Description = "AUXILIAR DE PRODUÇÃO FARMACÊUTICA" };
        public static Occupation AuxiliarProteseDentaria => new Occupation { Code = 322420, Description = "AUXILIAR DE PRÓTESE DENTÁRIA" };
        public static Occupation AuxiliarRadiologiaRevelacaoFotografica => new Occupation { Code = 766420, Description = "AUXILIAR DE RADIOLOGIA (REVELAÇÃO FOTOGRÁFICA)" };
        public static Occupation AuxiliarSaudeNavegacaoMaritima => new Occupation { Code = 322240, Description = "AUXILIAR DE SAÚDE (NAVEGAÇÃO MARÍTIMA)" };
        public static Occupation AuxiliarSeguros => new Occupation { Code = 411040, Description = "AUXILIAR DE SEGUROS" };
        public static Occupation AuxiliarServicosImportacaoExportacao => new Occupation { Code = 411045, Description = "AUXILIAR DE SERVIÇOS DE IMPORTAÇÃO E EXPORTAÇÃO" };
        public static Occupation AuxiliarServicosJuridicos => new Occupation { Code = 351430, Description = "AUXILIAR DE SERVIÇOS JURÍDICOS" };
        public static Occupation AuxiliarVeterinario => new Occupation { Code = 519305, Description = "AUXILIAR DE VETERINÁRIO" };
        public static Occupation AuxiliarSaudeBucal => new Occupation { Code = 322415, Description = "AUXILIAR EM SAÚDE BUCAL" };
        public static Occupation AuxiliarSaudeBucalEstrategiaSaudeFamilia => new Occupation { Code = 322430, Description = "AUXILIAR EM SAÚDE BUCAL DA ESTRATÉGIA DE SAÚDE DA FAMÍLIA" };
        public static Occupation AuxiliarGeralConservacaoViasPermanentesExcetoTrilhos => new Occupation { Code = 992225, Description = "AUXILIAR GERAL DE CONSERVAÇÃO DE VIAS PERMANENTES (EXCETO TRILHOS)" };
        public static Occupation AuxiliarServicosAlimentacao => new Occupation { Code = 513505, Description = "AUXILIAR NOS SERVIÇOS DE ALIMENTAÇÃO" };
        public static Occupation AuxiliarTecnicoLaboratorioFarmacia => new Occupation { Code = 325105, Description = "AUXILIAR TÉCNICO EM LABORATÓRIO DE FARMÁCIA" };
        public static Occupation AuxiliarTecnicoPatologiaClinica => new Occupation { Code = 324210, Description = "AUXILIAR TÉCNICO EM PATOLOGIA CLÍNICA" };
        public static Occupation AvaliadorBensMoveis => new Occupation { Code = 354415, Description = "AVALIADOR DE BENS MÓVEIS" };
        public static Occupation AvaliadorImoveis => new Occupation { Code = 354410, Description = "AVALIADOR DE IMÓVEIS" };
        public static Occupation AvaliadorProdutosMeioComunicacao => new Occupation { Code = 352410, Description = "AVALIADOR DE PRODUTOS DO MEIO DE COMUNICAÇÃO" };
        public static Occupation AvaliadorFisico => new Occupation { Code = 224105, Description = "AVALIADOR FÍSICO" };
        public static Occupation Avicultor => new Occupation { Code = 613305, Description = "AVICULTOR" };
        public static Occupation Baba => new Occupation { Code = 516205, Description = "BABÁ" };
        public static Occupation BailarinoExcetoDancasPopulares => new Occupation { Code = 262810, Description = "BAILARINO (EXCETO DANÇAS POPULARES)" };
        public static Occupation Balanceador => new Occupation { Code = 992110, Description = "BALANCEADOR" };
        public static Occupation Balanceiro => new Occupation { Code = 414115, Description = "BALANCEIRO" };
        public static Occupation Bamburista => new Occupation { Code = 811705, Description = "BAMBURISTA" };
        public static Occupation BanhistaAnimaisDomesticos => new Occupation { Code = 519315, Description = "BANHISTA DE ANIMAIS DOMÉSTICOS" };
        public static Occupation Barbeiro => new Occupation { Code = 516105, Description = "BARBEIRO" };
        public static Occupation Barista => new Occupation { Code = 513440, Description = "BARISTA" };
        public static Occupation Barman => new Occupation { Code = 513420, Description = "BARMAN" };
        public static Occupation BateFolhaMaquina => new Occupation { Code = 751105, Description = "BATE-FOLHA A MÁQUINA" };
        public static Occupation Bibliotecario => new Occupation { Code = 261205, Description = "BIBLIOTECÁRIO" };
        public static Occupation BilheteiroEstacoesMetroFerroviariasAssemelhadas => new Occupation { Code = 511220, Description = "BILHETEIRO (ESTAÇÕES DE METRÔ, FERROVIÁRIAS E ASSEMELHADAS)" };
        public static Occupation BilheteiroTransportesColetivos => new Occupation { Code = 421110, Description = "BILHETEIRO DE TRANSPORTES COLETIVOS" };
        public static Occupation BilheteiroServicoDiversoes => new Occupation { Code = 421115, Description = "BILHETEIRO NO SERVIÇO DE DIVERSÕES" };
        public static Occupation Bioengenheiro => new Occupation { Code = 201105, Description = "BIOENGENHEIRO" };
        public static Occupation Biologo => new Occupation { Code = 221105, Description = "BIÓLOGO" };
        public static Occupation Biomedico => new Occupation { Code = 221205, Description = "BIOMÉDICO" };
        public static Occupation Biotecnologista => new Occupation { Code = 201110, Description = "BIOTECNOLOGISTA" };
        public static Occupation BloqueiroTrabalhadorPortuario => new Occupation { Code = 783230, Description = "BLOQUEIRO (TRABALHADOR PORTUÁRIO)" };
        public static Occupation BobinadorEletricistaMao => new Occupation { Code = 731165, Description = "BOBINADOR ELETRICISTA, A MÃO" };
        public static Occupation BobinadorEletricistaMaquina => new Occupation { Code = 731170, Description = "BOBINADOR ELETRICISTA, A MÁQUINA" };
        public static Occupation Boiadeiro => new Occupation { Code = 782815, Description = "BOIADEIRO" };
        public static Occupation BombeiroAerodromo => new Occupation { Code = 517105, Description = "BOMBEIRO DE AERÓDROMO" };
        public static Occupation BombeiroSegurancaTrabalho => new Occupation { Code = 517110, Description = "BOMBEIRO DE SEGURANÇA DO TRABALHO" };
        public static Occupation Boneleiro => new Occupation { Code = 765015, Description = "BONELEIRO" };
        public static Occupation BordadorMao => new Occupation { Code = 768205, Description = "BORDADOR, A MÃO" };
        public static Occupation BordadorMaquina => new Occupation { Code = 763310, Description = "BORDADOR, A MÁQUINA" };
        public static Occupation Borracheiro => new Occupation { Code = 992115, Description = "BORRACHEIRO" };
        public static Occupation Brasador => new Occupation { Code = 724305, Description = "BRASADOR" };
        public static Occupation Cabeleireiro => new Occupation { Code = 516110, Description = "CABELEIREIRO" };
        public static Occupation Cableador => new Occupation { Code = 722405, Description = "CABLEADOR" };
        public static Occupation CaboBombeiroMilitar => new Occupation { Code = 031205, Description = "CABO BOMBEIRO MILITAR" };
        public static Occupation CaboPoliciaMilitar => new Occupation { Code = 021205, Description = "CABO DA POLÍCIA MILITAR" };
        public static Occupation Cacique => new Occupation { Code = 113005, Description = "CACIQUE" };
        public static Occupation Cafeicultor => new Occupation { Code = 612605, Description = "CAFEICULTOR" };
        public static Occupation CaixaBanco => new Occupation { Code = 413210, Description = "CAIXA DE BANCO" };
        public static Occupation Calafetador => new Occupation { Code = 716605, Description = "CALAFETADOR" };
        public static Occupation CalandristaBorracha => new Occupation { Code = 811710, Description = "CALANDRISTA DE BORRACHA" };
        public static Occupation CalandristaPapel => new Occupation { Code = 832105, Description = "CALANDRISTA DE PAPEL" };
        public static Occupation Calceteiro => new Occupation { Code = 715205, Description = "CALCETEIRO" };
        public static Occupation CaldeireiroChapasCobre => new Occupation { Code = 724405, Description = "CALDEIREIRO (CHAPAS DE COBRE)" };
        public static Occupation CaldeireiroChapasFerroAco => new Occupation { Code = 724410, Description = "CALDEIREIRO (CHAPAS DE FERRO E AÇO)" };
        public static Occupation CamareiraTeatro => new Occupation { Code = 513305, Description = "CAMAREIRA DE TEATRO" };
        public static Occupation CamareiraTelevisao => new Occupation { Code = 513310, Description = "CAMAREIRA DE TELEVISÃO" };
        public static Occupation CamareiroEmbarcacoes => new Occupation { Code = 513320, Description = "CAMAREIRO DE EMBARCAÇÕES" };
        public static Occupation CamareiroHotel => new Occupation { Code = 513315, Description = "CAMAREIRO DE HOTEL" };
        public static Occupation CaminhoneiroAutonomoRotasRegionaisInternacionais => new Occupation { Code = 782505, Description = "CAMINHONEIRO AUTÔNOMO (ROTAS REGIONAIS E INTERNACIONAIS)" };

    }



}
